### ISSUE TITLE
AMQP-cpp/examples/rpc_server crash if onReceived has long running code

### ISSUE THREAD

**Issue by njs-sys** [CopernicaMarketingSoftware/AMQP-CPP#100]
Hi,
As shown below whenever I have code in OnReceived() that takes more than a couple of minutes to run, the rpc_server crashes. Is this a known issue? What is the solution for this? Code snippet has been pasted below..
Thanks

    channel.consume("").onReceived([&channel](const AMQP::Message &message,
            uint64_t deliveryTag,
            bool redelivered)
    {
        const auto body = message.message();
        std::cout<<" [.] fib("<<body<<")"<<std::endl;

///long running code or sleep
sleep(700);
///long running code or sleep

        AMQP::Envelope env(std::to_string(fib(std::stoi(body))));
        env.setCorrelationID(message.correlationID());

        channel.publish("", message.replyTo(), env);
        channel.ack(deliveryTag);
    });

**Comment by EmielBruijntjes** [comment]
RabbitMQ send heartbeat messages to the client to check whether it is still alive. The connection is closed if the client does not respond in time to these heartbeat messages. This means that you cannot have a long-running function that blocks the event loop.

You can disable these heartbeats by implementing the ConnectionHandler::onNegotiate() method. If you simply return 0, no heartbeat frames will be sent. However, in my opinion it is better to keep the heartbeats alive, and choose an alternative architecture for your application in which the event loop is not disrupted for such a long time (for example: start a seperate thread to do the long-lasting work).

On top of that, you must also make sure that the SIGPIPE signal is ignored by your program. This is as simple as calling `signal(SIGPIPE, SIG_IGN)` right after your program starts. Sometimes this signal is triggered when AMQP-CPP tries to send data to a lost connection.

**Comment by njs-sys** [comment]
I added onNegotiate() to asiohandler and returned 0. Also added  signal(SIGPIPE, SIG_IGN) to the rpc_server and retried. The code snippet pasted above still crashes with the same error on Ubuntu..

 [x] Awaiting RPC requests
 [.] fib(30)
Error writing:system:32
terminate called after throwing an instance of 'boost::system::error_code'
Aborted

Our adaptation of rpc_server is supposed to return a response after a lengthy computation and the client is waiting for that response.  If I thread the computation and return immediately, then rpc_server is likely to pick the next request even before it has finished computing for the first request. Is there any example of the right way to use this for lengthy request processing on the server side?

Thanks

**Comment by akay25** [comment]
As pointed out by @EmielBruijntjes, putting blocking operation in event loop is really a bad idea. I was having trouble with "Connection lost" error for past 2 days and I tried all examples with heartbeats and onNegotiate as 0 as well but my code threw error exact after 32 secs. After running the blocking operation in separate thread it finally stopped.

I hope this helps someone else too.
