### ISSUE TITLE
writing:system:14

### ISSUE THREAD

**Issue by qrpike** [CopernicaMarketingSoftware/AMQP-CPP#101]
I get this error randomly:

`writing:system:14`

Can't find what this actually means. If it's a connection issue or a channel publish'ing error.

Thanks,

**Comment by EmielBruijntjes** [comment]
I think it is a boost error. I have no idea what it means either, I'm not a boost expert. I've removed all boost examples, because people keep asking questions about them, and the person who once wrote these examples does not answer these calls.
