### ISSUE TITLE
Not sending message after connect.

### ISSUE THREAD

**Issue by Grinder777** [CopernicaMarketingSoftware/AMQP-CPP#102]
Hello, Im trying to realize cycle message producer. I'm using example from test with libevent.
After creating queue  in another thread im starting to publish messages to queue somtimes its ok but sometimes messages dont get to queue.  RabbitMq  configured in cluster mode on 2 machines. Message size from 100kb to 50mb.

**Comment by martijnotto** [comment]
Don't use threads.

**Comment by Grinder777** [comment]
Why? Look in main thread i use event_base_dispatch(evbase) func which block my main thread. In another thread  i publish messages in cycle.  How i can constantly зpublish messages without second thread?
