### ISSUE TITLE
The problem using publish/subscrible, the subscribler crash after running about 4minutes

### ISSUE THREAD

**Issue by xupanwilson** [CopernicaMarketingSoftware/AMQP-CPP#103]
I am using the TcpConnections and LibEvent, and I am running it in my linux machine for test, you can copy and save in a file and build it like the comments in the file.

**The subscrible:**
//g++ -g -std=c++11 -o event_rpc_client_class event_rpc_client_class.cpp -levent -lamqpcpp -pthread
// #include<unistd.h>
#include <iostream>
#include <signal.h>
#include "tools.h"
#include <event2/event.h>
#include <event2/event_struct.h>
#include <event2/util.h>
#include <amqpcpp.h>
#include <amqpcpp/libevent.h>
using namespace std;

int main(int argc, const char* argv[])
{
	signal(SIGPIPE,SIG_IGN);
	event_base *base;
	string host;
	int port;
	string user;
	string password;
	int timeout;
	string channelName;

	base = event_base_new();
	host = "192.1.101.83";
	port = 5672;
	user = "epri";
	password = "123456";
	timeout = 3;
	channelName = "logs";

	AMQP::LibEventHandler handler(base);
	AMQP::TcpConnection connection(&handler, AMQP::Address(host,port,AMQP::Login(user, password), "/"));
	AMQP::TcpChannel channel(&connection);
	//channel.
	auto receiveMessageCallback = [](const AMQP::Message &message,
			uint64_t deliveryTag,
			bool redelivered)
	{

		std::cout <<"Receive: [x] "<<message.message() << std::endl;
	};

	AMQP::ErrorCallback error = [&](const char * msg)
	{
		cout << msg << endl;
	};

	AMQP::QueueCallback callback =
			[&](const std::string &name, int msgcount, int consumercount)
			{
				channel.bindQueue(channelName, name,"");
				channel.consume(name, AMQP::noack).onReceived(receiveMessageCallback).onError(error);
			};

	AMQP::SuccessCallback success = [&]()
			{
				channel.declareQueue(AMQP::exclusive).onSuccess(callback);
			};

	channel.declareExchange(channelName, AMQP::fanout).onSuccess(success);

	std::cout << " [*] Waiting for messages. To exit press CTRL-C\n";

	event_base_dispatch(base);
	return 0;
}

**The publisher:**

//g++ -g -std=c++11 -o event_rpc_client_class event_rpc_client_class.cpp -levent -lamqpcpp -pthread
// #include<unistd.h>
#include <iostream>
#include <signal.h>
#include "tools.h"
#include <event2/event.h>
#include <event2/event_struct.h>
#include <event2/util.h>
#include <amqpcpp.h>
#include <amqpcpp/libevent.h>
using namespace std;

int send()
{
	signal(SIGPIPE,SIG_IGN);
	event_base *base;
	string host;
	int port;
	string user;
	string password;
	int timeout;
	string channelName;

	base = event_base_new();
	host = "192.1.101.83";
	port = 5672;
	user = "epri";
	password = "123456";
	timeout = 3;
	channelName = "logs";

	AMQP::LibEventHandler handler(base);
	AMQP::TcpConnection connection(&handler, AMQP::Address(host,port,AMQP::Login(user, password), "/"));
	AMQP::TcpChannel channel(&connection);

	timeval tv;
	tv.tv_sec = 5;
	tv.tv_usec = 0;
	event_base_loopexit(base, &tv);

	channel.declareExchange(channelName,AMQP::fanout).onSuccess([&]()
	{
		string msg = "I am publishing a message. ";
		channel.publish(channelName, "", msg);
		std::cout << " Send: [x] "<<msg << std::endl;
		event_base_loopbreak(base);
	});

	event_base_dispatch(base);
	event_base_free(base);
	return 0;
}
int main(int argc, const char* argv[])
{
	while(1)
	{
		send();
		sleep(1);
	}
}

**Comment by xupanwilson** [comment]
I changed the onHeartBeat method to print the message, the onHeartBeat method is never reached.

**Comment by EmielBruijntjes** [comment]
This is mostly copied code from an example that we have already removed from the website because we do not approve it any longer.

To report bugs, show the smallest possible program that causes the problem.
