### ISSUE TITLE
endian.h conflicts with x86_64/linux-gnu/bits/waitstatus.h

### ISSUE THREAD

**Issue by j6mes** [CopernicaMarketingSoftware/AMQP-CPP#104]
I'm having an issue compiling my RPC client on both Ubuntu 16.04 and Debian 8.5, compiling with either g++ 5.4 and g++4.9 respectively. 

The code previously worked on my mac, when compiling with clang-703.0.31

It looks like a lot of the names defined in endian.h are already defined in my x86_64/linux-gnu/bits/waitstatus.h https://gist.github.com/j6mes/d963dbc81efeeef884283467fb075d2a

```
g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
```

```
uname -a
Linux jr-build 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
g++ src/RPCClient.cpp -o build/RPCClient.o -g -Wall -c -std=c++11 -Wextra -pedantic -I../lib-amqp-cpp/include

In file included from /usr/include/stdlib.h:42:0,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /usr/include/c++/5/tuple:39,
                 from /usr/include/c++/5/unordered_map:41,
                 from src/RPCClient.h:9,
                 from src/RPCClient.cpp:5:
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:79:27: error: redeclaration of ‘unsigned int wait::<anonymous struct>::__w_retcode’
  unsigned int __w_retcode:8;
                           ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:74:27: note: previous declaration ‘unsigned int wait::<anonymous struct>::__w_retcode’
  unsigned int __w_retcode:8; /* Return code if exited normally.  */
                           ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:80:28: error: redeclaration of ‘unsigned int wait::<anonymous struct>::__w_coredump’
  unsigned int __w_coredump:1;
                            ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:73:28: note: previous declaration ‘unsigned int wait::<anonymous struct>::__w_coredump’
  unsigned int __w_coredump:1; /* Set if dumped core.  */
                            ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:81:27: error: redeclaration of ‘unsigned int wait::<anonymous struct>::__w_termsig’
  unsigned int __w_termsig:7;
                           ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:72:27: note: previous declaration ‘unsigned int wait::<anonymous struct>::__w_termsig’
  unsigned int __w_termsig:7; /* Terminating signal.  */
                           ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:93:27: error: redeclaration of ‘unsigned int wait::<anonymous struct>::__w_stopsig’
  unsigned int __w_stopsig:8; /* Stopping signal.  */
                           ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:88:27: note: previous declaration ‘unsigned int wait::<anonymous struct>::__w_stopsig’
  unsigned int __w_stopsig:8; /* Stopping signal.  */
                           ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:94:27: error: redeclaration of ‘unsigned int wait::<anonymous struct>::__w_stopval’
  unsigned int __w_stopval:8; /* W_STOPPED if stopped.  */
                           ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:87:27: note: previous declaration ‘unsigned int wait::<anonymous struct>::__w_stopval’
  unsigned int __w_stopval:8; /* W_STOPPED if stopped.  */
```

**Comment by martijnotto** [comment]
This looks very strange. From what I can see, it looks as if the file /usr/include/x86_64-linux-gnu/bits/waitstatus.h contains multiple definitions of the same symbol itself.

I see unsigned int wait::<anonymous struct>::__w_retcode being defined on both line 79 and 74. This would obviously never work, so there's likely some preprocessor condition around those lines.

As I do not have access to an apple computer I can't see exactly what's here and why it would conflict with the stuff we do in endian.h. Could you post the waitstatus.h file here?

**Comment by j6mes** [comment]
Hi, the waitstatus.h is posted on this gist: https://gist.github.com/j6mes/d963dbc81efeeef884283467fb075d2a

I'm also very confused by this issue too. I've been using AMQP-CPP for a few months and not had any major issues like this before.

**Comment by j6mes** [comment]
Just been thinking that this may be because endian.h is defining, __BYTE_ORDER __BIG_ENDIAN, __LITTLE_ENDIAN under certain circumstances. which then causes the #if __BYTE_ORDER == __BIG_ENDIAN/__LITTLE_ENDIAN in waitstatus.h to return true at all times, causing the conflict

I do not have this issue if i don't have a -I for AMQP-CPP.

**Comment by martijnotto** [comment]
I only see endian.h declaring __LITTLE_ENDIAN and __BIG_ENDIAN for Windows systems. Maybe gcc mistakenly sets some define to true which causes us to think we're compiling under Windows?

Could you put in some #warning statements so we have a better idea which path is being taken and why?

**Comment by j6mes** [comment]
I think I've spotted it. I'm kicking myself. The issue is that your endian.h conflicts with an endian.h in my system libraries.

If I place #define AMQP_ENDIAN_H and #warning IN AMQP_ENDIAN_H in your endian.h file, I see that the file is getting called instead of the endian.h in my system's endian.h.  This means that byte orders are not being defined and hence in waitorder.h, i get the following output:

```
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:26:3: warning: #warning __BIG_ENDIAN is not defined [-Wcpp]
  #warning __BIG_ENDIAN is not defined
   ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:32:3: warning: #warning __LITTLE_ENDIAN is not defined [-Wcpp]
  #warning __LITTLE_ENDIAN is not defined
   ^
/usr/include/x86_64-linux-gnu/bits/waitstatus.h:38:10: warning: #warning __BYTE_ORDER is not defined [-Wcpp]
         #warning __BYTE_ORDER is not defined
```

This also means that line 139 of your endian.h is effectively trying to include itself: #include <endian.h> and effectively does nothing.

Deleting endian.h out of your include folder allows me to compile my RPC client.

I think common sense and best practice to avoid naming conflicts by placing library-specific includes in their own folder and therefore instead of ```#include <amqpcpp.h>``` i'd be doing ```#include <amqpcpp/amqpcpp.h>```

**Comment by martijnotto** [comment]
This is strange. So if you do an #include <endian.h> our endian.h is included? It looks like something has gone wrong during the 'make install'. All the files in the include directory should end up in something like /usr/include/amqcpp/. Did you copy files yourself or is this a bug in the Makefile?

**Comment by martijnotto** [comment]
I'm closing this issue as it is unlikely to be an error in the library. Either the endian.h was copied (by hand) to some system-directory and not to the correct subfolder or a the directory containing all the headers (e.g. /usr/include/amqpcpp) is erroneously used with -I causing the compiler to use our endian.h instead of the system default.

**Comment by llrocha** [comment]
The problem occurs because a other endian.h is created, and the headers defines is like this:
#ifndef _ENDIAN_H
#define _ENDIAN_H
...

#endif 

If you change this, to:

#ifndef _ENDIAN_H_dafc0ade-0642-4450-9c00-7c0411e3bd59
#define _ENDIAN_H_dafc0ade-0642-4450-9c00-7c0411e3bd59
...
#endif //_ENDIAN_H_dafc0ade-0642-4450-9c00-7c0411e3bd59

Your code compile well.
