### ISSUE TITLE
Issue Compiling using LibEvHandler specifically Watcher

### ISSUE THREAD

**Issue by wnyffenegger** [CopernicaMarketingSoftware/AMQP-CPP#105]
I am trying to compile an example using AMQP::LibEvHandler; but, I am running into trouble.

Compiling: pthread, C++ 11, g++ 5.4.0

Specifically I am trying to initialize it by:
AQMP::LibEvHandler handler = AMQP::LibEvHandler(&loop);

I have attached the error report.
[error.txt](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/files/527913/error.txt)

**Comment by EmielBruijntjes** [comment]
This is a beginners C++ question, not at all related to AMQP-CPP.
