### ISSUE TITLE
Channel::onError does not report when rabbitmq server is down

### ISSUE THREAD

**Issue by TianBo-Timothy** [CopernicaMarketingSoftware/AMQP-CPP#107]
When the channel is created, a callback is registered by onError() call. The code looks like this:

```cpp
TcpConnection connection(&evHandler, amqpAddress);
TcpChannel channel(&connection);
channel.onError([](const char * errMsg) {
        std::cout << "AMQP: " << errMsg << std::endl;
    });
```

I expected that there will be something printed out when I shut down rabbitmq server (with `sudo service rabbitmq-server stop`). But actually, it does not. 

However, if I check the channel before publishing, the channel shows it is not connected. The code is like:

```cpp
if (!channel.connected()) {
    std::cout << "AMQP channel is not connected!\n";  // this line is printed out
}
```

My question is: 
1. is broken connection supposed to be reported via Channel::onError()?
2. if I cannot get disconnection report from Channel::onError, should I check the connection before every publishing? Or is there a more preferred way to handle such a situation?

Thanks.

**Comment by EmielBruijntjes** [comment]
If something goes wrong with the entire connection, the `onError()` method inside the TcpHandler class is called. Best way is to create your own class that extends from TcpHandler or LibEvHandler, and implement this `onError()` method.
