### ISSUE TITLE
libev publishing subscribing issue

### ISSUE THREAD

**Issue by wnyffenegger** [CopernicaMarketingSoftware/AMQP-CPP#108]
I have a simple multi-threaded application that is giving me trouble. In that application, I have one thread open a connection to RabbitMQ and consume messages from an exchange-key pair. The other thread also opens a connection to RabbitMQ and begins publishing to that same exchange-key pair.

At some point the two threads enter a race condition where the publishing thread takes over and the subscriber no longer receives messages.

I am using two different event loops initialized using ev_loop_new(), which, according to the man pages, is thread safe. When I run the publisher and subscriber in two different processes I have no issues; but, as far as I can tell, the connections for both threads are separate as are the ev_loop's.

My question is why I am I encountering this race condition?

**Comment by EmielBruijntjes** [comment]
I don't know. The connections and channels do not use global variables or so, so it is safe to create multiple instances in different threads. We do the same all the time.

Could you publish the smallest thinkable program (thus: really small) in which this error occurs?

**Comment by wnyffenegger** [comment]
```C++
#include <amqpcpp.h>
#include <amqpcpp/libev.h>
#include "thread"
#include "chrono"



struct ev_loop* loop1 = ev_loop_new();
struct ev_loop* loop2 = ev_loop_new();

void computations(AMQP::TcpChannel* chan) {
    chan->declareExchange("exchange", AMQP::topic);

    int _iterations = 0;
    while(_iterations < 2000) {
        chan->startTransaction();
        std::cout << _iterations << std::endl;
        chan->publish("exchange", "key", "message");
        chan->commitTransaction();

        std::this_thread::sleep_for(std::chrono::milliseconds(1));
        _iterations++;
    }
}

void publisher() {
    std::string host = "amqp://localhost/";
    AMQP::LibEvHandler* handler = new AMQP::LibEvHandler(loop1);
    AMQP::TcpConnection* conn = new AMQP::TcpConnection(handler, AMQP::Address(host));
    AMQP::TcpChannel* chan = new AMQP::TcpChannel(conn);

    std::thread comp(computations, chan);

    ev_run(loop1);
}

void subscriber() {
    std::string host = "amqp://localhost/";
    AMQP::LibEvHandler* handler = new AMQP::LibEvHandler(loop2);
    AMQP::TcpConnection* conn = new AMQP::TcpConnection(handler, AMQP::Address(host));
    AMQP::TcpChannel* chan = new AMQP::TcpChannel(conn);

    auto startCb = [](const std::string&consumertag) {
        std::cout << "Consumer operation started" << std::endl;
    };

    auto errorCb = [](const char *message) {
        std::cout << message << std::endl;
        std::cout << "Consume operation failed" << std::endl;
    };

    auto messageCb = [chan](const AMQP::Message &message, uint64_t deliveryTag, bool redelivered) {
        std::cout << "Message Delivered" << std::endl;
        chan->ack(deliveryTag);
    };

    chan->declareQueue("queue");
    chan->declareExchange("exchange", AMQP::topic);
    chan->bindQueue("exchange", "queue", "key");

    chan->consume("queue")
            .onReceived(messageCb)
            .onSuccess(startCb)
            .onError(errorCb);

    ev_run(loop2);
}

int main() {
    std::thread sub(subscriber);
    std::thread pub(publisher);

    pub.join();
    sub.join();
}
```

**Comment by EmielBruijntjes** [comment]
You start three threads in total: the publisher-thread and the computations-thread both access the same AMQP objects, which is wrong.

**Comment by wnyffenegger** [comment]
What would you suggest then? Extend TcpHandler for publishing? Also, why would using the object in multiple threads be wrong? There are no overtly concurrent uses of the channel.

**Comment by wnyffenegger** [comment]
In fact, the appropriate question is: how would you create a Handler or a Connection and use it without an event loop?

**Comment by EmielBruijntjes** [comment]
You run the event loop in one thread (`ev_run` inside the publisher thread), which processes all sorts of events on the AMQP Connection and Channel, and updates the internal state of these objects.

At the same time, from a completely different thread (the compulations thread) you start calling methods on the same channel object. These methods also access and update these internal state variables. This is illegal, because a channel object is not thread safe. You cannot use it from multiple threads at the same time.

You asked "how would you create a Handler or a Connection and use it without an event loop?". The answer: you can't. You always need an event loop that you associate with a connection, so that you can process incoming events on the AMQP channel (like heartbeats, or the answers from sent instructions). This event loop allows you to monitor the AMQP connection for activity.

If you want to run a long-running computation inside a different thread, you must, from that other thread, first interrupt the main event loop (using a libev synchronize watcher), and only when you're 100% sure that the event loop came to a halt, you can access the channel object from that different thread.

**Comment by dichen16** [comment]
Hi everyone,

**Comment by dichen16** [comment]
Hi everyone, 
I have two handler, one for receive,  another for publish, each handler will create a thread to execute event loop. these two handler owns two completely different connections and channels.
I init the receiver  successfully first, when i try to init the publisher,  my program carshed
` ev.c:3247: ev_run: Assertion ("libev: ev_loop recursion during release detected", ((loop)->loop_done) != 0x80) failed.`

I read Emiel's comments above, does that means i must merge the receiver and publisher to one handler, and create two different connections for receiver and publisher, and use one event loop for process the requests?

**Comment by EmielBruijntjes** [comment]
You can do whatever you want. But the objects from the AMQP-CPP library are not thread-safe, so you can only access them from one thread at a time.

**Comment by dichen16** [comment]
thank you Emiel for your quick reply
It's a cool project, I learn a lot from its coding style

**Comment by dichen16** [comment]
Sorry to bother you again, 
I am stuck in the error `ev.c:3247: ev_run: Assertion ("libev: ev_loop recursion during release detected", ((loop)->loop_done) != 0x80) failed.`😞
I use libev for my backend,
could you show me some example about using two event loops in two different threads?

**Comment by dichen16** [comment]
Sorry and ok, 
I use two threads, one for receive, another for publish.
```
int main(int argc, char* argv[])
{
    auto *loop1 = EV_DEFAULT;
    std::unique_ptr<Receiver> handler1 = std::unique_ptr<Receiver>(new Receiver(loop1));
    handler1->receive();

    auto *loop2 = EV_DEFAULT;
    std::unique_ptr<Publisher> handler2 = std::unique_ptr<Publisher>(new Publisher(loop2));
    while (true)
    {
        std::chrono::milliseconds dura(5000);
        std::this_thread::sleep_for(dura);
        handler2->publish();
    }
    return 0;
}
```
The issue is that it will crash while calling the second ev_run() in the second thread, and each thread possess its own AMQP-CPP objects.
```
bool Publisher::Connnect2Rabbitmq()
{
    m_pTcpConnection = std::unique_ptr<AMQP::TcpConnection>(
        new AMQP::TcpConnection(this, AMQP::Address("amqp://hzhs:hzhs@192.168.0.140:5672")));
    m_pTcpChannel = std::unique_ptr<AMQP::TcpChannel>(new AMQP::TcpChannel(m_pTcpConnection.get()));
    std::cout << "before the publish thread detached" << std::endl;
    m_thread = std::thread{ ev_run, m_loop, 0 };
    std::cout << "publish thread detached" << std::endl;
    return true;
}
```

![image](https://user-images.githubusercontent.com/36980985/50890114-87c1f100-1434-11e9-80c1-ec69031249b1.png)

**Comment by EmielBruijntjes** [comment]
You know that loop1 is exactly the same as loop2, don't you?

**Comment by dichen16** [comment]
Sorry and ok,
```
int main(int argc, char* argv[])
{
    auto *loop1 = EV_DEFAULT;
    std::unique_ptr<Receiver> handler1 = std::unique_ptr<Receiver>(new Receiver(loop1));
    handler1->receive();

    auto *loop2 = EV_DEFAULT;
    std::unique_ptr<Publisher> handler2 = std::unique_ptr<Publisher>(new Publisher(loop2));
    while (true)
    {
        std::chrono::milliseconds dura(5000);
        std::this_thread::sleep_for(dura);
        handler2->publish();
    }
    return 0;
}
```
The issue is that it will crash while calling the second ev_run() in the second thread, and each thread possess its own AMQP-CPP objects.
```
bool Publisher::Connnect2Rabbitmq()
{
    m_pTcpConnection = std::unique_ptr<AMQP::TcpConnection>(
        new AMQP::TcpConnection(this, AMQP::Address("amqp://hzhs:hzhs@192.168.0.140:5672")));
    m_pTcpChannel = std::unique_ptr<AMQP::TcpChannel>(new AMQP::TcpChannel(m_pTcpConnection.get()));
    std::cout << "before the publish thread detached" << std::endl;
    m_thread = std::thread{ ev_run, m_loop, 0 };
    m_thread.detach();
    std::cout << "publish thread detached" << std::endl;
    return true;
}
```
> You know that loop1 is exactly the same as loop2, don't you?
I don't, I just start to learn libev,  I am not familiar with the game rule of libev

**Comment by dichen16** [comment]
Thanks to your advice
```
int main(int argc, char* argv[])
{
    auto *loop1 = ev_loop_new(0);
    std::unique_ptr<Receiver> handler1 = std::unique_ptr<Receiver>(new Receiver(loop1));
    handler1->receive();

    auto *loop2 = ev_loop_new(0);
    std::unique_ptr<Publisher> handler2 = std::unique_ptr<Publisher>(new Publisher(loop2));
    while (true)
    {
        std::chrono::milliseconds dura(5000);
        std::this_thread::sleep_for(dura);
        handler2->publish();
    }
    return 0;
}
```
my code seems run correctly
