### ISSUE TITLE
Is AMQP-CPP thread safe?

### ISSUE THREAD

**Issue by sheetalrkadam** [CopernicaMarketingSoftware/AMQP-CPP#110]
Hi,

I am interested in using the amq -cpp in multithreaded environment, is it thread safe.?
can we scale the consumer tasks? 
Does AMQP-CPP uses boost library? or any other library.
Also, it would be really useful if you could share some examples  for better understanding of the usage of 
MyTcpHandler/AMQP::LibEvHandler/AMQP::ConnectionHandler.

Thanks,
Sheetal

**Comment by martijnotto** [comment]
I don't understand most of the question, but I'll try to answer as much as I can.

The AMQP-CPP library is not thread safe. You cannot use the same connection (and any of the channels associated with it) from multiple threads at the same time. If you insist on using multiple threads you could either use multiple Connection instances (each bound to their own event loop) or implement a system where a single thread takes care of the communication and then disperses the messages to the other threads. You can move connections between threads but you need to first stop the event loop there and then register the connection to the event loop in the other thread.

I don't understand what you mean by "scaling the consumer tasks". You just get the number of messages that you set as QOS when you start consuming and then every time you ack() a message a new one will be provided.

**Comment by sheetalrkadam** [comment]
Thanks for immediate response. :)
we did not understand the following statement, could you please elaborate or provide an example of the same.
"You can move connections between threads but you need to first stop the event loop there and then register the connection to the event loop in the other thread."

Sorry, it would have been better if I had explained you the our requirement. Would try to give some details about the same as an example.
Example:
ConsumerTask1: binding to RMQ and receiving msgs, posting the msgs to WorkerTasks for further processing.
ConsumerTask2: binding to RMQ and receiving msgs, posting the msgs to WorkerTasks for further processing.
WorkerTask(1..n): Processing the received msg and sending Acks.

Couple of queries:
1) Can we send Acks from multiple worker threads other than consumer tasks.
2) Could you please elaborate on the following:
"You just get the number of messages that you set as QOS when you start consuming and then every time you ack() a message a new one will be provided."
Does it mean next msg is being delivered only after 1 msg is acked.
Or 
if QOS=10, all 10 msgs should be acked only then next batch of msgs is received.
Note:
Queue: exchange_type="direct", durable=True, auto_delete=False.


Thanks,
Sheetal

**Comment by martijnotto** [comment]
It means you can only use the Connection from the same thread as the event loop. If you wish to use the library from another thread you first have to make sure the event loop no longer tries to read and write from the socket and then have the event loop in the other thread manage the socket.

I still don't understand what you mean by "scaling the messages". In your example I also don't understand the point of the ConsumerTaskx. What are they doing? Is this a difficult algorithm? Why can't the WorkerTask not directly read the messages?

1. You can only ack from the same thread as the event loop that is running the Connection instance
2. Next message is delivered as soon as you ack (provided the queue isn't empty of course).

**Comment by martijnotto** [comment]
The easiest way would be to eliminate the ConsumerTaskx and just give each WorkerTask it's own connection. This only works if you aren't doing long blocking algorithm-stuff. In that case you could easily do with a single ConsumerTask. This task consume()s from the queue with the QOS set to the number of worker threads.

You then put the messages in an std::deque or similar construct and let the workers read from this queue and then add some signaling back to the ConsumerTask to indicate when tasks are done so the ConsumerTask can ack() the messages.

**Comment by martijnotto** [comment]
It doesn't matter in which order you ack BTW. As soon as you ack a message, the number of unacked messages goes down. As long the number of unacked messages is below the QOS and more messages are available you will get messages from RabbitMQ.
