### ISSUE TITLE
Fail compilation, when compiler doesn't support C++11

### ISSUE THREAD

**Issue by GeorgeKT** [CopernicaMarketingSoftware/AMQP-CPP#111]
The usage of set_cxx_norm.cmake, seems to suggest that this project compiles with gcc 4.6 (with -std=c++0x). However it heavily uses features which are not supported by gcc 4.6, so it can't compile with it.

**Comment by Kojoley** [comment]
From [README.md](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/master/README.md)
> The AMQP-CPP library uses C++11 features, so if you intend use it, please make sure that your compiler is up-to-date and supports C++11.

**Comment by GeorgeKT** [comment]
The point is, if C++11 is the minimum required, detect if it is supported, and if not fail during the cmake run. 

There is no point to see if you need to add -std=c++98, -std=c++03 or -std=c++0x as compiler flags in set_cxx_norm.cmake, if your minimum required version is C++11.

**Comment by Kojoley** [comment]
I understand you but I am not a developer of the library.
`set_cxx_norm.cmake` is a third party script though I had suggested to remove it a while ago https://github.com/CopernicaMarketingSoftware/AMQP-CPP/pull/45#issuecomment-152821428.

**Comment by EmielBruijntjes** [comment]
The CMakefile was not created by my (the AMQP-CPP maintainer), but came from a pull request that I accepted. I dont use it myself. But the things that you're saying make sense. If you send in a pull request I am willing to accept it.
