### ISSUE TITLE
arguments["x-message-ttl"] 

### ISSUE THREAD

**Issue by wulinwulin76** [CopernicaMarketingSoftware/AMQP-CPP#112]
This code runs successfully: 
```
int aa=300000;  
arguments["x-message-ttl"] = aa;   
channel->declareQueue(AMQP::durable,arguments)  
                .onSuccess(callbackQueueDeclared)  
                .onError([](const char *message) {  
            qDebug() << "queue declare error in MQTopicConsume: " << message;  
        });  
```

However, it the type of aa is changed to uint, the code compiles without error or warning, but when run, l get the error: "connection reset by peer"  
```
uint aa=300000;  
arguments["x-message-ttl"] = aa;  
channel->declareQueue(AMQP::durable,arguments)  
                .onSuccess(callbackQueueDeclared)  
                .onError([](const char *message) {  
            qDebug() << "queue declare error in MQTopicConsume: " << message;  
        });  
```

**Comment by EmielBruijntjes** [comment]
And it would not surprise me if your whole RabbitMQ server crashes as well! I've experienced the same thing: the RabbitMQ server does not handle all the types that are documented in the AMQP standard, and sometimes even crashes if you send an unsupported type. This is not really an AMQP-CPP issue, but a RabbitMQ issue.
