### ISSUE TITLE
frame out of range

### ISSUE THREAD

**Issue by Sk8rMarc** [CopernicaMarketingSoftware/AMQP-CPP#114]
I'm receiving the connection error, 'frame out of range' (framecheck.h:44) when trying to consume a message on a queue having:

- Properties:
    - reply_to: 'myReplyQueue'
    - correlation_id: '1484874177335'
    - headers:
        - restrictToSIDs: list of '1000', '2000', '3000', '4000', '5000, '6000', '7000'
        - restrictToAge: 147
- Payload:
    'testing list in header'

The message was created with a nodejs amqplib client.
``` node
      channel.publish( '', 'testq', new Buffer( 'testing list in header' ), 
         { 
            replyTo: 'myReplyQueue',
            correlationId: new Date().getTime().toString(),
            headers: 
               {
                  'restrictToSIDs' : [ '1000', '2000', '3000', '4000', '5000', '6000', '7000' ],
                  'restrictToAge' : 147 
               }
         } );
```
And the RabbitMQ Management Console can 'Get Messages' and requeue:

![rabbitmqmanagementconsoleclipping](https://cloud.githubusercontent.com/assets/24689855/22131705/123d1178-de83-11e6-87e1-b74c2dc50ad7.png)

**Comment by Sk8rMarc** [comment]
Some further testing...  the headers field-table is seen,  so is the field-name of the first field-value-pair ("restrictToSIDs"), and the field-value of the first field-value-pair is an Array, but what starts to mess up is that the array's _charsToRead_ is **21** !! This doesn't make sense to me.  Wouldn't the array's _charsToRead_ be 7 x 5 {4 chars + byte length} == **35** ??

**Comment by EmielBruijntjes** [comment]
Let met first check this: people often report these kind of errors because they start multiple threads that all try to send and receive data over the same connection. Do you have threads?

**Comment by Sk8rMarc** [comment]
I'm using ASIO standalone, no boost, and using one thread to drive the service, and even have all async tasks on their own strand, just in case someone (me at the moment) decided to pool more threads to run the service given to the connection.  So everything AMQP-CPP is serialized.

I tried using AMQP-CPP's libev example, I had to wrap AMQP::TcpConnection to get at onError, but sure enough, I get the same Connection Error when attempting to consume such a message.  So I doubt it's a bug in my ASIO async socket implementation.  The AMQP-CPP library is working like a charm when reading messages sans headers.

I had sent you an early version of my AMQP::ASIO::Connection and AMQP::ASIO::Channel.  I've since then made some changes.  Adding the strand to keep all AMQP async activities serialized, and more recently, am now utilizing the resolve/connect timer for heartbeats.  The timer is re-primed whenever we receive a heartbeat frame, because AMQP-CPP already sends a heartbeat reply, and whenever an async write sequence is started.

**Comment by Sk8rMarc** [comment]
Here's my current ASIO implementation of Connection and Channel.  For this simply test to attempt to consume a message with headers with a list/array -- normally, my application would stay connected to the broker, this was just a quick attempt to consume such a message.  I was hopping to get 'Received Query Message', then write the code to fully consume the headers.

[amqpasio.zip](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/files/719305/amqpasio.zip)

```c++
   asio::io_service queryIo;
   asio::io_service::work work( queryIo );
   AMQP::ASIO::Connection::Ptr qConn = AMQP::ASIO::Connection::make( queryIo );

   qConn->onError( [qConn, &queryIo]( std::string const& message ) 
   {
      std::cerr << "Connection Error: " << message << std::endl;
      qConn->close();
      queryIo.stop();
   } ).onConnected( [qConn, &queryIo]( AMQP::ASIO::Connection::Ptr conn )
   {
      std::cerr << "Connected" << std::endl;

      AMQP::ASIO::Channel::Ptr qCh = AMQP::ASIO::Channel::make( conn );
      qCh->consume( "testq", AMQP::noack ).onMessage( [qConn, qCh, &queryIo]( AMQP::Message && message, uint64_t deliveryTag, bool redelivered ) mutable
      {
         std::cerr << "Received Query Message" << std::endl;
         qCh->close();
         qCh = nullptr;
         qConn->close();
         queryIo.stop();

      } ).onError( [qConn, qCh, &queryIo]( char const* message ) mutable
      {
         std::cerr << "Channel Error: " << message << std::endl;
         qCh->close();
         qCh = nullptr;
         qConn->close();
         queryIo.stop();
      } );
   } );


   qConn->connect( "amqp://localhost" );
   queryIo.run();
   qConn = nullptr;
```

**Comment by Sk8rMarc** [comment]
I captured the frame being parsed... something's quite weird.  The BNF says field-array is a 32-bit signed size followed by *field-value.   Looking at the memory dump, we see the first headers entry: restrictToSIDs followed by the Array field type @ 0x0177a9c4

`0x0177a9c5 - 0x0177a9c8: 00 00 00 15` ==> 0x00000015 == 21 -- chars to read for the array

But now the 21 is correct, but the field-values do not make sense!!! The field type, is 73 or 's' for ShortString, but the byte length is missing and it is not a string, but a big endian 16-bit value!!!

`0x0177a9c9 - 0x0177a9cb: 73 03 e8` ==> 's' 0x03e8 == 1000
`0x0177a9cc - 0x0177a9ce: 73 07 d0` ==> 's' 0x07d0 == 2000
`0x0177a9cf - 0x0177a9d1: 73 0b b8` ==> 's' 0x0bb8 == 3000
`0x0177a9d2 - 0x0177a9d4: 73 0f a0` ==> 's' 0x0fa0 == 4000
`0x0177a9d5 - 0x0177a9d7: 73 13 88` ==> 's' 0x1388 == 5000
`0x0117a9d8 - 0x0177a9da: 73 17 70` ==> 's' 0x1770 == 6000
`0x0117a9db - 0x0177a9dd: 73 1b 58` ==> 's' 0x1b58 == 7000

```
   13  	Table::Table(ReceivedFrame &frame)
   14  	{
   15  	    // table buffer begins with the number of bytes to read
-> 16  	    uint32_t bytesToRead = frame.nextUint32();
   17  	
   18  	    // keep going until the correct number of bytes is read.
   19  	    while (bytesToRead > 0)
(lldb) p *(AMQP::ByteBuffer*) &(*(AMQP::ReducedBuffer*)&frame._buffer)._buffer
(AMQP::ByteBuffer) $1 = (_data = "\x01", _size = 201)
(lldb) p (*(AMQP::ByteBuffer*) &(*(AMQP::ReducedBuffer*)&frame._buffer)._buffer)._data
(const char *) $2 = 0x000000000177a960 "\x01"
(lldb) memory read --outfile mem.txt 0x000000000177a960 0x000000000177a960+201
(lldb) memory read  0x000000000177a960 0x000000000177a960+201
0x0177a960: 01 00 01 00 00 00 34 00 3c 00 3c 1f 61 6d 71 2e  ......4.<.<.amq.
0x0177a970: 63 74 61 67 2d 63 55 53 41 6a 61 78 59 41 38 77  ctag-cUSAjaxYA8w
0x0177a980: 75 62 4b 4f 71 72 61 70 72 61 51 00 00 00 00 00  ubKOqrapraQ.....
0x0177a990: 00 00 01 00 00 05 74 65 73 74 71 ce 02 00 01 00  ......testq.....
0x0177a9a0: 00 00 67 00 3c 00 00 00 00 00 00 00 00 00 16 26  ..g.<..........&
0x0177a9b0: 00 00 00 00 3a 0e 72 65 73 74 72 69 63 74 54 6f  ....:.restrictTo
0x0177a9c0: 53 49 44 73 41 00 00 00 15 73 03 e8 73 07 d0 73  SIDsA....s..s..s
0x0177a9d0: 0b b8 73 0f a0 73 13 88 73 17 70 73 1b 58 0d 72  ..s..s..s.ps.X.r
0x0177a9e0: 65 73 74 72 69 63 74 54 6f 41 67 65 73 00 93 0d  estrictToAges...
0x0177a9f0: 31 34 38 34 39 33 36 39 30 37 31 31 39 0c 6d 79  1484936907119.my
0x0177aa00: 52 65 70 6c 79 51 75 65 75 65 ce 03 00 01 00 00  ReplyQueue......
0x0177aa10: 00 16 74 65 73 74 69 6e 67 20 6c 69 73 74 20 69  ..testing list i
0x0177aa20: 6e 20 68 65 61 64 65 72 ce                       n header.
```

**Comment by Sk8rMarc** [comment]
And the next headers entry's name is restrictToAge, and its numeric value of 147 (0x93) is entered as `73 00 93` or 's' 0x0093 = 147.  This isn't documented in the BNF, for sure!

**Comment by Sk8rMarc** [comment]
https://www.rabbitmq.com/amqp-0-9-1-errata.html

> Remarks:
> 
>  A1, A2: Notice how the types CONFLICT here. In Qpid and Rabbit,
>          's' means a signed 16-bit integer; in 0-9-1, it means a
>          short string.

**Comment by Sk8rMarc** [comment]
Okay, here's the deal.  The sample code I originally provided has the SIDs as strings in quotes.  If I run that, I get LongStrings and that would work.  However, the 147 number was using 's' 16-bits which was causing the frame out of range.  If I also put quotes around the 147 too, the frame **IS** parsed correctly.

The issue is with 16-bit quantities in an Array.  Apparently, in amqp-0.9.1, within field-array's 's' does not mean ShortString, but Signed 16-bits.

My work around will be to use quotes around my entities within the headers.  You may close this item, or come up with a Fix... that is 's' within 'A' is a signed 16-bit quantity.

**Comment by EmielBruijntjes** [comment]
Is this a documented feature of AMQP 0.9.1, or is it a RabbitMQ mistake?

**Comment by Sk8rMarc** [comment]
The errata starts off with

> Here we list errors and ambiguities in the 0-9-1 specification and provide our interpretations and corrections.

**Comment by Sk8rMarc** [comment]
btw, I ended up moving the strand outside my asio connection object as I'm working with shared_ptr of AMQP::ASIO::Connection and Channel.  And when there are issues with on Connection causing the creation of another, I didn't necessarily have ability to keep things serialized during that chaos.  So my Connection now constructs with an asio::io_strand::strand reference now.

**Comment by Kawabaumga** [comment]
> Let met first check this: people often report these kind of errors because they start multiple threads that all try to send and receive data over the same connection. Do you have threads?

What is the best practice? One connection for incoming messages and one for outgoing or one connection is enough if we use one channel for incoming messages and one for outgoing messages?

**Comment by EmielBruijntjes** [comment]
This very much depends on your own application. But from an AMQP-CPP standpoint one connection should be sufficient. You can use many channels at the same time, but you can also use a single channel for all operations. For the AMQP-CPP library a single channel is more efficient, but then again, setting up channels is also not that expensive, so I don't mind paying that extra price and I create channels all the time. A single channel is more error-prone: if an operation fails, the entire channel becomes invalid, so better spread unrelated operations over multiple channels, so that an error for one operation does not affect other things that are going on.

I do not exactly know how RabbitMQ works, but internally it seems to do a lot of threading. I'm not sure how stressful it is for Rabbit if you use more channels or more connetions, but I assume that for rabbit it is also more efficient to use less connections and channels.

**Comment by Kawabaumga** [comment]
I tried a first implementation (using your TCP class) with only one connection and one channel to receive and publish some json messages but I faced "frame error" when the process exchange many messages

**Comment by EmielBruijntjes** [comment]
Did you use threads?

**Comment by Kawabaumga** [comment]
Yes. One for reading messages and N threads to process the message/tasks
and publish the result

Le mar. 12 mai 2020 à 11:01, Emiel Bruijntjes <notifications@github.com> a
écrit :

**Comment by EmielBruijntjes** [comment]
Stop doing that.

**Comment by sblocatible** [comment]
I know this is a very old topic.. But I lost a lot of time on this when I finally realized I was sending headers as Integer from NodeJS to the RabbitMQ and consuming with the AMQP-CPP lib. 

This is the snipped from NodeJS (please note the hack which fixed my problem, line 16):

```
const response = /* my payload here */
const opt = {};
opt.headers = {};
opt.timestamp = options.timestamp || Date.now();
opt.correlationId = options.correlationId || uuid.v4();
opt.replyTo = options.replyTo || null;
const response = makeResponse(payload, options);
const buf = Buffer.from(JSON.stringify(response));
Object.assign(opt.headers, {
    'Content-Type': 'application/json',
    'Content-Length': buf.length, /* this is integer */
},
options.headers || {});

// Hack to fix error in c++ code. All the headers must be string;
Object.keys(opt.headers).forEach((key) => opt.headers[key] = opt.headers[key].toString());

return channel.publish(exchange, routingKey, buf, opt);
```

And of course, the threading is also an issue, but in this case the headers caused this too.
