### ISSUE TITLE
Semicolon is missing in sample program.

### ISSUE THREAD

**Issue by muzudho** [CopernicaMarketingSoftware/AMQP-CPP#119]
Hi!

I found missing semicolon in readme.MD.

FLAGS AND TABLES

auto callback = [](const std::string &name, int msgcount, int consumercount) {

    // @todo add your own implementation

}
 ~
 Here!

CONSUMING MESSAGES

auto errorCb = [](const char *message) {

    std::cout << "consume operation failed" << std::endl;
}
 ~
 Here!

auto messageCb = [&channel](const AMQP::Message &message, uint64_t deliveryTag, bool redelivered) {

    std::cout << "message received" << std::endl;

    // acknowledge the message
    channel.ack(deliveryTag);
}
 ~
 Here!

Thankyou:-)

**Comment by EmielBruijntjes** [comment]
thanks for mentioning, it has been fixed
