### ISSUE TITLE
Message::body() and Message::message() return different values which one should be used?

### ISSUE THREAD

**Issue by barabenka** [CopernicaMarketingSoftware/AMQP-CPP#121]
Message::body() and Message::message() return different values. This is reproduced by code below:

```
#include "amqpcpp.h"
#include <string>

using namespace AMQP;
using namespace std;

class TestMessage: public Message
{
    public:
        TestMessage(const string &exchange, const string &routingKey, const string & msg): 
            Message(exchange, routingKey)
        {
            append(msg.c_str(), static_cast<uint64_t>(msg.length()));
        };
};

int main(int argc, char* argv[])
{
	
	string message_str("coding is fun");
	TestMessage msg("exchange", "routing_key", message_str);
	cout<<"msg.message()="<<msg.message()<<endl;
	cout<<"msg.body()="<<msg.body()<<endl;

	return 0;
}
```
The output is:
_msg.message()=
msg.body()=coding is fun_

Which function should be used to retrieve received message in MessageCallback? Some of you examples show using message() but it is empty in the test above while body() has correct string.

**Comment by EmielBruijntjes** [comment]
You are not supposed to instantiate Message objects yourself. The library does that for you every time it receives a message, and passes that message to the onReceived() handler that you can install for a consume() call.

We've recently refactored the Message class and removed the message() method.
