### ISSUE TITLE
Adaptive buffer size for _amqpBuffer

### ISSUE THREAD

**Issue by varun1312** [CopernicaMarketingSoftware/AMQP-CPP#124]
I am trying to send and receive messages of large sizes(More than 4 KB). Initially, I was facing problems with the consumer(it was not dequeuing the messages). After going through one of the issues, I understood that the problem is with respect to the _amqpBuffer size. When I increase it, It worked!!!

Is there any way in which we can have this buffer size adaptive so that the consumer can consume messages without any problem even if the message size goes beyond the buffer size.

**Comment by EmielBruijntjes** [comment]
There is no _amqpBuffer variable in the source code, what are you referring to?

**Comment by varun1312** [comment]
I was referring to the _amqpBuffer in AsioHandler class. To be interoperable between Windows and Linux, we are using boost ASIO like it is mentioned in the examples.

**Comment by EmielBruijntjes** [comment]
The AsioHandler is not a part of this AMQP-CPP library.
