### ISSUE TITLE
Can I reconnect after tcp failure?

### ISSUE THREAD

**Issue by kyudin** [CopernicaMarketingSoftware/AMQP-CPP#125]
Greetings.

I'm using boost::asio for tcp work with amqp. After tcp failure, when socket is closed (broken pipe, bad file descriptor etc) can I recover without application restart?

Considering that we close socket, I cannot close channel and cannot close connection. When I try to just restore tcp connection without closing channel/amqp connection I receive some frame, on which I receive exception: frame size exceeded. Looks like there is no uint32, when it's expected.

tcpdump output on normal connect:
```
Flags [P.], seq 3753889094:3753889102, ack 750495965, win 229, options [nop,nop,TS val 626410109 ecr 365668103], length 8
	0x0000:  4500 003c 8f3a 4000 4006 2820 0a01 0aa4  E..<.:@.@.(.....
	0x0010:  0a01 64bc b70c 1628 dfbf cd46 2cbb a8dd  ..d....(...F,...
	0x0020:  8018 00e5 e24d 0000 0101 080a 2556 427d  .....M......%VB}
	0x0030:  15cb a707 414d 5150 0000 0901            ....AMQP....
Flags [.], ack 3753889102, win 219, options [nop,nop,TS val 365668104 ecr 626410109], length 0
	0x0000:  4500 0034 0fd5 4000 3d06 aa8d 0a01 64bc  E..4..@.=.....d.
	0x0010:  0a01 0aa4 1628 b70c 2cbb a8dd dfbf cd4e  .....(..,......N
	0x0020:  8010 00db 7dfd 0000 0101 080a 15cb a708  ....}...........
	0x0030:  2556 427d                                %VB}
Flags [P.], seq 750495965:750496453, ack 3753889102, win 219, options [nop,nop,TS val 365668106 ecr 626410109], length 488
```

tcpdump output on reconnect attempt:
```
Flags [P.], seq 63835659:63835686, ack 3713499861, win 229, options [nop,nop,TS val 626454689 ecr 365846422], length 27
	0x0000:  4500 004f fd62 4000 4006 b9e4 0a01 0aa4  E..O.b@.@.......
	0x0010:  0a01 64bc b75d 1628 03ce 0e0b dd57 82d5  ..d..].(.....W..
	0x0020:  8018 00e5 71ce 0000 0101 080a 2556 f0a1  ....q.......%V..
	0x0030:  15ce 5f96 0100 0100 0000 0b00 1400 2800  .._...........(.
	0x0040:  0000 0000 0000 ce41 4d51 5000 0009 01    .......AMQP....
Flags [P.], seq 3713499861:3713499869, ack 63835659, win 219, options [nop,nop,TS val 365846422 ecr 626454689], length 8
	0x0000:  4500 003c dd41 4000 3d06 dd18 0a01 64bc  E..<.A@.=.....d.
	0x0010:  0a01 0aa4 1628 b75d dd57 82d5 03ce 0e0b  .....(.].W......
	0x0020:  8018 00db 8be9 0000 0101 080a 15ce 5f96  .............._.
	0x0030:  2556 f0a1 414d 5150 0000 0901            %V..AMQP....
```

Can I somehow reconnect, or I cannot recover if I have no tcp connection established?

I realized that actually I can use following sequence: if tcp connection is closed then open new, after that try to close amqp connection, close tcp connection, open new tcp connection, open amqp connection. And that works. However, is there some better way?

**Comment by EmielBruijntjes** [comment]
You cannot create a new TCP connection and use it with an existing AMQP connection. If the TCP connection is gone, your AMQP connection and channel objects become worthless too. The only thing you can do is either exit the application, or create a brand new TCP connection, a new AMQP connection and new AMQP channel objects.

**Comment by kyudin** [comment]
EmielBruijntjes, thanks for answer. I know that. But I cannot create new AMQP connection with new TCP connection as I stated in question (some strange frame is sended by rabbit).

**Comment by EmielBruijntjes** [comment]
Can you show the smallest possible example (keep it small!) that demonstrates this? And do not use boost asio, because he asio code code is not part of AMQP-CPP - and the asio example have already been removed from the repository.

**Comment by kyudin** [comment]
I will try to do small example. Btw, I use boost asio, cause it's more natural for our project and handler is highly rewritten for fit in our requirements (few ips, reconnects, threads, waiting for end of operation, etc). Looks like I cannot reconnect at all using libev example, cause I can call ev_run only once in application.

**Comment by kyudin** [comment]
EmielBruijntjes, seems like that is almost impossible. Connection and channel just not created correctly on reconnect attempt (using tcpconnection and tcpchannel). I will try more, however, you will not accept example of this case with boost asio?

**Comment by EmielBruijntjes** [comment]
I need a very simple and small example that clearly demonstrates when it goes wrong. If you can only get to the error with a long and complex example, the problem is probably somewhere in your complex code, and not inside the AMQP-CPP library.
