### ISSUE TITLE
Add support for boost async loop

### ISSUE THREAD

**Issue by progovoy** [CopernicaMarketingSoftware/AMQP-CPP#126]

**Comment by fantastory** [comment]
It was there in the examples directory :
But they removed it.
https://github.com/CopernicaMarketingSoftware/AMQP-CPP/commit/1392e2b8736e035f26935e6f6f41de82d4eae886

**Comment by progovoy** [comment]
Tried to use it without success. The messaging publishing doesn't work at all. Maybe this was a reason why they removed it. Thanks for the reference anyway..

**Comment by fantastory** [comment]
I am using a copy it with vs2015 and works well
