### ISSUE TITLE
Is AMQP-CPP thread safe??

### ISSUE THREAD

**Issue by sheetalrkadam** [CopernicaMarketingSoftware/AMQP-CPP#128]
Hi Emiel,

Is AMQP-CPP thread safe. 
Can I use this library to create multiple threads with one tcp connection  shared between threads. But with multiple channels, i.e one channel per thread?

Thanks,
Sheetal

**Comment by sheetalrkadam** [comment]
Hi,

Request for info on using one channel per thread and only 1 thread establishing connection with rmq.
Channels: A channel is a sort of virtual connection, and it is possible to create many channels that all use the same connection.

Is it possible to achieve this in a multithreaded application? if So how can we achieve with connection object not being thread safe?

Thanks,
Sheetal

**Comment by EmielBruijntjes** [comment]
Yes and no. The AMQP-CPP library is thread safe. No global or static variables are used, and you can safely use it in a multithreaded application.

An AMQP object, however, is **not** thread safe. You can not call multiple methods on the same object from multiple threads at the same time. This means that you cannot have one AMQP-CPP connection, and send data to over it simultaneously from multiple threads.

**Comment by tilsche** [comment]
@EmielBruijntjes @zerodefect How does this affect usage within a multi-threaded IO service, such as asio? The l[ibboostasio example](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/master/examples/libboostasio.cpp#L30) explicitly mentions thread safety. Is there some magic going on that ensures that one AMQP-CPP object is handled only by one service thread?

It would be really nice if the documentation could be clarified for this.

**Comment by EmielBruijntjes** [comment]
I did not make the boost asio example, nor do i use it, i have no idea how it works.

But as a general rule: amqp-cpp is thread safe, but the objects are not. You can not acces a connection from multiple threads at the same time. But you can have multiple connections running in different threads.

**Comment by zerodefect** [comment]
Internally, I use an asio strand to ensure that only one thread from the given boost pool acts on object at any one time.

**Comment by zerodefect** [comment]
....so my comment in the example code was to demonstrate that the number of threads in boost asio pool has no affect on safety of implementation for a given object. That comment was not meant to address the overall thread safety of AMQP-CPP.
