### ISSUE TITLE
Returned Messages

### ISSUE THREAD

**Issue by RZRCDR** [CopernicaMarketingSoftware/AMQP-CPP#129]
Hi @EmielBruijntjes

I have a question in regards to the "mandatory" flag on basic.publish and then also on basic.return.

Looking back in history for the publish function on channel, it had the flags parameter.
I know RabbitMQ 3 has removed the "immediate" flag so I am not concerned about it at all.
Initially you did implement "basic.return", thus providing support for the flag "mandatory" and returning
unroutable messages.

What was the reason for removing this?
Is there a possibility that a changed implementation in regards to this will be put in place in a future version of the API?

I am very curious as to why this has been removed very early on.

Thank you.

**Comment by EmielBruijntjes** [comment]
I do not remember removing it, so I can only guess what my motifs were. In our organization we do not need this method, and the implementation was probably too much work to spend time on, giving the fact that we had no need for it.

If you publish messages with a "mandatory" flag, you (meaning: the channel object) must be prepared to receive future frames with returned messages, collect and group them, and pass them to a user space function. From a technical standpoint it would of course be very well possible to do this, but I can imagine that when I implemented this I decided to leave this feature out. Most channel objects are not even used for publishing, so it would be a waste to have all these extra members. Although with a smart architecture this can be overcome.

So, in the end there is no real technical reason - just a matter of considering the time that it would take to implement and document it (quite a lot) and the complexity that it would add to the library (it would make it more complex), and how much we needed it (not at all!), we left it out.

But if you send in a pull request with this feature that matches the API and programming style of the rest of the library, I am happy to accept it.
