### ISSUE TITLE
can we have same Channel shared across threads ?

### ISSUE THREAD

**Issue by sheetalrkadam** [CopernicaMarketingSoftware/AMQP-CPP#135]
Hi, 

Could you please let us know if I can use same channel shared between threads. 
Example:
Thread1: One connectionManager Thread creating connection and channels. once msgs are received, posting the msgs correspoding to channel1 to thread2 and channel2 to thread3.
Thread2: Process the msgs and then acks the msgs using the same channel
Thread3: Process the msgs and then acks the msgs using the same channel
So, channel is used by thread1 and thread2 or thread1 and thread3.

Could you please let me know if same channel can be shared between threads, if not how can we create one connection with multiple channel (one channel per thread).

Thanks,
Sheetal

**Comment by EmielBruijntjes** [comment]
The AMQP lib is thread safe (no global vars are used internally), but the objects are not. You can therefore NOT acces a connection or channel object from multiple threads at the same time without some kind of locking. Even if you use 2 channels that both use the same connection

**Comment by sheetalrkadam** [comment]
Thanks, for the immediate response.  
"A channel is a sort of virtual connection, and it is possible to create many channels that all use the same connection."
I have another query:
Thread1 : Establishing connection with RMQ broker and  creating channels using locks. Assigned channel1 to Thread2, and channel2 to Thread3.
Thread2: processing msgs and sending acks 
Thread3: processing msgs and sending acks 

But since the msgs are received on the same connection (socket), it is always received by the Thread1. We need to post these msgs to different threads for furthur processing.  probably, we could have received the msgs in the context of the thread creating the channel (not sure).
How can we use of multiple virtual connections in multithread application. 

Thanks,
Sheetal

**Comment by EmielBruijntjes** [comment]
Be careful: sending ack's also goes over the same connection and should not interfere with other acks or other read or write operations on the same connection. Things get messy if you have two threads that try to send to the same connection. You do need some sort of mutex protection to prevent this from happening.

We always stick with one connection per thread. For MailerQ for example, we create a couple of threads with connections to RabbitMQ machines and start consuming. One a message is received, we hand the received message over to a different worker thread that further process the message. When the message has been processed, it is handed back to the consumer thread where it will be ack'ed again.

But I'm not going into more details. This is not a forum for event driven multi threaded software architecture.

**Comment by sheetalrkadam** [comment]
Thank you so much  for the quick response. 
We have been using RabbitMQ-C client library and amqpcpp library creating   one connection per thread. C library is not thread safe and did not provide the flexibilty of creating multiple channels. So, tried exploring this library.
