### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by nikitablack** [CopernicaMarketingSoftware/AMQP-CPP#14]
Hello. Thank you for the library. But I can't even run it. I'm using Win7 and VS2013. Using CMake I generated a project for VS. But when I'm trying to build it I have tons of errors. For example:

```
fatal error C1083: Cannot open include file: 'amqpcpp/classes.h': No such file or directory
```

and a lot of similar.
I've tried to change include declarations from

```
#include <amqpcpp/classes.h>
```

to

```
#include "classes.h"
```

but it shows me

```
error C3861: 'htobe16': identifier not found
```

because I don't have `<endian.h>` on my system.

**Comment by LiamKarlMitchell** [comment]
The paths are different, on linux the files get put somewhere as part of the Makefile which makes it so the system include #include "amqpcpp/classes.h" works.

For windows, we would have to do some kind of symlink or move files around.
I would have thought it would be more appropriate to use relative includes?

```
#include "include\classes.h"
```

I've not come across using <> for anything but standard library/os sdk includes.

Forgive me if this is not the case for linux code my knowledge is lacking (let me know if it is best practice).
From memory, other libraries I have seen use relative includes, and have their main .h in the includes dir.

Example: https://github.com/spurious/SDL-mirror/blob/master/include/SDL.h

There is another issue for windows build however, might try that.
