### ISSUE TITLE
irregular consuming of messages

### ISSUE THREAD

**Issue by lazedo** [CopernicaMarketingSoftware/AMQP-CPP#141]
Hi,

i'm evaluating this library as an alternative to rabbitmq-c and noticed a weird thing.

when using librabbitmq (publisher in pictures),  the rate is stable.
when using AMQP-CPP (consumer) it shows 0, the expected value or the double.
i'm using the libevent.cpp sample with a change for 5 channels consuming from a shared queue.
the consumer just outputs the message body to stdout.
i experienced the same behaviour when using AMQP-CPP as a producer.

as anyone experienced the same ?

Thanks

![screenshot](https://user-images.githubusercontent.com/770988/28959356-05e4f0a8-78f2-11e7-916d-ee9b5b7539e1.png)
![screenshot 1](https://user-images.githubusercontent.com/770988/28959365-1057f3c8-78f2-11e7-881c-af06ed3592f8.png)
![screenshot 2](https://user-images.githubusercontent.com/770988/28959370-14172984-78f2-11e7-9a83-7d74a24052cd.png)

**Comment by EmielBruijntjes** [comment]
I'm not exactly sure what you mean. Are you saying that you experience hick-ups? Maybe there is some blocking operation somewhere, or the TCP_NODELAY option was not correctly set internally by the AMQP library. Would it be possible for you to dig deeper?

**Comment by lazedo** [comment]
@EmielBruijntjes thanks for the feedback. the hickups are constant. two programs consumer/producer, built with librabbitmq/amqp-cpp. the amqp-cpp is based on the libev in tests dir. i just removed the extra channels/consumers but behaviour is still the same.
can you point me in the direction where i should look for the TCP_NODELAY ?  i'm using master from yesterday.

btw, this looks awesome so far

**Comment by lazedo** [comment]
@EmielBruijntjes recompiled everything and it seems much stable now. closing this. sorry for the noise.
