### ISSUE TITLE
How to reconnect when use TcpHandler

### ISSUE THREAD

**Issue by swpuzhang** [CopernicaMarketingSoftware/AMQP-CPP#142]
if client disconnetct ，how can I reconnect server.
just like this， Recreate again??
 virtual void onClosed(AMQP::TcpConnection *connection) 
{
Recreate 
 MyTcpHandler myHandler;
AMQP::Address address("amqp://guest:guest@localhost/vhost");
AMQP::TcpConnection connection(&myHandler, address);
AMQP::TcpChannel channel(&connection);
channel.declareExchange("my-exchange", AMQP::fanout);
channel.declareQueue("my-queue");
channel.bindQueue("my-exchange", "my-queue", "my-routing-key");
}

**Comment by EmielBruijntjes** [comment]
Yes indeed something like that, but then of course written by a C++ programmer.
