### ISSUE TITLE
how to know publis is success  or failed?

### ISSUE THREAD

**Issue by swpuzhang** [CopernicaMarketingSoftware/AMQP-CPP#143]
when I test publish  ,I connect rabbitmq-server success and then I sleep 10s,
In the meantime， I kill rabbitmq-server,  after 10s, I publish my message,.
sleep(10);
bool b = m_pChannel->publish("topic", "my_queue", "Hello World!", strlen("Hello World!") + 1);

the result is that b == true, and  Channel::onError() has not be called..
I don't no know how to do to get publish result?
please help me 。 so urgent

**Comment by EmielBruijntjes** [comment]
Publish operations are normally not confirmed, so you cannot know whether they've succeeded. 

If you want to capture errors with the connection (like rabbitmq crashing), you should make sure you implement the onError() method in the ConnectionHandler class.
