### ISSUE TITLE
connectionimpl.cpp not found (getting at runtime) using AMQP-CPP library in windows

### ISSUE THREAD

**Issue by vikaschamp** [CopernicaMarketingSoftware/AMQP-CPP#153]
I am using amqp-cpp in visual studio 2017 .
I have installed AMQP-CPP-vc140.2.6.1.5 (version) installed from nuget package in vs2017. 

I have implemented code but while making connection i am getting "connectionimpl.cpp not found" while debugging program.

#pragma once
#pragma once
#include <amqpcpp.h>

(1) Header.h
class MyConnectionHandler : public AMQP::ConnectionHandler
{
	
	virtual void onData(AMQP::Connection *connection, const char *data, size_t size){}
	virtual void onConnected(AMQP::Connection *connection){}
	virtual void onError(AMQP::Connection *connection, const char *message){}
	virtual void onClosed(AMQP::Connection *connection) {}	
};

(2) main.cpp
#include "stdafx.h"
#include "Header.h"

int main()
{

	MyConnectionHandler my;
	AMQP::Connection connection(&my, AMQP::Login("guest", "guest"), "/");
	AMQP::Channel channel(&connection);
        channel.declareExchange("my-exchange", AMQP::direct);
	channel.declareQueue("my-queue");
	channel.bindQueue("my-exchange", "my-queue", "my-routing-key");

	return 0;
}

Please suggest me what should i do?

Thanks in advance.

**Comment by fantastory** [comment]
**At runtime** 
Debugger tries stepping into function that is compiled into a library?

**Comment by fantastory** [comment]
I think you should only open issues that repository owner can reproduce. 
Since CopernicaMarketingSoftware uses only linux enviroment they can not.
Ther must be some other way to discuse a library - but I do not know it.

**Comment by vikaschamp** [comment]
Debugger tries stepping into function that is compiled into a library? == **Yes sir it is compiled into library**

**Comment by fantastory** [comment]
If so than why do you need the cpp file?

**Comment by EmielBruijntjes** [comment]
Closing this issue since it seems inactive, and I cannot help here as I do not use Visual Studio.
