### ISSUE TITLE
Crash in ~ChannelImpl() - should remove() also detach()?

### ISSUE THREAD

**Issue by jgallagher** [CopernicaMarketingSoftware/AMQP-CPP#154]
Hi! If you run the following program and then "force close" the connection from the RabbitMQ management GUI, it crashes in `ChannelImpl::~ChannelImpl()`.

```c++
#include <optional>
#include <amqpcpp.h>
#include <amqpcpp/libuv.h>

class MyHandler : public AMQP::LibUvHandler {
private:
    std::optional <AMQP::TcpChannel> _channel;

public:
    MyHandler(uv_loop_t *loop) :
            AMQP::LibUvHandler(loop),
            _channel(std::nullopt) {
    }

    void onConnected(AMQP::TcpConnection *connection) override {
        _channel.emplace(connection);
    }

    void onError(AMQP::TcpConnection *connection, const char *message) override {
        // Uncommenting this fixes the crash since the channel will be
        // destructed before the connection.
        //_channel = std::nullopt;
    }
};

int main() {
    auto loop = uv_default_loop();
    MyHandler handler(loop);
    AMQP::TcpConnection conn(&handler, AMQP::Address("amqp://guest:guest@localhost"));
    AMQP::TcpChannel chan(&conn);
    uv_run(loop, UV_RUN_DEFAULT);
    return 0;
}
```

Because `MyHandler` is holding on to a `TcpChannel`, the channel is destructed after the `TcpConnection`. That would be ok if the connection had called `detach()` on the channel when it was destructed, but that never happened because of `ChannelImpl::reportError()`:

```c++
    // the connection no longer has to know that this channel exists,
    // because the channel ID is no longer in use
    if (_connection) _connection->remove(this);
```

Should that `remove` be followed up with a `detach`?

**Comment by EmielBruijntjes** [comment]
Hmm, this is an interesting point. For now, I would say that this is not a bug, but a consequence of the architecture of this library.

The constructor of the Channel class requires you to pass in a pointer-to-a-Connection. This implies that this pointer must stay valid for the entire lifetime of the Channel object. If you do destruct the Connection before you destruct the Channel, you will indeed run into errors. _Even when it seems logical to destruct the connection_.

This is a design principle of the library: pointers passed in from user space are considered to be safe. It is also true for other pointers that you can pass to the library, like the pointer to the ConnectionHandler that you pass to a Connection instance. You cannot destruct this object either while the Connection object is still alive.

Although in your specific code sample if may seem logical to destruct the connection first and then the channel, it is not what this library expects from user-space programs. I would recommend to restructure your code a little so that there can never be a scenario in which connections are destructed before channels, or more general: in which "parent" objects are destructed before objects that depend on / refer to them.

**Comment by lacombar** [comment]
Shouldn't the API uses smart pointers to prevent these kind of issues ?

**Comment by EmielBruijntjes** [comment]
Not really, because that would force all user space programs in the world to always use smart pointers for connection and handler objects, even when they do not even destruct connections while channels are still in use, only because one person uses this peculiar architecture.

**Comment by lacombar** [comment]
not specifically, the current constructor could be kept and build an internal-only smart pointer with a custom no-op destructor. That way, both case could be handled, giving the flexibility to use smart pointers.

**Comment by EmielBruijntjes** [comment]
Can you show me a example where the user-space program does not use a smart pointer, and __explicitly__ destructs the connection object, while the amqp-library channel object still keeps it valid because it uses a smart pointer internally?

**Comment by lacombar** [comment]
This is what I have in mind:

```
struct F                                                                                            
{                                                                                                   
        F(std::shared_ptr<int> p) :                                                                 
                p(p)                                                                                
        {}                                                                                          
                                                                                                    
        F(int *p) :                                                                                 
                F(std::shared_ptr<int>(p, [](int* p){ std::cout << "no-op deleter for " << p << std::endl; }))
        {}                                                                                          
                                                                                                    
        std::shared_ptr<int> p;                                                                     
};                                                                                                  
                                                                                                    
int main()                                                                                          
{                                                                                                   
        int unmanaged(0);                                                                           
        auto managed = std::make_shared<int>(0);                                                    
                                                                                                    
        std::cout << "unmanaged ptr at " << &unmanaged << std::endl;                                
                                                                                                    
        F f0(&unmanaged);                                                                           
        F f1(managed);                                                                              
                                                                                                    
        return 0;                                                                                   
}
```
Internally, the library uses smart pointers.

``F(int *p)`` allows legacy software continues to use a raw, unmanaged interface. They keep being responsible for object lifetime (potentially leading to the issue raised by @jgallagher).

``F(std::shared_ptr<int> p)`` allows more complex code to be safeguarded automatically about lifetime issues.

**Comment by EmielBruijntjes** [comment]
I can see what you mean. It is interesting and I may even like the approach. However, at this point in time, my opinion is that there is not much wrong with the requirement that in C++ objects sometimes depend on or refer to other objects, and that destruction therefore sometimes has to follow a certain order in order not to break things. But I will let this sink in for a while any maybe I am going to use this.
