### ISSUE TITLE
Questions: Difference between onMessage onComplete

### ISSUE THREAD

**Issue by Victsz** [CopernicaMarketingSoftware/AMQP-CPP#156]
Which should be subscribed and on what scenario? 

AMQP-CPP/include/deferredget.h

/**
     *  Register a function to be called when a message arrives
     *  This fuction is also available as onSuccess() and onReceived() because I always forget which name I gave to it
     *  @param  callback    the callback to execute
     */
DeferredGet &onMessage(const MessageCallback &callback)
 /**
     *  Register a funtion to be called when a message was completely received
     *
     *  @param  callback    The callback to invoke
     *  @return Same object for chaining
     */
DeferredGet &onComplete(const CompleteCallback &callback)

**Comment by Victsz** [comment]
For the description, does it imply onMessage will be call with an incomplete message?

**Comment by EmielBruijntjes** [comment]
The onMessage() callback is normally enough. It gets called for every message that is received. You don't need any of the other callbacks.

Under the hood RabbitMQ sends each message in multiple frames to the client: a start-frame, an optional header-frame, zero or more data-frames, and a end-of-message frame. Normally, AMQP-CPP wraps everything in a AMQP::Message object and passes it to your callback. However, if you want to handle all these frames individually, you can set the following fallbacks instead:

- onBegin()
- onHeaders()
- onData()
- onComplete()
