### ISSUE TITLE
How to find out the moment when it's safe to free resources of published message.

### ISSUE THREAD

**Issue by hoxnox** [CopernicaMarketingSoftware/AMQP-CPP#157]
I have a long running application which sends a lot of messages. I allocate memory and pass it in the Envelope. After `publish` batch of messages I want to free the allocated resources. How can I determine the moment when it is safe to do it?
The only way I see - is to close the connection and wait for the event loop to stop. After that the resources could be released. But it is not efficient solution because of reconnection overhead. What is the right way?

**Comment by EmielBruijntjes** [comment]
You can free the resources after the envelope is destructed. Which normally means right after you've made the call to Channel::publish(). The AMQP-CPP library sends your data directly to the socket, or copies the data to an internal buffer if the data could not immediately be sent. For you, there is no need to keep the data around after the call to publish().
