### ISSUE TITLE
Cannot create connection 

### ISSUE THREAD

**Issue by Victsz** [CopernicaMarketingSoftware/AMQP-CPP#158]
I create both AMQP::Connection and AMQP::TcpConnection, but, from tcp dump, there is no package sent to the endpoint address. And the program just idle without exceptions.

And neither onConnected, onError nor onClose has been called.

Test via C# client, the endpoint is good.

```

reqestHandler reqHandler;
AMQP::Connection connection(&reqHandler, AMQP::Login("user", "password"), "172.30.50.xx:5672");

std::string addressStr="amqp://user:password@172.30.50.xx:5672";
auto address = new AMQP::Address(addressStr.c_str());
	MyTcpHandler tcpHandler;
	AMQP::TcpConnection* c = new AMQP::TcpConnection(&tcpHandler, *address);


```

**Comment by Victsz** [comment]
Is there a way to explicitly create connection? or the connection will be create as the AMQP::Connection object is constructed?   
What is necessary to extend  AMQP::ConnectionHandler? besides overwrite the virtual function.

**Comment by EmielBruijntjes** [comment]
In the tests/ directory you can find a couple of examples. Make sure that you run the event loop.
