### ISSUE TITLE
I'm having trouble compiling libboostasio.cpp

### ISSUE THREAD

**Issue by ytmhub** [CopernicaMarketingSoftware/AMQP-CPP#159]
I keep getting the following errors:
/usr/local/include/amqpcpp/libboostasio.h:152:41: error: ‘boost::placeholders’ has not been declared
                                         STRAND_SOCKET_HANDLER(
                                         ^
/usr/local/include/amqpcpp/libboostasio.h: In lambda function:
/usr/local/include/amqpcpp/libboostasio.h:152:41: error: ‘fn’ was not declared in this scope

And:
/usr/local/include/amqpcpp/libboostasio.h:360:35: error: ‘boost::placeholders’ has not been declared
                 _timer.async_wait(STRAND_TIMER_HANDLER(
                                   ^
/usr/local/include/amqpcpp/libboostasio.h: In lambda function:
/usr/local/include/amqpcpp/libboostasio.h:360:35: error: ‘fn’ was not declared in this scope

I.e. : Something seems to be wrong (at least for me) with the socket and timer lambda macros.

Compiled with:
g++ libboostasio.cpp -o boost_test -lpthread -lboost_system -lamqpcpp -std=c++11 (or 14)

boost version is 1.58.

Did I miss something?

**Comment by ytmhub** [comment]
It seems that all was needed to fix this problem was to replace 'boost::placeholder::_*' with '_*'.

It should also be noted that the module should be compiled with -std=c++14 due to lambda initializers, so maybe the compilation comment in the test should be updated.

In any case, thanks for maintaining this repo!

**Comment by zerodefect** [comment]
Hi @ytmhub , thanks for raising this. I was the developer that introduced these changes.  Could you please explain the 'boost::placeholder::_*'.  I'm using boost v1.62. I'll be happy to submit the suggested changes.

**Comment by zerodefect** [comment]
This is being resolved by another developer in #163
