### ISSUE TITLE
Compile problem on test/libboostasio.cpp

### ISSUE THREAD

**Issue by Cereal84** [CopernicaMarketingSoftware/AMQP-CPP#162]
Hi,
I'm trying to compile 'test/libboostasio.cpp' using Makefile  but I've this problem:

/usr/include/amqpcpp/libboostasio.h: In member function 'void AMQP::LibBoostAsioHandler::Watcher::read_handler(const boost::system::error_code&, std::size_t, std::weak_ptr<AMQP::LibBoostAsioHandler::Watcher>, AMQP::TcpConnection*, int)':
/usr/include/amqpcpp/libboostasio.h:152:41: error: 'boost::placeholders' has not been declared
                                         STRAND_SOCKET_HANDLER(
......

I'm using libboost 1.58.0 .

**Comment by billchenchina** [comment]
See #159. Same problem.

**Comment by Cereal84** [comment]
My bad.

**Comment by zerodefect** [comment]
I'll look to fix this in #159. Thanks.

**Comment by zerodefect** [comment]
This is being resolved by another developer in #163.
