### ISSUE TITLE
clang/gcc compile error: embedding a directive within macro arguments...

### ISSUE THREAD

**Issue by lion10243** [CopernicaMarketingSoftware/AMQP-CPP#164]
Both clang/gcc throw errors compiling this library.

clang-3.9
error: embedding a directive within macro arguments has undefined behavior
 #if __cplusplus >= 201701L

gcc-5.4.0
error: embedding a directive within macro arguments is not portable
 #if __cplusplus >= 201701L

This problem occurrs because the `#if` directive is embedded within a preprocessor macro. The compiler error applies to all six lines including the __cplusplus directive check.

Also, the use of the macros (STRAND_XXX_HANDLER) should not be considered "good" modern cpp style (imho it's dirty ;-)

https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/9935f8414bdda7854bb43c18723fd56b1529a36e/include/libboostasio.h#L272

**Comment by zerodefect** [comment]
Can we mark this as resolved and close please?
