### ISSUE TITLE
Support multiple platforms through CMake

### ISSUE THREAD

**Issue by surgura** [CopernicaMarketingSoftware/AMQP-CPP#166]
The CMake file in this project is alright, but does not fully support building on platforms other than unix(-->windows). The following fork attempts to fix this: https://github.com/surgura/AMQP-CPP/tree/clean-build. This issue is for discussing this subject. Feedback and possibly help is appreciated(My CMake and make skills are limited).

The aim is to solve the following issues:
- [x] Using CMake, build on linux/windows/osx out of the box. (as long as required C++11 features are supported by the compiler)
- [x] Separate unix TCP implementation from core library.
- [x] Fix compile warnings on common systems
- [x] Cleanup CMake file and add comments.

Edit: some new goals appeared along the way:
- [x] Update Make file to use new file structure.
- [x] Update `README.md` build

**Comment by surgura** [comment]
As of commit 271cb5b60d6dbc91360d4af3bb14a6836d5cb102 I've achieved the following:

- Builds out of the box on 'Visual Studio 15 2017 Win64' and 'g++ 7.2.0'.
- LINUX_TCP enables building Unix TCP implementation, which works on 'g++ 7.2.0'.
- Fixed a bunch of warnings, but not all.
- Cleaned up the top half of the CMake file.
- Separate Unix TCP implementation from core library.

This led to the following issues:
- Original Make file is now incompatible. Do we want to repair this, or drop Make completely?
- amqpcpp.h top level include file expects some kind of linux installation method to work. Need to find a way to make this work locally as well as when installed.
- Separation breaks backwards compatibility(I moved some files)

**Comment by zerodefect** [comment]
I like the sounds of some of this.
> Fixed a bunch of warnings, but not all.

I would enable `-Wall -Werror` on linux systems (GCC/Clang) so that warnings are not re-introduced in the future.

```
option(LINUX_TCP "Build linux sockets implementation" OFF)
```

When is this option needed?

> Separation broke backwards compatibility

Can you elaborate on this?

**Comment by surgura** [comment]
> I would enable -Wall -Werror on linux systems (GCC/Clang) so that warnings are not re-introduced in the future.

What do you mean by this? To clarify, by my statement I mean that there are still some warnings appearing that I did not yet fix.

> When is this option needed?

This enables the posix sockets implementation that is provided with the original lib. As this is not platform portable I disabled building them by default. This option enables them.

> Can you elaborate on this?

I moved `tcpchannel.h`, `tcpconnection.h`, `tcpdefines.h`, tcphandler.h` to include/linux_tcp/. They where originally in include/. This means you have to update your includes in a project using AMQP-CPP. I guess this does not break backwards compatibility as long as `amqpcpp.h` is correctly updated. Updating that is one of the tasks anyway, so I guess it's not that big of a deal.

**Comment by surgura** [comment]
Fixed all compile warnings I could find. Tested on `Visual Studio 15 2017 64 bit`, `Visual Studio 15 2017 32 bit`, and `g++ 7.2.0`. I haven't taken the time yet to figure out how to compile g++ as 32 or 64 bit, so I guess I only tested one of the two.

**Comment by zerodefect** [comment]
I would be inclined to try Clang too; GCC is very forgiving.

On another note, I'm looking to integrate Travis CI into this project which will hopefully prevent "bad" code entering in the future. See #167

**Comment by surgura** [comment]
@zerodefect I saw that, yeah. Creating some examples would be good too.

Regarding  #166, there is only a few more things to discuss. Do we want to update the old Make file? Afaik it is used by Copernica itself @EmielBruijntjes ?
Furthermore, do we want CMake to support some kind of install functionality, just as the Make file did?

**Comment by zerodefect** [comment]
I'm going to say we do still want install functionality with cmake; I'll certainly use it. Going forward, would like to use cmake's ExternalProject_add() functionality to perform an in-source build of AMQP-CPP. I've not tried to do that yet with AMQP-CPP.

**Comment by surgura** [comment]
Alright I'll work on the cmake install then, but I have to say that I've never really done something like that before.

Regarding Make,  I'll update that too; it's not a lot of work anyway.

**Comment by surgura** [comment]
CMake file is cleaned up. Can now(again) install. The only difference being that the posix tcp include files are not installed in <root>/amqp/include/ but in <root>/amqp/include/posix_tcp.

ExternalProject_add() might be suited for a follow-up issue, so I leave that for now.

Only Makefile to go. I'll keep that Linux only, as I expect new users of the library to use CMake, and old users are most likely on Linux.

**Comment by surgura** [comment]
Regarding warnings for Clang; I don't have a setup for that atm. So unless someone wants to do that, I'll leave that for a follow-up issue.

**Comment by zerodefect** [comment]
I can try it out. Have you pushed all your changes to your fork?

**Comment by EmielBruijntjes** [comment]
@surgura: We use "make" to compile the library. I have never checked the cmake code, nor do I have the knowledge to see whether the pull request is good or not. When you send in a pull request and it is approved by @zerodefect, I am just going to merge it without any checking. Does this also fix the problems with compiling on windows that people always ask questions about (and for which I also have no knowledge)?

**Comment by zerodefect** [comment]
@surgura If you merge the latest upstream master into your fork and push to github, you will now be able to build with clang. You will need to [enable travis-ci](https://docs.travis-ci.com/user/getting-started) on your fork.

**Comment by zerodefect** [comment]
One other thing I would suggest is updating [.travis.yml](.travis.yml) so that it builds with both cmake and make. Currently, I'm only trying cmake.

**Comment by surgura** [comment]
@EmielBruijntjes Yes, this does fix Windows builds. To do this I needed to remove posix tcp classes from `amqpcpp.h`, so this *will* break some builds that are using the library. To fix this, you will have to include amqpcpp/posix.h as well as the usual amqpcpp.h. I will update the `README.md` with write clear directions on how to fix you build like this and also include building with CMake.

**Comment by surgura** [comment]
@zerodefect The clean-build branch of my fork is up to date. I have no experience with travis, but I'll see what I can do this evening.

**Comment by surgura** [comment]
https://travis-ci.org/surgura/AMQP-CPP

**Comment by zerodefect** [comment]
I see the clang builds are reporting a warning about pointer to itself. Have you observed that?

**Comment by surgura** [comment]
Oh, I see. Do I have to click each build to manually check for warnings, or can travis-ci help you? I'll have a look at the warning later.

Regarding travis-ci, it seems like it does not support builds on windows? At least I'm having problems finding information about it. Their doc mainly talks about gcc and clang.

**Comment by zerodefect** [comment]
Yeah, you need to check each build log. In time, I feel builds should fail on warnings, but that is one to discuss.

For Windows, check out AppVeyor; I don't have any experience using it though.

**Comment by surgura** [comment]
AppVeyor seems to work 👍 

https://ci.appveyor.com/project/surgura/amqp-cpp

**Comment by zerodefect** [comment]
Nice work!

**Comment by surgura** [comment]
@zerodefect Could you maybe have a look at that Clang warning? I feel like Clang should not be complaining about this.

**Comment by surgura** [comment]
Well, I guess every class has by default an operator to cast the type it already is..? So redefining it would be useless?

**Comment by zerodefect** [comment]
> Well, I guess every class has by default an operator to cast the type it already is..? So redefining it would be useless?

Yes, I believe so.

I'm not able to look at this in too much detail for another 24 hours. Limited access. I'd see who added that code, and I'd also see what happens if you remove it.

**Comment by surgura** [comment]
Oh haha, the amqpcpp source already states that the clang warning is incorrect. Fair enough

**Comment by surgura** [comment]
Alright, I fixed almost everything. Only a few more things:
- [ ] When using the library in a project on Windows, `NOMINMAX` is required. Add this to README.md.
- [ ] When using the library in a project on Windows, there are compile error for `htonll` and `strcasecmp`.
- [ ] Add the requirement for pthread in README.md for CMake.
- [ ] Test if the DLL build is correct by using in a test project on Windows.

**Comment by zerodefect** [comment]
By the way, I've created a branch which allows me to build a few of the examples in Travis CI. 

In order to do this, I've had to move a few files around (and a few cmake tweaks). Not sure whether I should wait for you to go first?

**Comment by surgura** [comment]
You could maybe fork my fork? Should be really different though, except that everything builds to bin/ and the moved tcp module.

**Comment by surgura** [comment]
Created pull request.

Two more things that might be interesting:
- Find_AMQP-CPP script CMake. Think something like this: https://github.com/SFML/SFML/blob/master/cmake/Modules/FindSFML.cmake
- DLL for Windows. AMQP-CPP does not export any symbols currently.

**Comment by zerodefect** [comment]
Tried to add support to build examples. I can't quite get it to go. What is throwing me off is linux_tcp.  I don't want to break anything in your branch.

https://github.com/zerodefect/AMQP-CPP/tree/clean-build

**Comment by surgura** [comment]
What do you mean linux_tcp is throwing you off? Building without examples works correctly for you?

**Comment by zerodefect** [comment]
Yes, a bit confused on how to get the examples built.  Everything else is okay.

**Comment by zerodefect** [comment]
I've added a 'AMQP-CPP_BUILD_EXAMPLES' option by the way.

**Comment by surgura** [comment]
Okay good. I hope we can push this one through soon. Are you able to figure it out, or do you need help?

**Comment by zerodefect** [comment]
Yeah, I need help. I can do some things (which feel like cheese) to get it going, but I'm mindful that your goal here is to get Windows builds going.

**Comment by surgura** [comment]
I cloned your repo and everything seems to build fine for me(on Windows). The only thing that might be off is that the examples require boost and libev. Might want to add two extra options for those. AMQP-CPP_BUILD_LIBEV & AMQP-CPP_BUILD_BOOSTASIO. I guess these are no issue with the core build, as they are header only pieces.

What kind of issue do you have exactly?

**Comment by surgura** [comment]
As far as I can see your examples don't require linux_tcp.

**Comment by zerodefect** [comment]
So building on Linux with:

`cmake -DCMAKE_BUILD_TYPE=DEBUG -DAMQP-CPP_BUILD_EXAMPLES=ON ..`

```
[ 68%] Linking CXX static library ../bin/libamqpcpp.a
[ 68%] Built target amqpcpp
Scanning dependencies of target amqpcpp_libev_example
[ 73%] Building CXX object examples/CMakeFiles/amqpcpp_libev_example.dir/libev.cpp.o
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:14:
In file included from /home/gavin/code/amqp-cpp-surgura/include/amqpcpp.h:50:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/table.h:259:13: warning: conversion function converting 'AMQP::Table' to itself will never be used
    virtual operator const Table& () const override
            ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:14:
In file included from /home/gavin/code/amqp-cpp-surgura/include/amqpcpp.h:51:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/array.h:235:13: warning: conversion function converting 'AMQP::Array' to itself will never be used
    virtual operator const Array& () const override
            ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:15:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:32:29: error: expected class name
class LibEvHandler : public TcpHandler
                            ^
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:76:39: error: unknown type name 'TcpConnection'; did you mean 'Connection'?
        Watcher(struct ev_loop *loop, TcpConnection *connection, int fd, int events) : _loop(loop)
                                      ^~~~~~~~~~~~~
                                      Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:15:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:209:18: error: unknown type name 'TcpConnection'; did you mean 'Connection'?
        void set(TcpConnection *connection, uint16_t timeout)
                 ^~~~~~~~~~~~~
                 Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:15:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:253:26: error: unknown type name 'TcpConnection'; did you mean 'Connection'?
    virtual void monitor(TcpConnection *connection, int fd, int flags) override
                         ^~~~~~~~~~~~~
                         Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:15:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:253:18: error: 'monitor' marked 'override' but does not override any member functions
    virtual void monitor(TcpConnection *connection, int fd, int flags) override
                 ^
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:286:34: error: unknown type name 'TcpConnection'; did you mean 'Connection'?
    virtual uint16_t onNegotiate(TcpConnection *connection, uint16_t interval) override
                                 ^~~~~~~~~~~~~
                                 Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:15:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:286:22: error: 'onNegotiate' marked 'override' but does not override any member functions
    virtual uint16_t onNegotiate(TcpConnection *connection, uint16_t interval) override
                     ^
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:62:13: error: unknown type name 'TcpConnection'; did you mean 'Connection'?
            TcpConnection *connection = static_cast<TcpConnection*>(watcher->data);
            ^~~~~~~~~~~~~
            Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:15:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:62:53: error: unknown type name 'TcpConnection'; did you mean 'Connection'?
            TcpConnection *connection = static_cast<TcpConnection*>(watcher->data);
                                                    ^~~~~~~~~~~~~
                                                    Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:15:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:65:25: error: no member named 'process' in 'AMQP::Connection'
            connection->process(watcher->fd, revents);
            ~~~~~~~~~~  ^
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:149:13: error: unknown type name 'TcpConnection'; did you mean 'Connection'?
            TcpConnection *connection = static_cast<TcpConnection*>(timer->data);
            ^~~~~~~~~~~~~
            Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
In file included from /home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:15:
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/libev.h:149:53: error: unknown type name 'TcpConnection'; did you mean 'Connection'?
            TcpConnection *connection = static_cast<TcpConnection*>(timer->data);
                                                    ^~~~~~~~~~~~~
                                                    Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
/home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:28:32: error: no type named 'TcpConnection' in namespace 'AMQP'; did you mean 'Connection'?
    virtual void onError(AMQP::TcpConnection *connection, const char *message) override
                         ~~~~~~^~~~~~~~~~~~~
                               Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
/home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:28:18: error: 'onError' marked 'override' but does not override any member functions
    virtual void onError(AMQP::TcpConnection *connection, const char *message) override
                 ^
/home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:37:36: error: no type named 'TcpConnection' in namespace 'AMQP'; did you mean 'Connection'?
    virtual void onConnected(AMQP::TcpConnection *connection) override 
                             ~~~~~~^~~~~~~~~~~~~
                                   Connection
/home/gavin/code/amqp-cpp-surgura/include/amqpcpp/connection.h:20:7: note: 'Connection' declared here
class Connection
      ^
/home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:37:18: error: 'onConnected' marked 'override' but does not override any member functions
    virtual void onConnected(AMQP::TcpConnection *connection) override 
                 ^
/home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:68:24: error: expected ';' after expression
    AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost/"));
                       ^
                       ;
/home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:68:11: error: no member named 'TcpConnection' in namespace 'AMQP'
    AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost/"));
    ~~~~~~^
/home/gavin/code/amqp-cpp-surgura/examples/libev.cpp:68:25: error: use of undeclared identifier 'connection'
    AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost/"));
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
examples/CMakeFiles/amqpcpp_libev_example.dir/build.make:62: recipe for target 'examples/CMakeFiles/amqpcpp_libev_example.dir/libev.cpp.o' failed
make[2]: *** [examples/CMakeFiles/amqpcpp_libev_example.dir/libev.cpp.o] Error 1
CMakeFiles/Makefile2:144: recipe for target 'examples/CMakeFiles/amqpcpp_libev_example.dir/all' failed
make[1]: *** [examples/CMakeFiles/amqpcpp_libev_example.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by surgura** [comment]
Ohh I see your issue. The libev example *does* depend on linux_tcp. If you include <amqpcpp/linux_tcp.h> you should be fine.

**Comment by surgura** [comment]
I mean in libev.h. And I guess in libboostasio.h too. I guess I looked over these when making everything platform portable. These implementations depend on TcpConnection, which is part of the linux_tcp stuff.

**Comment by surgura** [comment]
I guess we need to test that and add it to my pull request.

**Comment by zerodefect** [comment]
Yes, I can merge my changes into your branch.  I'll try open a request in the next hour.

**Comment by zerodefect** [comment]
Ok. I've opened my changes now as a separate pull request. Can we close this?

**Comment by surgura** [comment]
As the pull request has been accepted I will close this. However, as of c2873827707146a9e5df1517378be43e5d22a16a the Windows build is broken again 😄, so I'll open a new issue for that.

**Comment by zerodefect** [comment]
Yes, @EmielBruijntjes needs to enable AppVeyor for Windows build on this repo _ONLY_ once your Windows builds are functional again.
