### ISSUE TITLE
Integration help with SSL

### ISSUE THREAD

**Issue by jwright85** [CopernicaMarketingSoftware/AMQP-CPP#17]
Hello,

I have a branch of your AMQP library, and it's fantastic. Thank you very much for your effort on this library. I am currently using the library on Windows, and I plan to contribute my changes, and an example application using boost asio and SSL once I get through this issue. 

I have the library working fine for plain text, but once I configure SSL, I cannot get through the AMQP handshake (note the SSL handshake is complete).  

Here is a log of my log in process:
```
c:\workspaces\distributed-platform\Build\Windows\x64\Debug\Final>AdvancedMessageQueuingProtocol.test.exe -h %COMPUTERNAME% -u jeremy -P jeremy -p 5671 -t async
--sslcert %APPDATA%\RabbitMQ\ssl\testca\cacert.pem
Reading.
Writing: AMQP 0x0 0x0 0x9 0x1

Read Done:  0x1 0x0 0x0 0x0 0x0 0x1 0xdc 0x0 0xa 0x0 0xa 0x0 0x9 0x0 0x0 0x1 0xb7 0xc capabilitiesF 0x0 0x0 0x0 0xb5 0x12publisher 0x5fconfirmst 0x1 0x1aexchange
 0x5fexchange 0x5fbindingst 0x1 0xabasic 0x2enackt 0x1 0x16consumer 0x5fcancel 0
x5fnotifyt 0x1 0x12connection 0x2eblockedt 0x1 0x13consumer 0x5fprioritiest 0x1
0x1cauthentication 0x5ffailure 0x5fcloset 0x1 0x10per 0x5fconsumer 0x5fqost 0x1
0xccluster 0x5fnameS 0x0 0x0 0x0 0x23rabbit 0x40ITC 0x2dTPE 0x2dPC 0x2d 0x30 0x3
0 0x32 0x2ecommscope 0x2ecom 0x9copyrightS 0x0 0x0 0x0 0x27Copyright 0x20 0x28C
0x29 0x20 0x32 0x30 0x30 0x37 0x2d 0x32 0x30 0x31 0x34 0x20GoPivotal 0x2c 0x20In
c 0x2e 0xbinformationS 0x0 0x0 0x0 0x35Licensed 0x20under 0x20the 0x20MPL 0x2e 0
x20 0x20See 0x20http 0x3a 0x2f 0x2fwww 0x2erabbitmq 0x2ecom 0x2f 0x8platformS 0x
0 0x0 0x0 0xaErlang 0x2fOTP 0x7productS 0x0 0x0 0x0 0x8RabbitMQ 0x7versionS 0x0
0x0 0x0 0x5 0x33 0x2e 0x33 0x2e 0x35 0x0 0x0 0x0 0xeAMQPLAIN 0x20PLAIN 0x0 0x0 0
x0 0x5en 0x5fUS 0xce

Writing:  0x1 0x0 0x0 0x0 0x0 0x0 0xc5 0x0 0xa 0x0 0xb 0x0 0x0 0x0 0x9f 0x9copyr
ightS 0x0 0x0 0x0 0x1bCopyright 0x20 0x32 0x30 0x31 0x34 0x20Copernica 0x20BV 0x
binformationS 0x0 0x0 0x0 0x18http 0x3a 0x2f 0x2fwww 0x2ecopernica 0x2ecom 0x8pl
atformS 0x0 0x0 0x0 0x7Unknown 0x7productS 0x0 0x0 0x0 0x16Copernica 0x20AMQP 0x
20library 0x7versionS 0x0 0x0 0x0 0x7Unknown 0x5PLAIN 0x0 0x0 0x0 0xe 0x0jeremy
0x0jeremy 0x5en 0x5fUS 0xce
Reading.
Read Done:  0x1 0x0 0x0 0x0 0x0 0x0 0xc 0x0 0xa 0x0 0x1e 0x0 0x0 0x0 0x2 0x0 0x0
 0x2D 0xce

Writing:  0x1 0x0 0x0 0x0 0x0 0x0 0xc 0x0 0xa 0x0 0x1f 0x0 0x0 0x0 0x2 0x0 0x0 0
x2D 0xce

Writing:  0x1 0x0 0x0 0x0 0x0 0x0 0x8 0x0 0xa 0x0 0x28 0x1 0x2f 0x0 0x0 0xce
Reading.
(10 seconds... -> Timeout)
Unhandled exception
```

My RabbitMQ log shows:
```
=INFO REPORT==== 22-Dec-2014::12:17:37 ===
accepting AMQP connection <0.10747.0> ([FE80::A15F:8DD0:4FE:924C]:49632 -> [FE80::A15F:8DD0:4FE:924C]:5671)

=ERROR REPORT==== 22-Dec-2014::12:17:47 ===
closing AMQP connection <0.10747.0> ([FE80::A15F:8DD0:4FE:924C]:49632 -> [FE80::A15F:8DD0:4FE:924C]:5671):
{handshake_timeout,frame_header}
```

It appears to me that the server simply stops responding. I know this is a client side issue, but I'm lost where to start investigating this. Could you please point me in the right direction?

**Comment by mathemaphysics** [comment]
I'm having exactly this problem now. I've used my own event loop similar to what is seen in your examples. It works flawlessly without SSL. When I set up an SSL connection via a `Poco::Net::SecureStreamSocket` as opposed to `Poco::Net::StreamSocket` (which is the one that works quite well) it gets through the SSL handshake and then just stops responding.

I know that if the data were simply encrypted and unintelligible, it would continue to logs messages complaining about that frames and it would put the connection handler in an error state. This doesn't happen. It just stops doing anything at all.

**Comment by mathemaphysics** [comment]
Check out https://github.com/mathemaphysics/agent/tree/mathemaphysics/issue36, which is the branch of `agent` which attempts to convert the class I've been using into an SSL version.

**Comment by EmielBruijntjes** [comment]
The link is broken

**Comment by mathemaphysics** [comment]
Sorry, here's a link specifically to the event loop we implemented using your recommended setup (using our own connection handler). The underlying network connection is a `Poco::Net::SecureStreamSocket` in this case.

https://github.com/mathemaphysics/agent/blob/6f706185f1c7b235e7610fc3abfa0bf5c5cdb8ec/src/IConnectionHandlerSSL.cpp#L218

To see the original unsecured it's at

https://github.com/mathemaphysics/agent/blob/6f706185f1c7b235e7610fc3abfa0bf5c5cdb8ec/src/IConnectionHandler.cpp#L196

I've discovered that after the SSL validates the connection to RabbitMQ, `_socket.available()` is 0 forever. It never completes the AMQP handshake that normally fires off `onProperties()` and prints it to the log via the logger.

**Comment by EmielBruijntjes** [comment]
Hmmm. What would you expect me to say? I am not familiar with the classes that you are using, so there is not much feedback that I can give. I saw that you did not check the return-code for the sendBytes() call, are you sure that all bytes are indeed sent? Maybe that could help you solving this? With secure connections you sometimes have to receive data while you're busy sending and the other way around, because of all the handshakes and confirmations that take place as part of the secure protocol, or you have to wait until a socket becomes readable or writable before you can move on.

Anyway, the AMQP-CPP library simply calls ConnectionHandler::onData() when it has some data to send, and it is up to you to call Connection::parse() when you've received some data. That's it. It has been implemented for TCP so it works, as long as you call the right functions at the right time.

By the way, why did you write a special SSL layer yourself? The AMQP-CPP library also supports amqps:// connections for secured AMQP connection out of the box.

**Comment by EmielBruijntjes** [comment]
Ok good luck.

Just to double-check: are you sure you don't use threads for your implementation? The AMQP::Connection object and the channels on top of it do not allow calls to their methods that come from different threads.

**Comment by mathemaphysics** [comment]
@EmielBruijntjes We do indeed use threads, but the only calls that handle `AMQP::Connection` method calls are in the main thread. The main thread does create N worker threads, but non of them even interact with the connection. I was hoping to open another channel to properly `ack` a tag directly from a worker thread via an `AMQP::Channel` if that works.

**Comment by EmielBruijntjes** [comment]
No doesn't work. Keep threads far, far, far away from code that interacts with AMQP-CPP objects. AMQP-CPP objects are not thread safe (like almost all C++ objects, you also don't append to the same string from multiple threads, or write to the same file, etc).

Use one and the same thread to:

- construct a connection
- construct channels
- call methods on the connection (like connection.parse())
- call methods on the channel (like channel.publish(), channel.declareQueue(), channel.consume(), channel.ack(), etc)
- destruct channels
- destruct a connection

Never, ever, ever make calls to the same connection (or one of its channels) from multiple threads. That will eventually end up in data that is being sent over the line in the wrong order, which will make it impossible for RabbitMQ to process your input.

You code needs a massive refactor. Remove all std::thread stuff and keep it far away from the AMQP protocol.
