### ISSUE TITLE
Example for MyTcpHandler monitor Method and Event Loop

### ISSUE THREAD

**Issue by selbolder** [CopernicaMarketingSoftware/AMQP-CPP#178]
I want to understand the usage of that library deeper, but I got stuck with that monitor method inside MyTcpHandler class which you gave as example in the manual. I'm clueless what to do there, and what to do in the caller function. Can you give an example wihtout the usage of third party libraries like libevent or libev?

**Comment by EmielBruijntjes** [comment]
Do you already have an event loop? What do you use? select()? poll()?

**Comment by selbolder** [comment]
Hello, I used select.
