### ISSUE TITLE
Unclear build instructions (or cmake version difference)

### ISSUE THREAD

**Issue by dwburke** [CopernicaMarketingSoftware/AMQP-CPP#186]
I had to locate the correct names to pass the LINUX_TCP and BUILD_SHARED to cmake:

`cmake .. -DAMQP-CPP_LINUX_TCP=1 -DAMQP-CPP_BUILD_SHARED=1`

On ubuntu 17.10, cmake version 3.9.1

**Comment by surgura** [comment]
Oh I see. You mean I forgot. The prefix right? I'll add a pull request later.

**Comment by surgura** [comment]
see #187
