### ISSUE TITLE
Little endian assumed

### ISSUE THREAD

**Issue by surgura** [CopernicaMarketingSoftware/AMQP-CPP#196]
See file https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/master/include/amqpcpp/endian.h
Row 66, `#define htole16(x) (x)`

`htole` means host to little endian. As this is defined as the identity function, does this mean we assume all systems are little endian..? I mean this is a fair assumption for most servers, but might not be true for things like embedded software.

**Comment by EmielBruijntjes** [comment]
I have no idea. This endian.h file does not come from us, nor do we use it or rely on it. Is this an issue for you?

**Comment by surgura** [comment]
Not currently. I'm pointing it out, because it might be an issue in the future.

**Comment by gchaviaras** [comment]
@surgura  what about the line 63 ?
`63: #if BYTE_ORDER == LITTLE_ENDIAN`
`...`
`66: #define htole16(x) (x)`
`...`
`80: #elif BYTE_ORDER == BIG_ENDIAN`
`...`
`84: #define htole16(x) __builtin_bswap16(x)`

So, apparently the whole thing is a pre-processor's  if-else statement

**Comment by surgura** [comment]
Oh I see, I'm blind.
