### ISSUE TITLE
How to shutdown a AMQP-CPP service cleanly with the asio implementation?

### ISSUE THREAD

**Issue by tilsche** [CopernicaMarketingSoftware/AMQP-CPP#197]
With the given documentation and example I struggle to implement a clean shutdown solution. Specifically a `SIGINT` handler that stops a AMQP-CPP / asio based service cleanly, e.g. ensure that all pending acknowledgements are sent.

Consider a setup with several connections and channels and an `asio::io_service`. Is it sufficient to just call `close` on all connections and then immediately `io_service::stop`?

```
    signals.async_wait([this](auto, auto signal) {
        if (!signal)
            return;
        rpc_connection->close();
        data_connection->close();
        io_service.stop();
    });
```

I have not found a way get a actual close-callback for a connection. Or do I need to specify close callbacks for all channels manually?

**Comment by EmielBruijntjes** [comment]
In your connectionhandler class you can override and implement the onClosed() method. The default implementation does nothing but your impl could stop the event loop.

Btw: If you close all connections, the event loop notmally comes to an end (if the application did not open other fds or set timer). But im not sure how it works with boost asio, that code was once submitted as pull request and is not used or maintained by me.

**Comment by tilsche** [comment]
> If you close all connections, the event loop notmally comes to an end (if the application did not open other fds or set timer).

you are right, this works with the libev implementation.

> But im not sure how it works with boost asio, that code was once submitted as pull request and is not used or maintained by me.

@zerodefect 
I tracked down two issues in the asio implementation that prevent a clean shutdown:

1. The timer is not being stopped properly. The libev impementation manually changes the ref count to prevent the timer from keeping the event loop alive. I don't think such a possibility exists in asio. So I added a
```
    void onClosed(TcpConnection* connection) override
    {
        _timer.reset();
    }
```

Which does the trick for me... except that:

2. With < C++17, the `shared_ptr` keep alive the timer and the watchers even when they are reset/erased by their primary owners. The issue seems to be that `std::bind` uses the type of the argument (`shared_ptr`), instead of the function signature (`weak_ptr`)... So `_socket.release` is never called and again the main loop goes on.

**Comment by zerodefect** [comment]
@tilsche Do you have a possible fix? I'm not going to be able to look at this for a few days.

**Comment by tilsche** [comment]
Yes, I'm testing the two changes above, particularly the `_timer.reset` right now. My code is actually built with C++17, but the `shared_ptr` bit me during isolated testing.

**Comment by tilsche** [comment]
I wanted to make a PR, but I'm struggling with SSL linker issues on master. So cannot test it.

**Comment by EmielBruijntjes** [comment]
I cannot help you with the boost things, but I would like to know what linker issues you ran into?

**Comment by tilsche** [comment]
See #198 for the SSL issues.
