### ISSUE TITLE
any dynamic message send example.?

### ISSUE THREAD

**Issue by MyraBaba** [CopernicaMarketingSoftware/AMQP-CPP#204]
Hi,

first of all thanks for open sourcing such a great library. 

We are porting our scala software to the c++11. And decide to use amqpccp.

I am little bit confused:

Why we cant just publich the message ? when we use the libev ie how we dynamically change the message ? Or do we need to run libev in a seperate thread ? 

when i wrote publish-> message . etc . why its not published directly ?

yes stupid question may be :) but we are confused. 

such as I want to send message through signal/slot mechanism (QT)  but this event loop confused us and blocked.  

thx

**Comment by EmielBruijntjes** [comment]
I haven’t worked with QT for a very long time (decades). But somewhere deep inside the QT library there is an event loop too. This is the loop that makes sure that the signals are fired and the approprate handlers (slots?) are called when something happens. What you need to do, is find the QT methods to interact with this event loop, and use them to write your own AMQP::TcpHandler implementation that integrates AMQP-CPP in this loop.

As an alternative you can run all the AMQP related stuff in a separate thread with its own event loop. But be aware of thread safety! You can then not make direct calls between your regular code and the AMQP code. You need some kind of locking.

**Comment by MyraBaba** [comment]
Thanks for reply.

I think we are not fully understand the mechanism behind the eventLoop.

All examples working great. but when we enter the event loop how we can communicate with publisher to send new messages ? yes really stupid question but really stuck here.

Or should we call everything from the beginning when we are publishing new messages ? 

:)
