### ISSUE TITLE
Consume tag

### ISSUE THREAD

**Issue by roderick1980** [CopernicaMarketingSoftware/AMQP-CPP#211]
Hello,
I'd really appreciate some help with this:
As Channel::consume() comment says (_The consume tag is a string identifier that will be passed to each received message, so that you can associate incoming messages with a  consumer_), I thought that I could retrieve the tag upon message reception. However, Channel class does not offer any function for recovering the tag in question (neither does Envelope) when DeferredConsumer's onReceived callback comes into action.
Thanks in advance

**Comment by EmielBruijntjes** [comment]
The comment is indeed wrong. The consumer tag is useful if you want to cancel a consumer, but not to identify messages.

**Comment by EmielBruijntjes** [comment]
In fact: the consumer tag *is* used to link incoming messages to the original consumer, but the AMQP-CPP library uses this internally to call the appropriate callback, and does not expose it to user space. If you start multiple consumers, you do not have to do this bookkeeping yourself, AMQP-CPP parses the incoming messages and hand them over to the callback that you installed for that specific consumer.
