### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by skandragon** [CopernicaMarketingSoftware/AMQP-CPP#22]
Is this library thread safe, where a multithreaded app can work without creating one connection per thread?

**Comment by EmielBruijntjes** [comment]
It depends. The library does not use global variables, and it safe to use in a multi-threading environment.

However, connection objects uses internal buffers, and they are not protected by locks. If you want to use the same connection from within multiple threads, you will have to take care of your own locking. My advise is to use a connection only from one thread.
