### ISSUE TITLE
Сheck the existence pair exchange:routingKey

### ISSUE THREAD

**Issue by FarafontovDmitriy** [CopernicaMarketingSoftware/AMQP-CPP#223]
Hi!
Tell me please how I can check the existence in server of a queue for pair exchange:routingKey? If I publish a message for non-existent pair exchange:routingKey then message is lost.

**Comment by EmielBruijntjes** [comment]
You can do a declareQueue() call to make sure that the queue exists before you start publishing. With the AMQP::passive flag you can even use this call to just check if the queue exists, without actually declaring it if it doesn't.

**Comment by EmielBruijntjes** [comment]
I don't think this is possible with the AMQP protocol. I believe that RabbitMQ has a REST API too, which can be used to view all sorts of things that are going on internally inside RabbitMQ. But you'll need a different library to access that API, and check the documentation on rabbitmq.com to find out how it works.
