### ISSUE TITLE
TCP doesn't work on Windows?

### ISSUE THREAD

**Issue by AmilsonJunior** [CopernicaMarketingSoftware/AMQP-CPP#225]
How can I connect to a remote rabbitmq server using this library on Windows? I need to pass the IP:PORT on vHost param on AMQP::Connection constructor?

**Comment by EmielBruijntjes** [comment]
The TCP module is only implemented for Linux. You need to implement your own ConnectionHandler object in which you call the windows-specific system calls for setting up network connections. I am not a windows-programmer, and can not help you with that.
