### ISSUE TITLE
Automatically propagate include directories

### ISSUE THREAD

**Issue by kepakiano** [CopernicaMarketingSoftware/AMQP-CPP#227]
Hi,

I'm using AMQP-CPP as a git submodule and add it to my build using add_subdirectory. I'd like to add the library to my project by only linking to it as is afaik custom in modern CMake.
In order to do this, I had to add the following in AMQP-CPP's CMakeLists.txt:
```
target_include_directories(${PROJECT_NAME} PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/>
    $<INSTALL_INTERFACE:include/>
)
```
Is this the correct way and should this be added to the project or am I missing something?

**Comment by EmielBruijntjes** [comment]
The above pull request has been merged. It is supposed to fix this.
