### ISSUE TITLE
[patch] Building with CMake is broken

### ISSUE THREAD

**Issue by szreder** [CopernicaMarketingSoftware/AMQP-CPP#23]
...since commit 3e47191f9075bab90b12e666edb2144eb20e40a2 (fixed apple incompatibility), which merged CMake branch with mainline. This suggests that building with CMake wasn't tested very thoroughly since then or maybe the problem manifests using only sufficiently recent GCC versions on linux.

The compile errors are caused by undefined byte order due to NOT including system-wide `<endian.h>` header file. Due to using `<...>` notation for project-wide header files instead of `"..."` and also doing weird things regarding include directories order in top level CMakeLists.txt, the file "includes/endian.h" includes itself instead of system-wide `<endian.h>`. This is fixed by removing one offending statement from CMakeLists.txt

Additionally remove redundant depedency on Boost libraries by not adding_subdirectory() containing a simple test case for detecting Boost presence in system. Boost is currently not used anywhere in AMQP-CPP

Fixed in:
https://github.com/szreder/AMQP-CPP/commit/11bf55b6a24a624ee17cee82d380db08f92a1e05

**Comment by EmielBruijntjes** [comment]
Can you send in a pull request for this?

**Comment by szreder** [comment]
Sure. I've also recently added (in next commit) install target to CMake. Do you want me to include this feature in the same pull request?

**Comment by EmielBruijntjes** [comment]
Yes that would be nice.
