### ISSUE TITLE
Changing the delivery_mode

### ISSUE THREAD

**Issue by neilxp** [CopernicaMarketingSoftware/AMQP-CPP#231]
Hi

Dose AMQP-CPP support changing the delivery_mode of amqp property when calling channel.publish, which is described in AMQP spec at https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf, 
1.4.3 Persistent: A message that the server holds on reliable disk storage and MUST NOT lose after a
server restart.

**Comment by EmielBruijntjes** [comment]
Yes, this is supported. You should pass an AMQP::Envelope object to the Channel::publish() method, and set delivery-mode in the envelope to the appropriate value.

```c++
AMQP::Envelope env(message, size);
env.setDeliveryMode(2);
channel.publish(exchange, routingkey, env);
```

Above is untested pseudo-code
