### ISSUE TITLE
Cannot leave the event loop

### ISSUE THREAD

**Issue by jdtotow** [CopernicaMarketingSoftware/AMQP-CPP#233]
Hello,
I'm using AMQPCPP on a project with Qt, i reimplemented TcpHandle to be able to send signal in the way of Qt and it's working fine.
When i initialize my connection i call event_base_loop(loop,0) when my class MyHandler emit the signal connected, i break the loop with event_base_loopbreak(loop). I can see a new connection on Rabbitmq server management (browser). Until now everything is working as expected.
Now when i  initialize my TcpChannel, if i try to call event_base_loop(loop,0) again i got the following warning 

> [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.

If i try to recall 

> loop = event_base_new()

 then after the initialization of the channel, a channel is created on my server and the callback function is called normally and the instruction (inside the callback)

> event_base_loopbreak(loop)

 is returning 0 but the application is still not responding like the loop was still running.
My configuration is Ubuntu LTS 16.04 and here is my code 

```
// initialization of the connection
void Project::initializeConnection()
{
    loop = event_base_new();
    connection_handler = new MyHandler(loop);
    connect(connection_handler,SIGNAL(connected()),this,SLOT(connected()));
    connect(connection_handler,SIGNAL(error(AMQP::TcpConnection*,QString)),SLOT(errorConnection(AMQP::TcpConnection*,QString)));
    connect(connection_handler,SIGNAL(closed(AMQP::TcpConnection*)),SLOT(closeConnection(AMQP::TcpConnection*)));

    AMQP::Address address("amqp://admin:12345@localhost:5672");
    // create a AMQP connection object
    connection = new AMQP::TcpConnection(connection_handler, address);
    event_base_loop(loop,0);
}
// connected
void Project::connected()
{
    setConnectionStatus("connected");
    event_base_loopbreak(loop);
}
//initialization of the channel
void Project::initChannel()
{
    channel = new AMQP::TcpChannel(connection);
    QString idnumber = QUuid::createUuid().toString();
    setIdNumber(idnumber);
    std::string idn = idnumber.toStdString();
    loop = event_base_new();
    channel->declareQueue(idn,AMQP::exclusive).onSuccess([&](const std::string &name, uint32_t messageCount, uint32_t consumerCount){
        Q_UNUSED(name)
        Q_UNUSED(messageCount)
        Q_UNUSED(consumerCount)
        qDebug() << "queue declared"; // the message is printed
        event_base_loopbreak(loop); // it is returning 0
    });
    event_base_loop(loop,0); // if i remove this line , the loop is still running
}
```
How can i solve this problem , thank you !

**Comment by EmielBruijntjes** [comment]
This is more a Qt question than an AMQP-CPP question. So you better consult the Qt documentation if you want to find out how you can integrate file-descriptors in the Qt event loop. The approach that you are taking (using libevent?) is probably wrong, because I think that Qt uses its own event loop mechanism (but I'm guessing here, I am not Qt expert, maybe http://doc.qt.io/qt-5/qsocketnotifier.html does the trick?). Good luck.
