### ISSUE TITLE
Cannot cleanly exit the event loop with LibEvHandler

### ISSUE THREAD

**Issue by EHadoux** [CopernicaMarketingSoftware/AMQP-CPP#237]
Hi everyone, 

I am trying to exit the event loop as cleanly as possible but I cannot manage to do it.
My minimal example is as follows: 
1. I declare a queue ```discovery``` and an exchange.
2. I declare another queue with a name generated by the server and ```onSuccess``` I publish this name on ```discovery``` and close the connection.

However the loop does not exit at this point.

```c++
#include <ev.h>
#include <amqpcpp.h>
#include <amqpcpp/libev.h>
#include <amqpcpp/linux_tcp.h>

int main() {
  auto loop = EV_DEFAULT;
  AMQP::LibEvHandler handler(loop);
  AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost"));
  AMQP::TcpChannel channel(&connection);

  channel.declareQueue("discovery", AMQP::passive);
  channel.declareExchange("discovery_ex", AMQP::ExchangeType::direct);
  channel.bindQueue("discovery_ex", "discovery", "");
  channel.declareQueue(AMQP::exclusive).onSuccess([&channel, &connection](auto name, uint32_t, uint32_t) {
    std::cout << "Sending discovery message." << std::endl;
    channel.publish("discovery_ex", "", "READY " + name);
    connection.close();
  });

  ev_run(loop);

  return 0;
}
```

The publishing works as my code in Python on the other end writes the name in the console:
```
b'READY amq.gen-U4c7ddGI-0Z3TU5aRaDIbA'
```

And the logs from RabbitMQ show that the connection is made and closed:
```
2018-06-26 11:03:13.150 [info] <0.1869.0> accepting AMQP connection <0.1869.0> (172.20.0.1:54504 -> 172.20.0.2:5672)
2018-06-26 11:03:13.267 [info] <0.1869.0> connection <0.1869.0> (172.20.0.1:54504 -> 172.20.0.2:5672): user 'guest' authenticated and granted access to vhost '/'
2018-06-26 11:03:13.358 [info] <0.1869.0> closing AMQP connection <0.1869.0> (172.20.0.1:54504 -> 172.20.0.2:5672, vhost: '/', user: 'guest')
```

Note that putting a ```ev_break(loop, EVBREAK_ALL)``` after the ```connection.close()``` works but generates memory leaks.

Thank you!

**Comment by EHadoux** [comment]
After investigation it seems that even though the connection is properly closed and timers removed, some watchers (I don't know what they are watching) are still there and trigger the monitor which prevent the loop from stopping.

**Comment by EmielBruijntjes** [comment]
I've modified your code to:

```c++
#include <ev.h>
#include <amqpcpp.h>
#include <amqpcpp/libev.h>
#include <amqpcpp/linux_tcp.h>

int main() {
  auto loop = EV_DEFAULT;
  AMQP::LibEvHandler handler(loop);
  AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost"));
  AMQP::TcpChannel channel(&connection);
  
  channel.onError([](const char *message) {
      std::cout << "channel error " << message << std::endl;
  });

  channel.declareQueue("discovery", AMQP::passive);
  channel.declareExchange("discovery_ex", AMQP::ExchangeType::direct);
  channel.bindQueue("discovery_ex", "discovery", "");
  
  std::cout << "declare queue" << std::endl;
  
  channel.declareQueue(AMQP::exclusive).onSuccess([&channel, &connection](const std::string &name, uint32_t, uint32_t) {
    std::cout << "Sending discovery message." << std::endl;
    channel.publish("discovery_ex", "", "READY " + name);
    connection.close();
  }).onError([](const char *message) {
    
    std::cout << "error " << message << std::endl;  
      
  });
  std::cout << "start event loop" << std::endl;

  ev_run(loop);

  return 0;
}
```

Then I ran into the following error:

```
channel error NOT_FOUND - no queue 'discovery' in vhost '/'
```

Are you sure that the "discovery" exchange exists? I removed the "AMQP::passive" flag from the declareQueue() call, and then everything seems to work fine.

**Comment by EHadoux** [comment]
> Are you sure that the "discovery" queue exists?

Yes, it's started by another server, hence the passive, but I should have removed it in the example you are right.

Literally copy pasting what you have written (with the AMQP::passive removed) and running it with a rabbitmq server running and reachable I get:

```
declare queue
start event loop
Sending discovery message.
```

And then it's stuck, even though the call to ```connection.close()``` works as rabbitmq logs ```closing AMQP connection```.

Looking at the code, it's because some kind of timer is set up (the heartbeat stuff) and it's not removed at the same time as the connection so it keeps alive the loop as well.

**Comment by EmielBruijntjes** [comment]
Do you use the master branche of AMQP-CPP? This is the output that I get:

```
emiel@emiel:~$ ./a.out 
declare queue
start event loop
Sending discovery message.
emiel@emiel:~$ 
```

So for me it seems to work.

**Comment by EHadoux** [comment]
> Do you use the master branche of AMQP-CPP? 

Yes 3d33332c23935b065226051fe3e47bc9a1b00272, compiled with the flag ```AMQP-CPP_LINUX_TCP``` on with gcc 7.3.0, and ```-std=c++1z``` for the main program. I am on Ubuntu, are you on MacOS?

**Comment by EmielBruijntjes** [comment]
@EHadoux do you already have more information?
