### ISSUE TITLE
Messages not being published

### ISSUE THREAD

**Issue by davide84** [CopernicaMarketingSoftware/AMQP-CPP#239]
I started using this library a few months ago and I like it :) but recently an undesired behavior appeared. My services stop publishing after a short time, say one minute but can be more. Broker and consumers work fine, e.g. if I manually publish a message from the broker web gui.

I created a minimal working example (99 lines) of my C++ publisher, plus a Python consumer to complete the test. My configuration is AMQP-CPP 3.1.0, Ubuntu 18.04, rabbitmq-server, pika and C++11 with no external dependencies (e.g. no boost). One month ago I was using Ubuntu 16.04; I don't know if it matters. To run it, AMQP-CPP is compiled with make, my .cpp has gcc command as a comment in the header.

[mwe.zip](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/files/2206413/mwe.zip)
[exchange_monitor.zip](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/files/2206414/exchange_monitor.zip)

**Comment by davide84** [comment]
Hi All,
I tried a lot to understand this issue and I may have found something. What I am doing in my wrapper class is something like this (pseudocode):

```
MyClass::publish(exchange, routing, message) {
  TcpChannel::declareExchange(exchange)
  TcpChannel::publish()
}
```

I suspect the two calls conflict with random timing. If I remove the exchange declaration the problem seems to go away.
Maybe I should get rid of exchange declaration for good, or do something like

```
MyClass::publish(exchange, routing, message) {
  TcpChannel::declareExchange(exchange)
  .onSuccess(TcpChannel::publish())
}
```

I would welcome any confirm of my ideas...

Also, I was getting no errors associated to the loss of publishing... maybe that is still an issue?

**Comment by EmielBruijntjes** [comment]
You're accessing the AMQP objects from two threads at the same time. This is wrong and leads to undefined behavior.
