### ISSUE TITLE
How to publish while event loop running?

### ISSUE THREAD

**Issue by HarHarVeryFunny** [CopernicaMarketingSoftware/AMQP-CPP#242]
Given that the AMQP-CPP connection and channel objects are not thread-safe, is it OK (without any mutex synchronization) to have an event loop running in one thread, while using an associated channel in another (single) thread to produce messages? If not, what is the intended API usage to intermittently produce messages while the associated event loop is continuously running?

**Comment by EmielBruijntjes** [comment]
It does not sound OK. I'm not sure if I understand the rest of your question. Your program runs an event loop, and whenever a message (or something else) comes in from RabbitMQ, the AMQP-CPP library calls a callback function to notify your program about the event.
