### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by nabroyan** [CopernicaMarketingSoftware/AMQP-CPP#244]
I am trying to use AMQP-CPP library for messaging, however I can not make it work. I want to use already built classes from the library for channel, connection, handler. I started with examples but every time running the code I get 
> Bad file descriptor

 error and process ends. My code is based on the example and looks like this

```
#include <amqpcpp.h>
#include <amqpcpp/libboostasio.h>
#include <boost/asio/io_service.hpp>
#include <boost/asio/strand.hpp>
#include <boost/asio/deadline_timer.hpp>

class MyHandler : public AMQP::LibBoostAsioHandler
{
public:
    MyHandler(boost::asio::io_service& service)
        : AMQP::LibBoostAsioHandler(service)
    {
    }

    virtual void onError(AMQP::TcpConnection *connection, const char *message) override
    {
        std::cout << "MyHandler::onError " << message << std::endl;
    }
};

int main()
{
    // access to the event loop
    boost::asio::io_service service(2);

    // handler for libevent
    MyHandler handler(service);

    // make a connection
    AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://localhost/"));

    // we need a channel too
    AMQP::TcpChannel channel(&connection);

    channel.onError([](const char *message) {
        // report error
        std::cout << "channel error: " << message << std::endl;
    });
    channel.onReady([]() {
        // send the first instructions (like publishing messages)
        std::cout << "channel onReady: " << std::endl;
    });

    // create a temporary queue
    channel.declareQueue("aaa").onSuccess([&connection](const std::string& name, uint32_t messagecount, uint32_t consumercount) {

        // report the name of the temporary queue
        std::cout << "declared queue " << name << std::endl;

        // now we can close the connection
        connection.close();
    });  

    auto startCb = [](const std::string &consumertag) {
        std::cout << "consume operation started" << std::endl;
    };

    // callback function that is called when the consume operation failed
    auto errorCb = [](const char *message) {
        std::cout << "consume operation failed" << std::endl;
    };

    // callback operation when a message was received
    auto messageCb = [&channel](const AMQP::Message &message, uint64_t deliveryTag, bool redelivered) {
        std::cout << "message received" << std::endl;
        // acknowledge the message
        channel.ack(deliveryTag);
    };

    channel.consume("aaa").onReceived(messageCb)
    .onSuccess(startCb)
    .onError(errorCb);

    // run the loop
    service.run();

    return 0;
}

```
Output:
> MyHandler::onError Bad file descriptor

The error occurs on the `line service.run();` I have also tried a similar thing with libevent.
What's wrong here and how to fix?

**Comment by EmielBruijntjes** [comment]
The libboost code is not written, maintained or reviewed by me, and given the number of issues that are sent in, this backend is known to be not perfect. Please try your first steps with an other backend, like libev.

**Comment by nabroyan** [comment]
@EmielBruijntjes thanks for the prompt reply!
Is it the same for libevent? I have tried also with that backend.

**Comment by EmielBruijntjes** [comment]
We only use libev. The libboost and libevent backends were submitted by others and are not used by us.

**Comment by nabroyan** [comment]
I see. Thank you!

**Comment by nabroyan** [comment]
@EmielBruijntjes I tried with libev backend. The result is the same. I also tried to run your example without any modification, again the same result. Then I tried with version 3.1.0 and 3.0.2 and nothing changed.
However one thing changed after switching to libev - errno started to return 2 (No such file or directory) instead of 9 (Bad file number).
Do you have any idea what can be a reason for this?

**Comment by nabroyan** [comment]
I have already found the problem. The rabbit-mq server was not running.
