### ISSUE TITLE
event loop with select()

### ISSUE THREAD

**Issue by SunDontShine** [CopernicaMarketingSoftware/AMQP-CPP#247]
can you post an example of an application using the select() system call used by the Tcp module class. without the libevent handler examples. ? I see this was a closed issue previously but not resolved

**Comment by EmielBruijntjes** [comment]
Of course I can, but I do not feel like spending a lot of time on that because I do not need it myself. I'm closing this one too, because this is not an issue.

**Comment by SunDontShine** [comment]
I think it will give others a basic understanding and lead to possible future contributions. In the basic example from your readme sits on the FD and read or write is never set
