### ISSUE TITLE
Cannot connect to rabbitmq server with TcpConnection

### ISSUE THREAD

**Issue by SunDontShine** [CopernicaMarketingSoftware/AMQP-CPP#249]
I am using the  AMQP::TcpHandler example to connect to the rabbitmq server, but it sits at the **select** system call where no 'input' from that file descriptor is coming. Do I need to make some special server configuration I am not aware of? 

Here is the example code

**main.cpp**

> int main(){
> // create an instance of your own tcp handler
> MyTcpHandler myHandler;
> 
> // address of the server
> AMQP::Address address("amqp://guest:guest@localhost/vhost");
> 
> // create a AMQP connection object
> AMQP::TcpConnection connection(&myHandler, address);
> 
> // and create a channel
> AMQP::TcpChannel channel(&connection);
> 
> // use the channel object to call the AMQP method you like
> channel.declareExchange("my-exchange", AMQP::fanout);
> channel.declareQueue("my-queue");
> channel.bindQueue("my-exchange", "my-queue", "my-routing-key");
> }
> 

**MyTcpHandler.h**
```
#include <amqpcpp.h>
#include <amqpcpp/linux_tcp.h>
#include <sys/types.h>
#include  <sys/select.h>

#include <sys/fcntrl.h>

class MyTcpHandler : public AMQP::TcpHandler
{
  public:
     virtual void onConnected(AMQP::TcpConnection *connection);
    virtual void onError(AMQP::TcpConnection *connection, const char *message);
    virtual void onClosed(AMQP::TcpConnection *connection) 
     virtual void monitor(AMQP::TcpConnection *connection, int fd, int flags);
}
```

**MyTcpHandler.cpp**
For the functions of the _MyTcpHandler_ class I had simple print strings that were never called. For simplicity I excluded the bodies of the functions other than the _monitor_ function.

```

class MyTcpHandler
{
    void onConnected(AMQP::TcpConnection *connection)
    { }
    void onError(AMQP::TcpConnection *connection, const char *message)
    { }
    void onClosed(AMQP::TcpConnection *connection) 
    { }
    virtual void monitor(AMQP::TcpConnection *connection, int fd, int flags)
    {
      fd_set rfds;
      FD_ZERO(&rfds);
      FD_SET(fd, &rfds);

   
     int queryFd = fcntrl(fd,F_GETFL); //always returns 0 for read only
    
      //check fd if readable
     int result = select(fd+1, &readset, NULL, NULL);  //the program sits here waiting...
  
    
    //if fd is readable, process readable flag on this fd
    if(FD_ISSET(fd, &readset))
    {
    connection->process(fd, AMQP::readable)
    }

    }
};

```

**Comment by EmielBruijntjes** [comment]
Your program does not have an event loop. The select() call should be in main() inside an endless loop, inside the monitor() method you only update the fd_set's with filedescriptors.

This, by the way, is not a school.

**Comment by SunDontShine** [comment]
okay thanks Emiel.
I know it is not a school Emiel, if this zip had basic examples that actually worked on the its latest release, basic questions wouldn't be asked.

**Comment by svyatogor** [comment]
> This, by the way, is not a school.

I came here with a very similar problem as a newbie C++ developer. But this comment made it super clear that I should be looking elsewhere. I understand that this is open source project and I appreciate you putting it online, but I don't think OpenSource community needs this kind of attitude.
