### ISSUE TITLE
 AMQP::LibBoostAsioHandler can process multiple TcpConnection?

### ISSUE THREAD

**Issue by lybest** [CopernicaMarketingSoftware/AMQP-CPP#251]
or every connection hava a unique handler?

**Comment by EmielBruijntjes** [comment]
I don't know about the libboost-asio-handler, maybe @zerodefect? 

Anyway, AMQP-CPP communicates with the handlers in such a way that it does not limit the handler to one specific connection. The implementation of the handlers for for example LibEv and LibEvent is also not limited to a single connection. 

However, in the applications that _I_ write on top of AMQP-CPP, I normally extend these Lib*Handlers further and override some extra methods (like `onError()`), and I always use in these applications one handler-instance per connection. It makes live easier.

**Comment by zerodefect** [comment]
The LibBoostAsioHandler behaves the same as the other handlers.
