### ISSUE TITLE
Build error while building with Clang 7 on Ubuntu 18.04

### ISSUE THREAD

**Issue by krzysztofwos** [CopernicaMarketingSoftware/AMQP-CPP#255]
I am trying to build AMQP-CPP with Clang 7 on Ubuntu 18.04 but unfortunately I am running into these sort of errors:

```
[  6%] Building CXX object CMakeFiles/amqpcpp.dir/src/array.cpp.o
In file included from /home/kwos/Work/third-party/AMQP-CPP/src/array.cpp:7:
In file included from /home/kwos/Work/third-party/AMQP-CPP/src/includes.h:57:
/home/kwos/Work/third-party/AMQP-CPP/include/amqpcpp/table.h:259:13: warning: conversion function converting 'AMQP::Table' to itself will never be used
    virtual operator const Table& () const override
```

Since I usually build my projects with `-Wall` and `-Werror`, this actually stops the build and unfortunately this warning cannot be disabled with a pragma.

Steps to reproduce:

```
git clone git@github.com:CopernicaMarketingSoftware/AMQP-CPP.git
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 ..
make -j
```

**Comment by EmielBruijntjes** [comment]
We are aware of this warning. It might be a compiler-bug: https://bugs.llvm.org/show_bug.cgi?id=28263. It is therefore recommended to not build with the -Werror compiler flag. If you know a way how we can solve it, your input is very welcome. But we want to keep the behavior of the library that AMQP::Table objects can be accessed using [] operators.
