### ISSUE TITLE
undefined reference to AMQP::Channel::Channel(AMQP::Connection*)

### ISSUE THREAD

**Issue by olegk0** [CopernicaMarketingSoftware/AMQP-CPP#267]
Hello.
When i try to build example libboostasio.cpp (for 4.0.0 )
i got  a error:  
```
libboostasio.o: In function `AMQP::TcpChannel::TcpChannel(AMQP::TcpConnection*)':
AMQP-CPP/examples/../include/amqpcpp/linux_tcp/tcpchannel.h:38: undefined reference to `AMQP::Channel::Channel(AMQP::Connection*)'
collect2: error: ld returned 1 exit status
```
With 3.2.0 the build was fine.

I compare the include/amqpcpp/channel.h file in both versions, and I see that the implementation of the Channel(Connection *connection) method is missing in the new version.

and I do not understand, this is a mistake or a planned changes?

**Comment by olegk0** [comment]
Sorry, I tried to use the last snapshot.
With release 4.0.0, everything is fine.

**Comment by cmbahadir** [comment]
Hello,

I faced with the same problem.

**Comment by EmielBruijntjes** [comment]
Sorry, I forgot to add a file in my latest commit.

**Comment by aarchetype** [comment]
> Sorry, I forgot to add a file in my latest commit.

Actually 4.0.1 is still broken because there is no channel.cpp in src/CMakeLists.txt.
#269 fixes this but #269 is not in release.

**Comment by aarchetype** [comment]
It seems you are affected by #127.
You can use master branch instead of release. Also you can take 4.0.1 and apply #269.

**Comment by vava24680** [comment]
@aarchetype Thanks for your answer. I will try. Thank You
