### ISSUE TITLE
Circular ownership problem

### ISSUE THREAD

**Issue by gary-jackson** [CopernicaMarketingSoftware/AMQP-CPP#276]
There is a problem with object lifetime and circular raw pointer ownership. To set this up:

1. A handler is created first by the owning program
2. A TcpConnection is created by the owning program -- the TcpConnection holds on to a raw pointer to the handler
3. At some point, the TcpConnection calls back through that raw pointer to the handler with a raw pointer to itself. The handler creates a Watcher of some sort, which holds on to that raw pointer back to the TcpConnection

The problem happens when:

1. The owning program destroys the TcpConnection
2. Some time after that, the Watcher fires off in another thread on the event loop, and tries to use the now-destroyed TcpConnection

We could try to destroy the handler first, but the TcpConnection's own callbacks may fire and refer to the destroyed handler.

There are a couple of different possible workarounds for this:

1. Quiesce thread activity before destroying the handler and the connection at the same time. This is the least invasive, but relies on having an event loop/thread pool that can be quiesced and restarted.
2. Instead of a raw pointer to the handler, hold on to a weak_ptr to the handler in the TcpConnection. If the handler is gone and can't be locked, TcpConnection callbacks become effectively no-ops. This is only slightly invasive, but it means we need to be careful to destroy the handler before the connection, which is counter-intuitive.
3. Hold on to a weak_ptr to the connection from the Watcher, instead of a raw pointer. This is probably the safest option of the three, but it means making invasive changes to all handler implementations.

I find this library to be very confusing overall. For example, the Watchable/Monitor idiom makes it seem like we're planning on being inside of a method while `this` is destroyed. Isn't that undefined behavior?

**Comment by EmielBruijntjes** [comment]
The objects are not thread safe. You should not destruct the tcpconnection if you're still using it in an other thread.
