### ISSUE TITLE
Frame error  type 3  

### ISSUE THREAD

**Issue by hemanthyatam** [CopernicaMarketingSoftware/AMQP-CPP#278]
hi ,
I am using amqpcpp with libev loop in  multi threaded application under Linux environment. It was running but after some time  getting error :   
onError called  : FRAME_ERROR - type 3, first 16 octets = <<2,0,40,0,0,0,14,0,60,0,0,0,0,0,0,0>>: {invalid_frame_end_marker,0}.please do needful.
RabbitMQ Vesion: 3.7.5 and erlang 20.3 , centos 7.2 .
I know channels  are not thread safe ,but i am using dedicated channel for each thread i hope this is not the cause for the frame error,please correct me if i am wrong .

Thanks in Advance.

**Comment by mvdwerve** [comment]
Are you also using a separate connection for each thread as well? Connections are also not threadsafe.

**Comment by hemanthyatam** [comment]
> Are you also using a separate connection for each thread as well? Connections are also not threadsafe.
   no i am not using, but dedicated connection for each thread is safe right.
>i need to know the reason for frame error ?

**Comment by EmielBruijntjes** [comment]
Do you honestly think that your input is sufficient to answer your question?

**Comment by hemanthyatam** [comment]
sorry for that. i am sharing the  example similar to  my application. the problem is when i am running this application in virtual machine , it's working fine but in production system it was throwing below error.

FRAME_ERROR - type 3, first 16 octets = <<2,0,40,0,0,0,14,0,60,0,0,0,0,0,0,0>>: {invalid_frame_end_marker,0} .

in rabbitmq.config frame max is 131072 [.](url)



#include <ev.h>
#include <amqpcpp.h>
#include <amqpcpp/libev.h>

#include<iostream>
#include<unistd.h>
#include<signal.h>
#include"UserStruct.h"
#include<thread>
#include <mutex>
#include<vector>
#include <sstream>
using namespace std; 

bool isbShutDown = false;

bool isbSignlaAlreadyRaised = false;


/************************************************************************************************/

class MyHandler : public AMQP::LibEvHandler
{

	protected:
	std::vector<AMQP::TcpConnection*>_pconnections;

	virtual void oncallback(  )
	{
		for( auto it = _pconnections.begin() ; it != _pconnections.end(); it++  )
		{
                        (*it)->close();
		}
	}

/*	      
                 //  disable heartbeats 
		  virtual uint16_t onNegotiate(TcpConnection *connection, uint16_t interval) override
		  {
	            // we agree with the interval
	             return 0;
	          }  

*/
	public:

	MyHandler(struct ev_loop *loop) : AMQP::LibEvHandler(loop) {     }
	virtual ~MyHandler() {}

	virtual void onConnected( AMQP::TcpConnection *connection  )
	{
		cout<<" onConnected in MyHandler\n";
		_pconnections.push_back( connection ) ;

	}


	virtual void onError(AMQP::TcpConnection* connection, const char *message) override
	{
		std::cout << "onError in MyHandler : " << message << std::endl;

		sleep(1);
		raise(SIGINT) ;

	}

	static void signal_handler(struct ev_loop *loop, ev_signal *w, int revents)
	{
		printf("Signal received: %d\n", revents );
		//sleep(2);
		auto * _hAndler = static_cast<MyHandler* > ( w->data );
		_hAndler->onclosed( );
		ev_signal_stop (loop, w);
	}

	virtual void onclosed( )
	{
		oncallback ( ) ;
	}

};


/***************************************************************************************************/

AMQP::TcpConnection *connection = NULL;
mutex m;

void *myThreadFun(void *vargp)
{

	auto *pchannel = static_cast< AMQP::TcpChannel*>(vargp);


	unsigned int iCount = 10000 ;


	// create a temporary queue
	pchannel->declareQueue("testq_devops" , AMQP::durable).onSuccess(
			[](const std::string &name, uint32_t messagecount, uint32_t consumercount)
			{
			std::cout << "declared queue " << name << std::endl;
			}	
			);

	// declare an exchange
	pchannel->declareExchange("my_exchange", AMQP::direct , AMQP::durable).onSuccess(
			[]()
			{ 
			std::cout << "exchange declared" << std::endl; 
			}
			);


	// bind queue and exchange
	pchannel->bindQueue("my_exchange", "testq_devops", "testq_devops").onSuccess(
			[]()
			{
			std::cout << "queue bound to exchange" << std::endl;
			}
			);


	// install a handler when channel is in error
	pchannel->onError(
			[ &pchannel ](const char *message)
			{
			std::cout << "channel error " << message << std::endl;
			pchannel->close();
			}
			);




	// install a handler when channel is ready
	pchannel->onReady(
			[&pchannel , iCount ]()
			{                              
			std::cout << "channel ready" << std::endl;
                        

			QueryStruct ST; /* consider this structure size 464 bytes */
			memset( (char*)&ST , 0x00 , sizeof( QueryStruct )  );
			ST.sTransaction.mcu64_MessageId = 123456789;
			unsigned int ic = 0; 
			int ibatchcnt = 0;

			while( !isbShutDown && ( ic < iCount ) )
			{
				ibatchcnt++;
				if( !isbShutDown )  
				{
					pchannel->publish("my_exchange", "testq_devops", (char*)&ST , sizeof(QueryStruct )   ) ;  
					ic ++ ;
				}
				else
				{
					cout<<"  SHUT DOWn FLAG TRUE ....." <<endl;
				}
				if(ic %30000 == 0)
					sleep(1);
			}



			});

	while(!isbShutDown) sleep(1)  ;

	pchannel->close(); 
	cout<<" thread exiting...."<<endl;

}



void *myThreadFun_c(void *vargp)
{

	   auto *pchannel = static_cast< AMQP::TcpChannel*>(vargp);

           m.lock();
            auto  *pch = new AMQP::TcpChannel ( connection );  /* this channel is for publish */
           m.unlock();  


	unsigned int iCount = 10000 ;


     /********************************************************/

        pch->declareQueue("testq_" , AMQP::durable).onSuccess(
                        [](const std::string &name, uint32_t messagecount, uint32_t consumercount)
                        {
                        std::cout << "declared queue " << name << std::endl;
                        }
                        );
	// bind queue and exchange
        pch->bindQueue("my_exchange", "testq_", "testq_").onSuccess(
                        []()
                        {
                        std::cout << "queue bound to exchange" << std::endl;
                        }
                        );

      /********************************************************/   


	// create a  queue
	pchannel->declareQueue("testq_devops" , AMQP::durable).onSuccess(
			[](const std::string &name, uint32_t messagecount, uint32_t consumercount)
			{
			std::cout << "declared queue " << name << std::endl;
			}	
			);

	// declare an exchange
	pchannel->declareExchange("my_exchange", AMQP::direct , AMQP::durable).onSuccess(
			[]()
			{ 
			std::cout << "exchange declared" << std::endl; 
			}
			);


	// bind queue and exchange
	pchannel->bindQueue("my_exchange", "testq_devops", "testq_devops").onSuccess(
			[]()
			{
			std::cout << "queue bound to exchange" << std::endl;
			}
			);


	// install a handler when channel is in error
	pchannel->onError(
			[ &pchannel ](const char *message)
			{
			std::cout << "=============>channel error  " << message << std::endl;
			pchannel->close();
			return ;
			}
			);

	// install a handler when channel is ready
	pchannel->onReady(
			[&pchannel , iCount ,&pch ]()
			{                              
			std::cout << "channel ready" << std::endl;
                        
			//	 ************************************************************************************************************************   
			// 	 start consuming ................................................

			time_t s = time(0);
			long int j = 0 ;

			pchannel->setQos(1000);	

			auto startCb = [](const std::string &consumertag)
			{

			std::cout << "consume operation started : "<<consumertag  << std::endl;
			};
			auto errorCb = [](const char *message) 
			{

				std::cout << "consume operation failed" << std::endl;
			};

			auto messageCb = [pchannel , j ,&pch ](const AMQP::Message &message, uint64_t deliveryTag, bool redelivered)
			{
				// std::cout << "message received:" <<j <<std::endl;

				/* manipulate  consumed message and do so business logic then publish
                                     .....
                                     .....
                                 */
                                   
	      	                pch->publish("my_exchange", "testq_", "9198xxxxxx84" ) ; /* this publish is the application requirement*/
                       	
                         	pchannel->ack(deliveryTag);
                                
			};


			pchannel->consume("testq_devops" ).onReceived(messageCb).onSuccess(startCb).onError(errorCb);
                       });
			


	while(!isbShutDown ) sleep(1)  ;  

	cout<<" consumer thread exiting ...."<<endl;

}



void handle_sigint(int sig)
{

	printf("Caught signal %d\n", sig);
	if( isbSignlaAlreadyRaised )
	{
		cout<<  " ***********  Signal Already Raised Wait For Exit ******************\n ";
		return;

	} 


	if( sig == SIGUSR1 )
	{
		cout<< " sig usr raised " << endl;
		signal(sig , SIG_IGN); //ignore the signal...
		return;
	}

	raise(SIGUSR1);
	sleep(1);
	isbShutDown = true ;
	isbSignlaAlreadyRaised = true ; 



}


int main(int argc, char** argv)
{

	auto *loop = EV_DEFAULT;


	int iThreadCount = 5;

	if( argc >= 2 )
	{
		iThreadCount = atoi( argv[1] );
	}


	MyHandler handler(loop);

	signal(SIGINT, handle_sigint);

	ev_signal exitsig  ;
	exitsig.data = &handler;    

	ev_signal_init (&exitsig, MyHandler::signal_handler, SIGUSR1);
	ev_signal_start (loop, &exitsig  );

        connection = new AMQP::TcpConnection( &handler ,  AMQP::Address("amqp://username:password@hostip//vhost")   )  ;


	pthread_t thread_id[iThreadCount];

      /************* publishing threads ***************/   

	for(int i=0;i<iThreadCount;i++)
	{
		try
		{ 
			auto *pchannel =  new AMQP::TcpChannel(connection);


			if( !(pchannel->connected() ) )
			{
				cout<<" Max channels exceed \n";
				return -1;
			} 



			pthread_create(&thread_id[i] , NULL, myThreadFun , pchannel);
			sleep(0.1);
		}
		catch( ...  )
		{
			cout<< " channels capacity exceeded \n";
			return -1;
		}
	}
     /********************************************************/  

     /******************** consumer threads **************************/
		pthread_t thread_id_c[iThreadCount];
		for(int i=0;i<iThreadCount;i++)
		{ 
			auto *pchannel =  new AMQP::TcpChannel(connection);
			pthread_create(&thread_id_c[i] , NULL, myThreadFun_c , pchannel);
			sleep(0.1);

		}
		
	/****************************************************************/

        sleep(1);
	ev_run(loop, 0);
	cout<< "after run "<<endl;

	for(int i=0;i<iThreadCount;i++)
	{
		pthread_join(thread_id[i] , NULL);
		cout<<"Publish Threads Are Joined ...." <<endl;

	}

	/***************************** consumers join **********************/
		for(int i=0;i<iThreadCount;i++)
		{
		pthread_join(thread_id_c[i] , NULL);
		cout<<"Consume Threads Are Joined ...." <<endl;

		}
		
	/******************************************************************/

	ev_loop_destroy ( loop  );	
        delete connection;
 	return 0;
}

**Comment by EmielBruijntjes** [comment]
Explain why you say that you're not sharing connections between threads.

**Comment by hemanthyatam** [comment]
i thought connection sharing  means , one connection  accessing  by all threads without any locking .
but in my case i am creating channel objects  and assigning one channel object per each thread.
