### ISSUE TITLE
Event loop on Windows

### ISSUE THREAD

**Issue by cppjocker** [CopernicaMarketingSoftware/AMQP-CPP#282]
How could I implement event loops approach on Windows platform ? I loooked at all Boost asio, libev, libevent, libuv libraries, but it seems that all of them dependent from TcpConnection from Linux headers and Linux system code? 

So is there some relatively easy way to implement event-loop on Windows or I have to do all things manually from the beginning?

**Comment by EmielBruijntjes** [comment]
I have no idea, we do not use windows ourselves.

**Comment by cppjocker** [comment]
if you don't care about how to develop applications on Windows then just switch off Windows supporting, don't confuse peoples. Or explain clearly what of your features work on Windows and what are not.  I would save much time if I would choose another AMQP c++ library from the beginning
