### ISSUE TITLE
Recieved "connection lost" error in the libevent mode

### ISSUE THREAD

**Issue by HibirdC** [CopernicaMarketingSoftware/AMQP-CPP#284]
Hi guys,

Recieved "connection lost" error in the libevent mode.
Info:
LibEventHandlerMyError::onError (this=0x7faf88ff0930, connection=0x7faf88ff0980, message=0x7faf9647851e "connection lost") 

Repro:
1. Env: Centos 7, AMQP-CPP-4.1.3
2. Init connection ,declare the queue , and it work well ,but waiting about 5 mins(3-5 heartbeat packet), onError recieved the error
3. if disable the heatbeat, need waiting more long time , it also repoet the error .

**Comment by HibirdC** [comment]
any idea?

**Comment by hoxnox** [comment]
I've resolved by making heartbeats - calling connection.heartbeat() every ~30sec in spite of existent amqp activity.

**Comment by EmielBruijntjes** [comment]
We have solved this in the libev handler. The libevent class still needs to be updated (pull request, anyone?) The reason of this issue is that different rabbitmq versions treat the heartbeat interval differently. Some versions treat it as a heartbeat interval, while others treat it as a heartbeat timeout (meaning that you have to send a heartbeat every half interval).

**Comment by EmielBruijntjes** [comment]
Yes.

**Comment by dronord** [comment]
Q!

Try
```
virtual void MyHandler::onHeartbeat(AMQP::TcpConnection * connection) override {
    connection->heartbeat();
}
```
Checked on LibBoostAsioHandler.

ConnectionHandler::onHeartbeat() has comment
     *  You do not have to do anything here, the **client sends back a heartbeat**
     *  **frame automatically**, but if you like, you can implement/override this
     *  method if you want to be notified of such heartbeats
it's does not work. After three server's heartbeat we get connection lost.

@EmielBruijntjes, Heartbeat frames are sent about every heartbeat timeout / 2 seconds. This value is sometimes referred to as the heartbeat interval. (c) https://www.rabbitmq.com/heartbeats.html#heartbeats-interval

**Comment by dronord** [comment]
```
virtual void MyHandler::onHeartbeat(AMQP::TcpConnection * connection) override {
    connection->heartbeat();
}
```
Today no disconnects. Interval = 60s, 30s.
Handler is boost asio.

RabbitMQ 3.8.2, AMQP-CPP 4.1.7

**Comment by imi187** [comment]
```

#include <event2/event.h>
#include <amqpcpp.h>
#include <amqpcpp/libevent.h>
#include <amqpcpp/openssl.h>
#include <amqpcpp/linux_tcp.h>

class RabbitMqHandler : public AMQP::LibEventHandler
{
public:
    RabbitMqHandler(struct event_base* evbase) : LibEventHandler(evbase), evbase_(evbase_) {}

    virtual void onHeartbeat(AMQP::TcpConnection *connection) {
        connection->heartbeat();
    }

private:
    struct event_base* evbase_ {nullptr};
};

```


With & without `connection->heartbeat();`

![heartbeat](https://user-images.githubusercontent.com/2426634/105736237-df0c5e80-5f34-11eb-888e-1a0c435ad540.png)

**Comment by EmielBruijntjes** [comment]
The libevent example handler is not maintained by us, if it is an error in this handler, you will have to fix this yourself.

**Comment by imi187** [comment]
Indeed.
There is no bug... you have to implement the heartbeat and everything works fine. (which is normal I think)
In my opinion you can close the issue...
