### ISSUE TITLE
websocketpp and amqp-cpp

### ISSUE THREAD

**Issue by jm130794** [CopernicaMarketingSoftware/AMQP-CPP#286]
Hello,

I want to write a websocket server (based on websocketpp) that can publish and consume AMQP messages. 
My question may be stupid but is it possible to use amqp-cpp and websocketpp together? 

Jean-Marc

**Comment by EmielBruijntjes** [comment]
How could I know? AMQP-CPP was designed to be flexible, so from this perspective it is possible.
