### ISSUE TITLE
Error :Invalid read of size 8

### ISSUE THREAD

**Issue by zhjphp** [CopernicaMarketingSoftware/AMQP-CPP#292]
`

    #include <event2/event.h>
    #include <amqpcpp.h>
    #include <amqpcpp/libevent.h>

    int main(int argc, char **argv)
    {
        struct event_base *evbase = event_base_new();
        AMQP::LibEventHandler handler(evbase);
        AMQP::TcpConnection connection(&handler,AMQP::Address("amqp://admin:admin@localhost /"));   // error at here
    }

`

use valgrind test the code ,at AMQP::TcpConnection some error :

==21838== Invalid read of size 8
==21838==    at 0x573EA61: ??? (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6.0.2)
==21838==    by 0x11FFFD: ~Watcher (libevent.h:99)
==21838==    by 0x11FFFD: ~Watcher (libevent.h:102)
==21838==    by 0x11FFFD: operator() (unique_ptr.h:78)
==21838==    by 0x11FFFD: ~unique_ptr (unique_ptr.h:268)
==21838==    by 0x11FFFD: ~pair (stl_pair.h:198)
==21838==    by 0x11FFFD: destroy<std::pair<int const, std::unique_ptr<AMQP::LibEventHandler::Watcher> > > (new_allocator.h:140)
==21838==    by 0x11FFFD: destroy<std::pair<int const, std::unique_ptr<AMQP::LibEventHandler::Watcher> > > (alloc_traits.h:487)
==21838==    by 0x11FFFD: _M_destroy_node (stl_tree.h:650)
==21838==    by 0x11FFFD: _M_drop_node (stl_tree.h:658)
==21838==    by 0x11FFFD: _M_erase_aux (stl_tree.h:2477)
==21838==    by 0x11FFFD: erase (stl_tree.h:1125)
==21838==    by 0x11FFFD: erase (stl_map.h:1032)
==21838==    by 0x11FFFD: AMQP::LibEventHandler::monitor(AMQP::TcpConnection*, int, int) (libevent.h:166)
==21838==    by 0x5E395F3: onIdle (tcpconnection.h:163)
==21838==    by 0x5E395F3: cleanup (tcpextstate.h:41)
==21838==    by 0x5E395F3: ~TcpExtState (tcpextstate.h:88)
==21838==    by 0x5E395F3: ~TcpConnected (tcpconnected.h:114)
==21838==    by 0x5E395F3: AMQP::TcpConnected::~TcpConnected() (tcpconnected.h:114)
==21838==    by 0x5E34A7E: operator() (unique_ptr.h:78)
==21838==    by 0x5E34A7E: ~unique_ptr (unique_ptr.h:268)
==21838==    by 0x5E34A7E: AMQP::TcpConnection::~TcpConnection() (tcpconnection.h:30)
==21838==    by 0x114246: main (main.cpp:172)
==21838==  Address 0xc109f70 is 432 bytes inside a block of size 664 free'd
==21838==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21838==    by 0x114227: main (main.cpp:249)
==21838==  Block was alloc'd at
==21838==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21838==    by 0x5743379: event_base_new_with_config (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6.0.2)
==21838==    by 0x57437FA: event_base_new (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6.0.2)
==21838==    by 0x1139E8: main (main.cpp:166)
==21838== 
==21838== Invalid read of size 8
==21838==    at 0x573E640: event_del_nolock_ (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6.0.2)
==21838==    by 0x573EA85: ??? (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6.0.2)
==21838==    by 0x11FFFD: ~Watcher (libevent.h:99)
==21838==    by 0x11FFFD: ~Watcher (libevent.h:102)
==21838==    by 0x11FFFD: operator() (unique_ptr.h:78)
==21838==    by 0x11FFFD: ~unique_ptr (unique_ptr.h:268)
==21838==    by 0x11FFFD: ~pair (stl_pair.h:198)
==21838==    by 0x11FFFD: destroy<std::pair<int const, std::unique_ptr<AMQP::LibEventHandler::Watcher> > > (new_allocator.h:140)
==21838==    by 0x11FFFD: destroy<std::pair<int const, std::unique_ptr<AMQP::LibEventHandler::Watcher> > > (alloc_traits.h:487)
==21838==    by 0x11FFFD: _M_destroy_node (stl_tree.h:650)
==21838==    by 0x11FFFD: _M_drop_node (stl_tree.h:658)
==21838==    by 0x11FFFD: _M_erase_aux (stl_tree.h:2477)
==21838==    by 0x11FFFD: erase (stl_tree.h:1125)
==21838==    by 0x11FFFD: erase (stl_map.h:1032)
==21838==    by 0x11FFFD: AMQP::LibEventHandler::monitor(AMQP::TcpConnection*, int, int) (libevent.h:166)
==21838==    by 0x5E395F3: onIdle (tcpconnection.h:163)
==21838==    by 0x5E395F3: cleanup (tcpextstate.h:41)
==21838==    by 0x5E395F3: ~TcpExtState (tcpextstate.h:88)
==21838==    by 0x5E395F3: ~TcpConnected (tcpconnected.h:114)
==21838==    by 0x5E395F3: AMQP::TcpConnected::~TcpConnected() (tcpconnected.h:114)
==21838==    by 0x5E34A7E: operator() (unique_ptr.h:78)
==21838==    by 0x5E34A7E: ~unique_ptr (unique_ptr.h:268)
==21838==    by 0x5E34A7E: AMQP::TcpConnection::~TcpConnection() (tcpconnection.h:30)
==21838==    by 0x114246: main (main.cpp:172)
==21838==  Address 0xc109f70 is 432 bytes inside a block of size 664 free'd
==21838==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21838==    by 0x114227: main (main.cpp:249)
==21838==  Block was alloc'd at
==21838==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21838==    by 0x5743379: event_base_new_with_config (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6.0.2)
==21838==    by 0x57437FA: event_base_new (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6.0.2)
==21838==    by 0x1139E8: main (main.cpp:166)  

is Bug?

**Comment by EmielBruijntjes** [comment]
Possibly, can you try to fix it and send a pull request? We do not use libevent in our organization, so it is low-priority work for us.

**Comment by EmielBruijntjes** [comment]
Closing this issue as no further input was received.
