### ISSUE TITLE
What is the most idiomatic way to close connection?

### ISSUE THREAD

**Issue by thekvs** [CopernicaMarketingSoftware/AMQP-CPP#293]
Hi!

What is the most idiomatic way to cleanly close connection without resorting to `sleep()` function after calling `connection.close()`? Without a `sleep()` I see RabbitMQ logs entries like `client unexpectedly closed TCP connection`, but using `sleep()` function looks like a very hackish way of doing things.

**Comment by EmielBruijntjes** [comment]
The connection.close() method starts a nice AMQP handshake to close down the connection. You can not immediately destruct the object after this call. Let the event loop run for a while, until your own overridden ConnectionHandler is notified (for example via ConnectionHandler::onClosed()) that the handshake has been completed.
