### ISSUE TITLE
Install on windows does not work properly

### ISSUE THREAD

**Issue by pseudonym117** [CopernicaMarketingSoftware/AMQP-CPP#30]
When installing the project through Visual Studio solution files on Windows, the INSTALL project does not copy the required header files to the install directory. The lib file is installs correctly, the include files just are not placed anywhere.

**Comment by heatonmatthew** [comment]
I'm building using Visual Studio 2013 and found that I need to:
* Remove the constexpr from stringfield.h
* Add #define NOMINMAX to includes.h
* Add #include<functional> to includes.h

Did you find the same issues?  I wouldn't mind submitting a patch for this and contribute to the project.
What's the project's philosophy towards these cross-compiler issues?

**Comment by pseudonym117** [comment]
Actually yes, I did find these. Specifically I needed to include
functional. I didn't remove constexpr as I am using the Intel compiler with
visual studio, but that issue was there.

I think with the VS2015 the constexpr issue will not be there, though in
the mean time it could be defined to be nothing and no code would need to
change.

BUT, these seem like separate issues from the install, so I did not include
them in this issue.

**Comment by EmielBruijntjes** [comment]
The projects philosophy: we (the Copernica team) developed AMQP-CPP, and only use it on Linux platforms, and we have no intention to start testing everything for Windows environments. In fact, we do not even have Windows computers here. 

But if we receive pull requests for Windows that seem to make sense, and that do not break our Linux build, we normally accept them.

**Comment by heatonmatthew** [comment]
Thanks.
