### ISSUE TITLE
FreeBSD: use of undeclared identifier 'IPPROTO_TCP'

### ISSUE THREAD

**Issue by yellowpint** [CopernicaMarketingSoftware/AMQP-CPP#300]
I had a problems in compiling with `clang` under FreeBSD on that [line](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/5a648fe2d8df7dacc389fdc83be5d35e616a06c1/src/linux_tcp/tcpresolver.h#L127):
```
/home/httpd/AMQP-CPP/src/linux_tcp/tcpresolver.h:127:37: error: use of undeclared identifier 'IPPROTO_TCP'
                setsockopt(_socket, IPPROTO_TCP, TCP_NODELAY, &optval, sizeof(int));
```
I solved it when include `<netinet/in.h>` in this file. And after that all works great.

**Comment by rversteegen** [comment]
(Driveby comment from a web search) Can confirm that this is the correct fix for this (had the same problem for a different project on FreeBSD); IPPROTO_TCP is defined in netinet/in.h by the POSIX standard.
