### ISSUE TITLE
Can't send message to Rabbitmq

### ISSUE THREAD

**Issue by kothemel** [CopernicaMarketingSoftware/AMQP-CPP#307]
Hello everyone,

I'm trying to make a simple console application on windows. I have installed AMQP-CPP  and included the library on my Visual Studio project. My task is to create the simple communication with the rabbitmq server. The main function is:
```
#include <amqpcpp.h>
#include "rabbitmqModels.h"

int main(){

    string msg = "hello world";
    string queueName = "message_queue";
    string exchangeName = "myexchange";
    string routingKey = "hello";
    
    Address address("amqp://guest:guest@localhost:15672");
    MyConnectionHandler myHandler;
    Connection connection(&myHandler, address);
    Channel channel(&connection);

    channel.declareQueue(queueName);
    channel.declareExchange(exchangeName, direct).onSuccess([]();
    channel.bindQueue(exchangeName, queueName, routingKey);
    channel.publish(exchangeName, routingKey, msg, msg.size());

    return 0;
}
```

where rabbitmqModels.h code is:

```
using namespace AMQP;
class MyConnectionHandler : public ConnectionHandler
{
private:
	/**
	 *  Method that is called by the AMQP library every time it has data
	 *  available that should be sent to RabbitMQ.
	 *  @param  connection  pointer to the main connection object
	 *  @param  data        memory buffer with the data that should be sent to RabbitMQ
	 *  @param  size        size of the buffer
	 */
	virtual void onData(Connection* connection, const char* data, size_t size)
	{
		// @todo
		//  Add your own implementation, for example by doing a call to the
		//  send() system call. But be aware that the send() call may not
		//  send all data at once, so you also need to take care of buffering
		//  the bytes that could not immediately be sent, and try to send
		//  them again when the socket becomes writable again
	}

	virtual void onReady(Connection* connection) override
	{
		// @todo
		//  add your own implementation, for example by creating a channel
		//  instance, and start publishing or consuming
		std::cout << "Connection is established...\n";

	}

	virtual void onError(Connection* connection, const char* message)
	{
		// report error
		std::cout << "Connection Error: " << message << std::endl;
	}

	virtual void onClosed(Connection* connection)
	{
		std::cout << "closed" << std::endl;

	}

	virtual void onConnected(Connection* connection)
	{
		std::cout << "connected" << std::endl;
	}
};
```

The code builds without errors. Note that my rabbitmq server runs on localhost:5672 and I have defined both the queue and the exchange/routing key.

The thing is that I cannot see any message coming to my defined queue.  Do I have to use only TCPHandler? I can't find any implementation of TCPHandler for windows.
Can you please tell me why?
Thanks in advance

**Comment by RZRCDR** [comment]
Hi there,

This question is not that new but I thought I'd still answer it.

If I understand it correctly the use case by the original library developer is for a UNIX/Linux environment.
There is no out of the box TCP handler implementation for windows provided with the library.

With that in mind, you can with little effort implement your own TCP handler, inheriting from ConnectionHandler.
It is up to you which networking library/event loop you want to use.

If you are interested, I don't mind sharing some knowledge and examples of my own with you.

Cheers

**Comment by EmielBruijntjes** [comment]
The above answer is correct. In your MyConnectionHandler you still have a lot of empty functions that you must implement to set up the connection to the RabbitMQ server.

**Comment by mavisakal** [comment]
Hi @EmielBruijntjes ,
Do you have an example MyConnectionHandler for Windows. 
Thanks

**Comment by EmielBruijntjes** [comment]
No, I'm sorry
