### ISSUE TITLE
Publish immediate flag is not supported

### ISSUE THREAD

**Issue by LadMartin** [CopernicaMarketingSoftware/AMQP-CPP#311]
Hi, when I tried to use immediate flag when calling publish I got a connection error that "NOT_IMPLEMENTED immediate=true", but in the documentation for the function it's stated that it's a supported flag? Can you please clarify the status? 
Thank you

**Comment by EmielBruijntjes** [comment]
The flag _is_ implemented by the AMQP-CPP library. However, the RabbitMQ server on the other end of the connection has not implemented it, and sends back this error message. The NOT_IMPLEMENTED code does not come from AMQP-CPP, but from the RabbitMQ server.

**Comment by LadMartin** [comment]
I see, thank you for the explanation
