### ISSUE TITLE
LibBoostAsio does not work with modern boost versions

### ISSUE THREAD

**Issue by arnoudvanleeuwen** [CopernicaMarketingSoftware/AMQP-CPP#315]
When trying to build  the amqp-cpp test in the examples (I am new to this library) using boost 1.66.0 i get include errors on boost::asio::posix (namespace not recognized). After fixing by defining BOOST_ASIO_ENABLE_OLD_SERVICES in the preprocessor definitions subsequent files are causing compilation issues. Is it possible to implement a newer version of Boost?

**Comment by EmielBruijntjes** [comment]
Yes, I suppose that it would indeed be helpful if you took that effort.
