### ISSUE TITLE
Is there a way to know if the connection is in bloked state ?

### ISSUE THREAD

**Issue by TonyRoussel** [CopernicaMarketingSoftware/AMQP-CPP#316]
[RabbitMQ added an extension to amqp protocol](https://www.rabbitmq.com/connection-blocked.html) to know when the broker may throttle publish. Does AMQP-CPP provide a way to use this extension ? If not, is there an alternative ?

_Context: One of my service run low on ram and become unresponsive when too much of its publish call goes into "CopiedBuffer", which seem to buffer messages until the broker has more resources to receive new messages_

**Comment by EmielBruijntjes** [comment]
No, we have not yet implemented this feature. But if you need it, you can send in a pull request for it.
