### ISSUE TITLE
Why does libev need heartbeat and libuv and libevent do not

### ISSUE THREAD

**Issue by magengbin** [CopernicaMarketingSoftware/AMQP-CPP#317]

**Comment by EmielBruijntjes** [comment]
In the AMQP protocol heartbeats are optional: you can decide for yourself whether you want to use them or not. Although AMQP-CPP is event-loop-agnostic, we already built a couple of integrations as an example. One of them is for libev, others are for libuv and libevent.

For the libevent and libuv integrations we decided to keep it simple, and skip the heartbeat implementation. For libev we challenged ourselves a little more. In the end it comes down to laziness why we kept the libuv and libevent integrations simpler.

You can send in a pull request if you have improved this.
