### ISSUE TITLE
why does Envelope move constructor/assignment copy the data if it was constructed with pointer?

### ISSUE THREAD

**Issue by bman654** [CopernicaMarketingSoftware/AMQP-CPP#32]
Why doesn't it just move the `_data` pointer over and let `_str` be empty so that the new version has exactly the same data pointers as the old version (and old version gets `_data` set to nullptr of course?

The way it is coded, don't you end up making a copy of the data every single time you *move* a message (which I think happens everytime you call the message callback on receive?)

**Comment by martijnotto** [comment]
The reason for this is simple: If you move the Envelope somewhere else (to keep it) the buffer could be overwritten, invalidating the pointer, resulting in - at best - strange behaviour (wrong data) or segfaults (if it reads a weird string length). The envelope does not manage the pointer and thus cannot guarantee it stays valid.

You are right that if you move the message you get in the callback, a data copy is made. This is unavoidable. However, if you don't actually move the item nothing gets copied, It is still a reference after all. And if you move the envelope multiple times, only a single copy is made.

**Comment by bman654** [comment]
I see. Unfortunately doesn't the library •move• the envelope (and thus copy the data) when calling the receive callback before client code ever sees the envelope?

--
Brandon

**Comment by martijnotto** [comment]
I don't see that happening anywhere. Perhaps I am overlooking it. If you see a specific place where the library moves the Envelope, please tell me exactly where, because this should indeed *not* happen.

**Comment by bman654** [comment]
Ok I think I was misreading.  Thanks for the clarification and the library.
