### ISSUE TITLE
Deferreds are not removed when pushed to closed channel

### ISSUE THREAD

**Issue by LadMartin** [CopernicaMarketingSoftware/AMQP-CPP#325]
@EmielBruijntjes Thank you for the fix,
I was wondering one more thing, if you notice my log, then there is a destruction of object A(5) and A(6) after the last interrupt which means that the 5 a 6 also got stuck somewhere, I realize that this is quite stupid use case when I am pushing stuff to a closed channel, but maybe still it's worth looking.

error Frame could not be sentdestructor A: 5
destructor A: -1
action is end: 5
^Caction begin: 6
constructed A: 6
move constructor A: 6
copy constructor A: 6
error Frame could not be sentdestructor A: 6
destructor A: -1
action is end: 6
^C**destructor A: 6**
**destructor A: 5**
destructor A: 1

_Originally posted by @LadMartin in https://github.com/CopernicaMarketingSoftware/AMQP-CPP/issues/323#issuecomment-592508339_

**Comment by EmielBruijntjes** [comment]
I would say: after a channel is closed it is up to the caller to ensure that no further methods are called. It would be a little odd to add all sort of precautionary checks to the class just in case the caller decides to misuse the channel object.
