### ISSUE TITLE
Calling AMQP::Connection::fail() causes exception.

### ISSUE THREAD

**Issue by scobei** [CopernicaMarketingSoftware/AMQP-CPP#326]
With single channel, fail() is called, causing the channel to be removed from the channels container. Upon removal, the channel is destroyed before the connection member is set to nullptr, triggering another attempt to remove it from the container.

Creating a pull request seemed like overkill, and although this is not tested, I believe changing this:
```
 if (_connection) _connection->remove(this);
 _connection = nullptr;
```

To this:
```
	if (_connection)
		{
		auto cx = _connection;
		_connection = nullptr;
		cx->remove(this);
		}
```
will take care of the problem.

**Comment by EmielBruijntjes** [comment]
I don't understand what you mean. Do you have a minimal example program that triggers this issue?

**Comment by EmielBruijntjes** [comment]
I've committed a fix, can you check whether you think that this fixes the issue too?

**Comment by scobei** [comment]
That should do it.
