### ISSUE TITLE
Building on MacOS 10.10 asks about `-soname`

### ISSUE THREAD

**Issue by automata** [CopernicaMarketingSoftware/AMQP-CPP#33]
I was getting this compilation error while building some code that depends on AMQP-CPP:

```
ld: unknown option: -soname
```

Thanks to this [reference](http://stackoverflow.com/a/8424297) I changed `-soname` in https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/master/src/Makefile#L26 to `-install_name` and it worked.

Probably that's an useful suggestion for anyone trying to build on the same environment.

**Comment by martijnotto** [comment]
I have committed a fix in commit b6c88febbd5c7037721edc31b1761712a8396482 . This should automatically use the different parameter when compiling under OS X. Since I don't have an OS X machine here, I was not able to actually test it.

Can you confirm whether it works?
