### ISSUE TITLE
Several access to the same bus

### ISSUE THREAD

**Issue by Kawabaumga** [CopernicaMarketingSoftware/AMQP-CPP#334]
Hi,

I need to declare and consume at least to queues from the same bus rabbitmq. I try to stay as simple as possible by using only ONE connection with 2 TcpChannels but with some loads, my both channels get the same error message "FRAME_ERROR - type 3, first 16 octets = <<\"{\\n\\\"actionCode\\\" :\">>: {invalid_frame_end_marker,
                                                     1}". 

Before showing my code, I would like to know if you have some recommandation about how to use your AMQP TcpConnection and LibEvHandler when you need to have several access to the same bus? and how to handle bus disconnection/reconnection?

Yours sincerely,
Julien BAUMGARTEN

**Comment by EmielBruijntjes** [comment]
What do you mean by "bus"? Declaring, publishing and consuming all over the same connection is possible, you can use multiple channels, but also a single channel, it very much depends on your application what suits you best.

**Comment by Kawabaumga** [comment]
Sorry if I wasn’t clear.
My application est a telecom application which uses a thread to handle
telecom events. We need to connect it to a « bus » rabbitmq to send the
events and process it by a third party application.
Currently, I have one thread to handle network/rabbitmq events, one thread
for telecom events and one thread for boost deadline_timer. The three
threads may send data to the rabbit as :
1) rabbit events may process telecom actions (such as play a file, ...) and
send back the result
2) telecom events may rised asynchronously (such as new call, end of call,
...)
3) a deadline_timer is used to send data to a third application as a
keepalive

The first implementation was with one connection per queue to consume, one
channel for incoming data and one channel for outgoing data. It worked
pretty well but it was a nightmare to handle disconnection/reconnection
The second implementation is with one connection for several queue to
consume but one channel per queue to consume and one channel for outgoing
data. It works quite well but under heavy load, I have some « end marker »
error.

I hope i was clear :)

Le dimanche 31 mai 2020, Emiel Bruijntjes <notifications@github.com> a
écrit :

**Comment by EmielBruijntjes** [comment]
Should not be a problem.

Of course, the connection and channel objects are not thread safe. If you start calling methods from multiple threads at the same time, the data on the underlying tcp connection might also be split up in random, unrecognizable, chunks. So if you do use multiple threads to access one connection, you need to locking or thread synchronization to prevent this..

**Comment by Kawabaumga** [comment]
I’m using mutex before sending message but is there a particular way to
protect the read as I’m using your libEvhandler or a method to know when
the connect is free to use because the read function is terminated?

**Comment by EmielBruijntjes** [comment]
The connection is never free to be called from a different thread. It can at any time be active with handshakes, retransmissions, heartbeats, and so on. If you want to send data to it from a different thread, you should first make sure that you pass that data to the same thread in which the connection is running, and then call the appropriate method on the connection or channel object.

In libev the async-watcher can be useful for this. See 
http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#code_ev_async_code_how_to_wake_up_an

**Comment by Kawabaumga** [comment]
Thank you. You helped me to improve my source code

Le lun. 1 juin 2020 à 11:14, Emiel Bruijntjes <notifications@github.com> a
écrit :
