### ISSUE TITLE
Does AMQP-CPP support polling?

### ISSUE THREAD

**Issue by drewcm** [CopernicaMarketingSoftware/AMQP-CPP#339]
I'm trying to integrate AMQP-CPP into an existing legacy C++ project that maintains its own event loop.  My understanding is that AMQP 0-9-1 supports synchronous polling [0] using ```basic.get``` (I could be misunderstanding the protocol though).  Does AMQP-CPP support polling queues directly?  I have searched extensively and have been unable to find example code using this.

Thanks!

[0] https://www.rabbitmq.com/amqp-0-9-1-quickref.html#basic.get

**Comment by EmielBruijntjes** [comment]
Nothing is synchronous in network programming. You send an instruction to a remote-server, you wait for a (for computers) huge amount of time, and then you receive the answer. During this waittime you can (and _should_) do something else.

The normal way for reading messages from RabbitMQ is that you send a _consume_ instruction to rabbit, which basically means that you say: "hey rabbit, whenever you have one or more messages in that queue, can you immediately pass them on to me, I'm ready." After which Rabbit starts sending messages (or not, if the queue is empty) until you tell Rabbit to stop doing that.

The alternative way to receive message is to use the _get_ instruction. This essentially means that you say: "hey rabbit, can you send me _one_ message from the queue, or, if the queue happens to be empty, send me an queue-is-empty message instead." After that, you receive an answer (either a message or the queue-is-empty message), and you're done. You do not have to tell rabbit to stop sending messages.

Both operations (_consume_ and _get_) are supported by AMQP-CPP, but both operations are implemented in an asynchronous way using an event loop to allow your code to do other things while AMQP-CPP is waiting for RabbitMQ to receive and process the instruction, and send back the response.
