### ISSUE TITLE
Accessing RabbitmqServer on windows remote machine from amqpcpp client which is in linux machine

### ISSUE THREAD

**Issue by tapasgaan** [CopernicaMarketingSoftware/AMQP-CPP#34]
When I am trying to send message to rabbitmq server which is on window machine from amqpcpp client which is on Linux machine I am not able to publish messages. My queue contains 0 messages.
I have done the following:
installed erlang 6.4
installed rabbitmq server 3.5.3
set environmental variable ERLANG_HOME to C:\Program Files\erl6.4\

I am using AMQP-CPP-Master library which downloaded from copernica

I have added one user other than "guest" and given administrator tag to the user.
when i am running rabbitmqctl list_connections command, it gives my client ip. so connection may be  ok.

In the log, i am getting the following error:

 10.1.124.143:5672):
connection_closed_abruptly.

but when rabbitmq is on a localhost(client & server are on same machine(Linux) it works fine

Please advise. will give further inputs if needed

thanks,
Tapas

**Comment by martijnotto** [comment]
The connection_closed_abruptly is something you seen in the log file on the Windows machine right? This would indicate that the client thinks there is a protocol error. According to the AMQP specifications, in case of protocol errors one has to close the connection immediately and not send anything.

If I understand your post correctly, it does connect and open a channel properly, but the connection closes whenever you try to publish a message? Is this correct? I would be very interested in a Wireshark dump to see what exactly is going on. Be sure to remove any credentials (unless using the default guest/guest combination of course).
