### ISSUE TITLE
Missing void types in Table and Array.

### ISSUE THREAD

**Issue by tarhan** [CopernicaMarketingSoftware/AMQP-CPP#344]
I've tried to search through closed issues but could not find anything related.  
Within AMQP 0-9-1 Protocol Specification there are void field types which you can use within tables. You can see grammar in 4.2.1 section **Formal Protocol Grammar**. Void field type is `V`. Such field does not have size itself besides field type.

Here example of message utilizing such types (seen by Wireshark):
![issue1](https://user-images.githubusercontent.com/5427484/88774394-0f449180-d18c-11ea-8239-789f87c1c716.png)

Such messages produced by [Celery - Distributed Task Queue](https://docs.celeryproject.org/en/stable/index.html).
It is valid headers and Python's clients like Kombu and Pika reading such message without problem.

In your library within `table.cpp`:
https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/c783cbc17e89049c1493c8ca2334682be179f51c/src/table.cpp#L21-L34
Before decode fields using `Field::decode` you decrease `bytesToRead` variable for length of field name and additionally for field type character. In `Field::decode` there no logic for "reading" void type so it returns `nullptr`. And as result such field will no added to `_fields` map.
1. I think this is **logically INCORRECT**. Since consumer (and producers also) could require fields with given name even with null value.

Despite that `bytesToRead` variable decreased by correct value. Problem arise with highlighted field within screenshot. When field is array type and any elements have `Void` field type its array's `size()` method returns incorrect value.
Here reading lines within `array.cpp`:
https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/c783cbc17e89049c1493c8ca2334682be179f51c/src/array.cpp#L25-L35

Again it have same logic: decrease array's `bytesToRead` variable by 1 **and do not add field to `_fields` array if field is `V` type**.
In my case array's `size()` should return 6: 4 byte for length of its content, 1 byte for `V` field type of first element and 1 byte for `V` field type for second element. But since these elements was not added to array's `_fields` it's `size()` method returns 4.
As result parent `table.cpp` incorrectly decrease its `bytesToRead` variable within this line:
https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/c783cbc17e89049c1493c8ca2334682be179f51c/src/table.cpp#L34
In my case at end of real headers `bytesToRead` variable have value of 2 and it read more 2 bytes (delivery mode and priority) out of headers. This will result exception with `frame out of range` error.
So at least you have error with reading nested types.

So questions are:
 - Are you intentionally ignore `Void` type fields?
 - If so how to correctly decrease of parents `bytesToRead` variable?
This especially will be matter if inner type is `F` Table type. In that case even field names sizes will not be included in parent scope.

**Comment by tarhan** [comment]
@EmielBruijntjes It is odd. You are updating library but do not react for issues for months. This issue related to core protocol support and it should be at least considered firstly.
At least make some comments like "We do not plan to support core protocol". 
Not answering at all is more offensive than answer that you will do nothing.

**Comment by EmielBruijntjes** [comment]
To be honest, we ourselves are not using tables with void-types. So it just somethidoesn't have top-priority for our organization, and I am also not familiar with them and how to handle them.

**Comment by tarhan** [comment]
@EmielBruijntjes Yes. I'm understating that you are not using void types. It is odd for me that you are not implementing standard formal grammar of AMQP.

Void types is like `nullptr` in C++, `None` in Python and `null` in C#. In some libraries such properties called **required optional** meaning that you have to specify property even if its value is empty. In **Celery** for example you can specify time range for launch tasks and you could provide empty upper or lower limit (so task launch date will not be limited at one of ends).

> If you can, please send in a pull-request to fix it, so that we can merge it into the code.
I've already done that in #345 at July 29. I think it is not overlap with your newer commits.

**Comment by tarhan** [comment]
@EmielBruijntjes I've found that CI is not working and found that `ReceivedFrame` class became `InBuffer` so I've made commit which renaming it within my `VoidField` class.
Please see #372.

**Comment by tarhan** [comment]
@EmielBruijntjes Also despite that is not related problem. I found that VS2019 create many warnings about converting 64 bit size into 32 bit size within `Envelope` class.
```c++
Envelope(InBuffer &buffer) : MetaData(buffer)
    {
        // extract the properties
        _bodySize = buffer.nextUint64();
        _body = buffer.nextData(_bodySize);
    }
```
Where `_bodySize` is `uint64_t` while `buffer.nextData` expects `uint32_t`. 
If you don't mine, please, review why have you changed size down to 32 bit (maybe it should 32 bit protocol).

I'll also look in Friday.
