### ISSUE TITLE
Compiling under FreeBSD

### ISSUE THREAD

**Issue by aseprano** [CopernicaMarketingSoftware/AMQP-CPP#35]
To compile under FreeBSD there's no need to create macros for be32toh() and so on, they are already declared that way. So you have to change include/endian.h:119 to:

#elif defined(&#95;&#95;NetBSD&#95;&#95;) || defined(&#95;&#95;DragonFly&#95;&#95;)

i.e.: remove checking for &#95;&#95;FreeBSD&#95;&#95; definition.

P.S.: I don't know if the same applies to NetBSD and DragonFly also, but it's like to be: NetBSD and DragonFly BSD don't follow the OpenBSD naming standard for betohxx(), they uses the bexxtoh() naming standard instead.

**Comment by martijnotto** [comment]
Thank you for reporting this issue. I have removed the macro definitions for FreeBSD. Unfortunately I don't have access to a NetBSD or a DragonFly system to test if they need to be removed there too, so I have left them in there.
