### ISSUE TITLE
Support of ASIO standalone edition

### ISSUE THREAD

**Issue by nothisman** [CopernicaMarketingSoftware/AMQP-CPP#381]
Official website：http://think-async.com/Asio/AsioStandalone

Boost is so big to a native project and most of its frequently used methods are implemented by c++11/14, therefore, we're trying to remove boost from our project.

It will be nice if AMQP-CPP gives a support to standalone asio, which no longer a part of boost.

Thanks.

**Comment by EmielBruijntjes** [comment]
Well, you can send in a pull request.
