### ISSUE TITLE
Checking if queue exists while keeping channel intact

### ISSUE THREAD

**Issue by stertingen** [CopernicaMarketingSoftware/AMQP-CPP#386]
Currently I am trying to 'wait for a queue' by declaring it with the 'passive' flag. Unfortunately, when the queue does no exist, the error callback is executed (as expected) and the channel becomes invalid. After checking once, I am unable to to things with the channel. (Error: 'Channel is in error state')

Is there a way to wait for a queue or check if a queue exists without creating an error?

**Comment by EmielBruijntjes** [comment]
A channel is usable until the first error. But why don't you simply create more channels, for example one for every operation that can fail? You do not even have to keep the channel in scope while the operation is in progress.
