### ISSUE TITLE
How to use in multi-threaded code?

### ISSUE THREAD

**Issue by MrNrTwo** [CopernicaMarketingSoftware/AMQP-CPP#39]
Hi Guys,

your lib is a great stuff, really love it :D

 I'd like to know how could I use it in a true multi-threaded environment? 

For example: I've declared an exchange (topic) and a queue, start consuming and I'd like to call channel->bindQueue(...) with different routing keys to the same exchange and same queue from threads could it cause any crash or any inconsistent state? 
Should I use a mutex lock/unlock before call bindQueue to ensure a sequential call?

Or should I create a new channel to execute bindQueue?

**Comment by MrNrTwo** [comment]
Ok, I've found a solution with boost's ioservice and its post method.

**Comment by EmielBruijntjes** [comment]
The AMQP-CPP library itself is thread-safe, meaning that it does not use global or static variables that could cause races when used in multi-threading context.

However, the various objects are not thread safe. You can not call methods on the same connection or channel (or any other) AMQP-CPP object from multiple threads, if you do not use some sort of locking.
