### ISSUE TITLE
Successfully connected through TLS, but no message reaches broker

### ISSUE THREAD

**Issue by noe-otorten** [CopernicaMarketingSoftware/AMQP-CPP#392]
Hello, I am having trouble with secured connections.

### General description

I've set up RabbitMQ broker with dev certificates using `tls_gen` linked in documentation.
Debug using openssl tools shows that everything seems alright at the server, and my CPP client is able to connect and secure connection as seen from logs from both broker and client (logs installed in `onSecuring`, `onSecured` and `onConnected`).

The problem is that almost no message seems to reach broker, and callback from `DeferredConsumer::onSuccess()` is never called.
I de

bug it with stunnel, but being connected with TLS directly gives the same result. I use wirshark to see what packets are sent.

### Description of communication with broker

The routine is as follows: 

1. after connecting to broker, client creates channel, sets `prefetch_count` and puts channel in confirm mode. 
2. checks whether queue `q_consume`, on which consume is planned, is empty and if not, empties it using get and saves contents. 
3. regular consume is registered
4. client periodically publishes messages to exchange that has some other queue `q_publish` bind to it. 
 
(This is not relevant to the topic, but to prevent questions I would mention that I need to empty the queue first in order to act on my business logic).

### Debuging information

With stunnel in server mode, i.e.

my client -> (encrypted connection, secure flag in AMQP::Address true) -> stunnel -> (plain connection) -> broker,

I see that the last communication between client and stunnel (and thus, between stunnel and broker) is `Basic.Get q=q_consume`, and broker responds with `Basic.Get-empty`.
Nothing else is sent from client.

For that reason RabbitMQ management shows connection but no consumer on `q_consume` and no messages waiting in `q_publish`.

I attached pcap file for you to inspect: [pcap_failed_secure_connection_amqp_cpp.zip](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/files/6108678/pcap_failed_secure_connection_amqp_cpp.zip)

With stunnel in client mode, i.e.

my client -> (plain connection, secure flag in AMQP::Address false) -> stunnel -> (encrypted connection) -> broker,

I cannot see the contents of AMQP communication, but in client
 debug I see that published messages are confirmed, and in RabbitMQ management I see them arriving to `q_publish` and a consumer on `q_consume`.

This brings me to conclusion, that I might have misconfigured something in AMQP-CPP, or there is a bug in the library. Assuming first situation, how can I further debug my problem?

Thank you for the answer and the library!

**Comment by mathemaphysics** [comment]
I'm having the same problem. It gets through the handshake using `POCO::Net::SecureStreamSocket` and then it just sits there forever in the loop never seeing anything arrive on the port ever again.

**Comment by EmielBruijntjes** [comment]
This is too little information to say anything meaningful about this. The AMQP-CPP library supports secure amqps:// connections, so I am also a bit puzzled why you try to write such things yourself.

**Comment by mathemaphysics** [comment]
@EmielBruijntjes I understand. The reason we made use of POCO beneath AMQP-CPP was due to the client wanting the worker to run on either on Linux or Windows. It works quite nicely when using the unencrypted socket on both operating systems.

We've used AMQP-CPP + POCO for several projects that worked out nicely. We only ran into issues with SSL. This is unresolved as of this moment.
