### ISSUE TITLE
amqpcpp lib stop to work after publish to invalid exchange

### ISSUE THREAD

**Issue by morden2k** [CopernicaMarketingSoftware/AMQP-CPP#40]
The code:

    AMQP::Channel*    m_channel;

    void RpcHandler::send_ack(const AMQP::Message &message, quint64 deliveryTag, const QByteArray& ba)
    {
        AMQP::Envelope envelope(ba.data());
        envelope.setCorrelationID(message.correlationID());

        //    if (!m_channel->publish("", message.replyTo(), envelope))
        //        LDEBUG() << "qqqqqqqqqqq";
        
        // after this string library stop to work
        //     if coment this string and uncomment previous publish
        //    with correct exchange all is work (ack, receiving new messages etc.)
        //
        if (!m_channel->publish("ajhsakjdhasdkjhas", message.replyTo(), envelope))
            LDEBUG() << "qqqqqqqqqqq";
        
        if (!m_channel->ack(deliveryTag))
            LDEBUG() << "sssssss1";
    }

After sending message to invalid exchange all stop to work:

 1. When I sends ack of my previous message, server does not receives it like I did not send ack. After exit from amqpcpp callback, message status on server changes from unacked to ready status, like I did not send ack. 
Also publish with invalid exchange return true, ack also returns true
 2. No new messages does not comes to my all consumed queus. Also if I send messages to other queues. Messages are pushes to RabbitMQ server and does not comes to my service anymore
 3. No any error reporting/conection closing on AMQP::ConnectionHandler::onError
 4. No any errors from ack or invalid publish

I have only error message on rabbitMq server (/var/log/rabbitmq/rabbit@morden.log)

    =ERROR REPORT==== 7-Aug-2015::17:46:25 ===
    connection <0.2479.0>, channel 1 - soft error:
    {amqp_error,not_found,"no exchange 'asasas' in vhost '/'",'basic.publish'}

No any errors about my ack. 

Could you halp me? Is it bug? I do not want to stop working library, I want to have any errors as minimum e.g. ConnectionHandler::onError if everething stopped or return false from publish without stopping working library or any way to detect this situation in code (only from RabitMQ log file in current moment).  Just restarting of my service is helping (I did not try to close and reopen connection). Would be great to have false from publish call and all continue to work.

Thank you.

**Comment by EmielBruijntjes** [comment]
You can better create a different channel object for every publish call. You can even create a channel on the stack for that. In that case, an error that occurs with a publish() will not stop any of the ack() calls.

Remember that when an error occurs on a channel, the entire channel becomes invalid. Creating new channels is not a very expensive operation, so you can create new channels for everything you want to do.

````c++
void RpcHandler::send_ack(const AMQP::Message &message, quint64 deliveryTag, const QByteArray& ba)
{
    AMQP::Envelope envelope(ba.data());
    envelope.setCorrelationID(message.correlationID());


    //    if (!m_channel->publish("", message.replyTo(), envelope))
    //        LDEBUG() << "qqqqqqqqqqq";

    // create temporary channel for publishing
    AMQP::Channel tempchannel(m_connection);

    // after this string library stop to work
    //     if coment this string and uncomment previous publish
    //    with correct exchange all is work (ack, receiving new messages etc.)
    //
    if (tempchannel.publish("ajhsakjdhasdkjhas", message.replyTo(), envelope))
        LDEBUG() << "qqqqqqqqqqq";

    if (!m_channel->ack(deliveryTag))
        LDEBUG() << "sssssss1";
}
````
