### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by kargapoltsev** [CopernicaMarketingSoftware/AMQP-CPP#41]
Hi. How to compile a static or dynamic library from AMQP-CPP? I tried to do it using the MVS 2015 but I received a huge number of obscure bugs ...

**Comment by Kojoley** [comment]
I had luck to compile AMQP-CPP with MinGW and MSVC14 (VS 2015) after some changes. Here is patch https://gist.github.com/Kojoley/e5e6b56a375f22ec8ce0

**Comment by EmielBruijntjes** [comment]
I would be nice to receive a pull request to fix this for Windows. I only use, test and have access to Linux environments.
