### ISSUE TITLE
Message format Error

### ISSUE THREAD

**Issue by docongminh** [CopernicaMarketingSoftware/AMQP-CPP#425]
Problem occur when i consumed and get messsage.body(). I used DirectExchange. Full body with format different with data sent to queue. Could anyone help me explain about this problem ? Thanks !

- Image 1: Output message.body()
<img width="1275" alt="Screen Shot 2021-09-08 at 21 46 56" src="https://user-images.githubusercontent.com/34453681/132532077-1bf10750-871b-4bd2-9417-25a274d11763.png">

- Image 2: Data sent to queue 

![Screen Shot 2021-09-08 at 21 47 13](https://user-images.githubusercontent.com/34453681/132532613-2b2d5bbf-ac2e-43f6-aa2c-dfb00d31e5fe.png)
- Image 3: Consumming message from queue

![Screen Shot 2021-09-08 at 21 52 16](https://user-images.githubusercontent.com/34453681/132532902-41fc89b6-4751-4045-b128-37cb4c753cbf.png)

**Comment by EmielBruijntjes** [comment]
message.body() is not null-terminated. Use stdout.write(message.body(), message.bodySize()).

**Comment by docongminh** [comment]
thanks ! i also find in [issue 383](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/issues/383)
