### ISSUE TITLE
why can not use regex in call back message

### ISSUE THREAD

**Issue by docongminh** [CopernicaMarketingSoftware/AMQP-CPP#427]
I use callback operation when a message was received. In this operation, i executed regex string, but can not execute regex. Could any body explained about this error ? Thanks

**Comment by EmielBruijntjes** [comment]
This does not seem to be an AMQP-CPP issue. Of course you can use regular expressions on the received messages. Please provide a (small!) piece of sample code if you do think that this is an AMQP-CPP issue.
