### ISSUE TITLE
Segmentation fault after message arived 

### ISSUE THREAD

**Issue by komarovsergey98** [CopernicaMarketingSoftware/AMQP-CPP#433]
Hello everyone. Now we are working with team to launch our application on Centos 7 kernel 3.10. This app we have been developing for ubuntu for several years.
Faced the following problem.
Everything starts and compiles, but when a message is received, we get a segmentation fault .

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  std::_Function_handler<void(const AMQP::Message&, long unsigned int, bool), AmqpMessageDispatcher::startConsuming()::<lambda(const AMQP::Message&, uint64_t, bool)> >::_M_invoke(const std::_Any_data &, const AMQP::Message &, unsigned long &&, bool &&) (__functor=..., __args#0=..., __args#1=<error reading variable>, __args#2=<error reading variable>) at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/std_function.h:300
300		(*_Base::_M_get_pointer(__functor))
```

Unfortunately, we cannot start in debug since the launch takes place on a remote computer with some specific rules. All we have is a core dump from which we pulled the following.

This is stacktrace. We can see that when trying to call the functor, we cannot determine the type of the second and third arguments.
```
#0  std::_Function_handler<void(const AMQP::Message&, long unsigned int, bool), AmqpMessageDispatcher::startConsuming()::<lambda(const AMQP::Message&, uint64_t, bool)> >::_M_invoke(const std::_Any_data &, const AMQP::Message &, <unknown type in /home/root/build/AmqpCommunication/libAmqpCommunication.so.1, CU 0x43ad6, DIE 0xa2c0c>, <unknown type in /home/root/build/AmqpCommunication/libAmqpCommunication.so.1, CU 0x43ad6, DIE 0xa2c1d>) (__functor=..., __args#0=..., 
    __args#1=<unknown type in /home/root/build/AmqpCommunication/libAmqpCommunication.so.1, CU 0x43ad6, DIE 0xa2c0c>, 
    __args#2=<unknown type in /home/root/build/AmqpCommunication/libAmqpCommunication.so.1, CU 0x43ad6, DIE 0xa2c1d>)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/std_function.h:300
#1  0x00007f2f77b2ea21 in std::function<void (AMQP::Message const&, unsigned long, bool)>::operator()(AMQP::Message const&, unsigned long, bool) const (
    this=0x7f2f380050f0, __args#0=..., __args#1=1, __args#2=false)
    at /usr/include/c++/4.8.2/functional:2471
#2  0x00007f2f77b2daa0 in AMQP::DeferredExtReceiver::complete (
    this=0x7f2f38004e68) at deferredextreceiver.cpp:44
#3  0x00007f2f77b495da in AMQP::DeferredReceiver::process (
    this=0x7f2f38004e68, frame=...) at deferredreceiver.cpp:85
#4  0x00007f2f77b3a3b2 in AMQP::BodyFrame::process (this=0x7f2f3dae85e0, 
    connection=0x7f2f38003598) at bodyframe.h:119
#5  0x00007f2f77b3bffe in AMQP::ReceivedFrame::process (this=0x7f2f3dae8670, 
    connection=0x7f2f38003598) at receivedframe.cpp:140

```

and data at this moment

<pre>(gdb) info args
<font color="#06989A">__functor</font> = @0x7f2f380050f0: {_M_unused = {_M_object = <font color="#3465A4">0x13d2cc0</font>, _M_const_object = <font color="#3465A4">0x13d2cc0</font>, _M_function_pointer = <font color="#3465A4">0x13d2cc0</font>, _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) <font color="#3465A4">0x13d2cc0</font>}, 
  _M_pod_data = &quot;\300,=\001&quot;, &apos;\000&apos; &lt;repeats 11 times&gt;}
<font color="#06989A">__args#0</font> = @0x7f2f38004f78: {&lt;AMQP::Envelope&gt; = {&lt;AMQP::MetaData&gt; = {_vptr.MetaData = <font color="#3465A4">0x7f2f77d95d90</font> &lt;<font color="#C4A000">vtable for AMQP::Message</font>+16&gt;, _bools1 = {&lt;AMQP::Field&gt; = {_vptr.Field = <font color="#3465A4">0x7f2f79375128</font> &lt;<font color="#C4A000">vtable for AMQP::BooleanSet</font>+16&gt;}, 
        _byte = 248 &apos;\370&apos;}, _bools2 = {&lt;AMQP::Field&gt; = {_vptr.Field = <font color="#3465A4">0x7f2f79375128</font> &lt;<font color="#C4A000">vtable for AMQP::BooleanSet</font>+16&gt;}, _byte = 96 &apos;`&apos;}, _contentType = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;text/plain&quot;}, _contentEncoding = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;utf-8&quot;}, _headers = {&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f77d94830</font> &lt;<font color="#C4A000">vtable for AMQP::Table</font>+16&gt;}, _fields = std::map with 6 elements = {[&quot;isReplyExchangeDurable&quot;] = std::unique_ptr&lt;AMQP::Field&gt; = {get() = <font color="#3465A4">0x7f2f380049a0</font>}, 
          [&quot;isReplyQueueDurable&quot;] = std::unique_ptr&lt;AMQP::Field&gt; = {get() = <font color="#3465A4">0x7f2f38004a00</font>}, [&quot;replyExchange&quot;] = std::unique_ptr&lt;AMQP::Field&gt; = {get() = <font color="#3465A4">0x7f2f38004a60</font>}, [&quot;replyExchangeType&quot;] = std::unique_ptr&lt;AMQP::Field&gt; = {
            get() = <font color="#3465A4">0x7f2f38004ac0</font>}, [&quot;replyQueue&quot;] = std::unique_ptr&lt;AMQP::Field&gt; = {get() = <font color="#3465A4">0x7f2f38004b20</font>}, [&quot;replyRoutingKey&quot;] = std::unique_ptr&lt;AMQP::Field&gt; = {get() = <font color="#3465A4">0x7f2f38004b80</font>}}}, _deliveryMode = warning: RTTI symbol not found for class &apos;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79375038</font> &lt;<font color="#C4A000">vtable for AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;</font>+16&gt;}, _value = 2 &apos;\002&apos;}, _priority = warning: RTTI symbol not found for class &apos;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79375038</font> &lt;<font color="#C4A000">vtable for AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;</font>+16&gt;}, _value = 7 &apos;\a&apos;}, _correlationID = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;&quot;}, _replyTo = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;&quot;}, _expiration = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;&quot;}, _messageID = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;&quot;}, _timestamp = warning: RTTI symbol not found for class &apos;AMQP::NumericField&lt;unsigned long, (char)84, std::enable_if&lt;true, unsigned long&gt; &gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374d68</font> &lt;<font color="#C4A000">vtable for AMQP::NumericField&lt;unsigned long, (char)84, std::enable_if&lt;true, unsigned long&gt; &gt;</font>+16&gt;}, _value = 1633964266}, _typeName = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;CAD_ENGINE_ANALYZE_DEPENDENCIES_REQUEST&quot;}, _userID = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;

{&lt;AMQP::Field&gt; = {_vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;&quot;}, _appID = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;&quot;}, _clusterID = warning: RTTI symbol not found for class &apos;AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;&apos;
{&lt;AMQP::Field&gt; = {
          _vptr.Field = <font color="#3465A4">0x7f2f79374e58</font> &lt;<font color="#C4A000">vtable for AMQP::StringField&lt;AMQP::NumericField&lt;unsigned char, (char)66, std::enable_if&lt;true, unsigned char&gt; &gt;, (char)115&gt;</font>+16&gt;}, _data = &quot;&quot;}}, 
    _body = //body is correct but i removed it to not demonstrate NDA data
<font color="#06989A">__args#1</font> = &lt;error reading variable&gt;
<font color="#06989A">__args#2</font> = &lt;error reading variable&gt;
</pre>

I cannot understand why, when calling a functor, It cannot determine the type of the second and third arguments.
From memory data, we see that the message structure is good, but the second and third arguments are not.
Has anyone encountered this?

**Comment by EmielBruijntjes** [comment]
How do I compile it, and how to run it?

**Comment by EmielBruijntjes** [comment]
https://en.wikipedia.org/wiki/Linux_kernel_version_history

Kernel 3.10 is EOL for four years now, isn't it?

**Comment by EmielBruijntjes** [comment]
> What can you advise us based on those logs that I sent you? I can also send you core.dump from our env

Provide the smallest possible example program that triggers the crash, so that we can reproduce the issue.

**Comment by rwols** [comment]
@komarovsergey98 would it be possible for you to upgrade the kernel and see if it still crashes? https://phoenixnap.com/kb/how-to-upgrade-kernel-centos

**Comment by komarovsergey98** [comment]
Hey all. Thank you all for your support.
The problem was solved. The system had two different versions of libg++. The AMgp library was built with an older one, while the application itself was newer. Because of this, there was a conflict that turned into such problems. 
Best regards.
