### ISSUE TITLE
Consume is blocking

### ISSUE THREAD

**Issue by naderafshari** [CopernicaMarketingSoftware/AMQP-CPP#435]
**Description**
After making a connection, setting up a channel and starting the consume, the onReceive callback gets invoked and I receive current messages from the queue and the subsequent messages published to the queue but my thread is blocked.  I tried libevent too, same behaviour.

**Expected behaviour**
I thought it should be non-blocking. What am I not setting up correctly?

**Sample code**
    auto *loop = uv_default_loop();

    // create an instance of your own tcp handler
    // handler for libevent
    AMQP::LibUvHandler myHandler(loop);
    //AMQP::LibEventHandler myHandler(evbase);
    //ControlBusTcpHandler myHandler;

    // address of the server
    AMQP::Address address("amqp://guest:guest@rabbitBroker/");

    // create a AMQP connection object
    AMQP::TcpConnection connection(&myHandler, address);
    //AMQP::TcpConnection* myConnection = new AMQP::TcpConnection(&myHandler, address);

    // and create a channel
    AMQP::TcpChannel channel(&connection);
    //AMQP::TcpChannel* myChannel = new AMQP::TcpChannel(myConnection);
    channel.onError([](const char *message) {
        // report error
        std::cout << "channel error: " << message << std::endl;
    });
    channel.onReady([&channel,  &connection, &topic]() {
        // send the first instructions (like publishing messages)
        std::cout << "channel ready" << std::endl;

        // use the channel object to call the AMQP method you like
        channel.declareExchange("request", AMQP::direct)
        .onSuccess([&channel,  &connection, &topic](){
            std::cout << "Exchange declared" << std::endl;

            channel.declareQueue("request.local").onSuccess([&channel,  &connection, &topic](const std::string &name, uint32_t messagecount, uint32_t consumercount){
                std::cout << "declared queue " << name << std::endl;
                channel.declareQueue("request.remote")
                .onSuccess([&channel,  &connection, &topic](const std::string &name, uint32_t messagecount, uint32_t consumercount) {
                    // report the name of the temporary queue
                    std::cout << "declared queue " << name << std::endl;

                    channel.bindQueue("request", "request.remote", "key.local");

                    // callback function that is called when the consume operation starts
                    auto startCb = [](const std::string &consumertag) {

                        std::cout << "consume operation started" << std::endl;
                    };

                    // callback function that is called when the consume operation failed
                    auto errorCb = [](const char *message) {

                        std::cout << "consume operation failed" << std::endl;
                    };

                    // callback operation when a message was received
                    auto messageCb = [&channel](const AMQP::Message &message, uint64_t deliveryTag, bool redelivered) {

                        std::cout << "message received" << std::endl;

                        // acknowledge the message
                        channel.ack(deliveryTag);
                    };
                    // start consuming from the queue, and install the callbacks
                    //channel.consume("request.remote")
                    channel.consume("request.remote")
                        .onReceived(messageCb)
                        .onSuccess(startCb)
                        .onError(errorCb);
                })
                .onError([](const char *message){
                    std::cout << "queue declare failed" << std::endl;
                });//queue 2 declare
            })
            .onError([](const char *message){
                std::cout << "queue declare failed" << std::endl;
            });//queue 1 declare
        })
        .onError([](const char *message){
            std::cout << "Exchange declare failed" << std::endl;
        }); //exchage
    });//channel ready

    //event_base_dispatch(evbase);
    uv_run(loop, UV_RUN_DEFAULT);

The output looks like this
```channel ready
Exchange declared
declared queue request.remote
consume operation started
message received
message received
message received
message received

```
and won't return to main

**Comment by rwols** [comment]
The loop runs for as long as there are async operations. Consuming from a queue is an async operation, as is maintaining a TcpConnection. I believe if you close the TcpConnection the uv_run call will return.

**Comment by naderafshari** [comment]
> The loop runs for as long as there are async operations. Consuming from a queue is an async operation, as is maintaining a TcpConnection. I believe if you close the TcpConnection the uv_run call will return.

Yes the it returns when connection closed but I want to keep the connection open. I want to implements a "subscription" where the consumer would receive messages as they get published. 
From what you are saying it sounds the event loop blocking my thread. Aren't event loops non-blocking too? I also tried libevent with EVLOOP_NONBLOCK option, still blocking.

**Comment by EmielBruijntjes** [comment]
uv_run() is a blocking operation. It is normally the hearth of your application, called from main() or so. All other processes (like the amqp connection) register filedescriptors, timers and callbacks so that the uv_run() function knows how to despatch events. 

Ev_run() stops when there are no more filedescriptors or timers active. In your example code there still is an amqp connection (hence a filedescriptor) thus the function keeps running.

This is not an AMQP-CPP issue.

**Comment by naderafshari** [comment]
Thank you for the responses. Is it possible to have a single "connection" with an event loop to consume and from the same thread publish? I have a feeling what the answer is. What is the best way of implementing consume and publish on the same thread? Is there any client implementation examples out there?

**Comment by EmielBruijntjes** [comment]
If the rest of your application is not yet event-loop based, you need to change that. That keeps everything in the same thread, and keeps all parts of your application responsive.

If this is not achievable, then you need to create a separate thread for the AMQP-CPP connection, with a wakeup/synchronize and (probably) locking mechanism to hand over data from the main thread to the AMQP thread, and the other way around. Do not make the mistake to start calling functions on the AMQP objects from your main thread, because the AMQP-CPP objects are not thread safe. It is up to the caller to ensure that you always access the objects from the same thread.
