### ISSUE TITLE
does some kindly and smart people provide more example

### ISSUE THREAD

**Issue by longjiang321** [CopernicaMarketingSoftware/AMQP-CPP#445]
hi friends:
     Thank you very much for your hard work to provide AMQP-CPP client lib in advance!!!!
     The Rabbitmq offical website has six kinds of mode, and provide offical tutorials of this six modes for many languages expect C/C++,  there has seldom C/C++ tutorious, so it is so diffcult for freshbird to learn. 
     for AMQP-CPP  client libary, there has only three examples,  does some kindly people can provide more examples(especially raw AMQP::Connection/AMQP::Channel objects   and  TCP module of the AMQP-CPP)? it is very diffcult for the newer the wirte a demo without any kind of event loop!
    Thanks very much in advance!!!

**Comment by EmielBruijntjes** [comment]
This is not really an issue. Event loops are a requirement of the AMQP-CPP library.
