### ISSUE TITLE
Service Mesh Sidecar Proxy

### ISSUE THREAD

**Issue by naderafshari** [CopernicaMarketingSoftware/AMQP-CPP#448]
Not an issue, just a question...
Say RabbitMQ server and clients are running in separate containers in a Kubernetes environment with a service mesh/sidecar proxies. 
First, would this library work in this situation? 
If yes... 
Which sidecar proxy has been most commonly used? 
How would the connection to server work? 
How would it work if libevent is used for all the I/O?

**Comment by EmielBruijntjes** [comment]
I don't understand your question. 

The AMQP-CPP library just speaks the AMQP protocol. If there is a RabbitMQ server at the other end of the connection, it works. And the network architecture that lies underneath it, is, as far as I see, further not relevant. Whether a program runs in Kubernetes or Docker, LXC or on bare metal or whatever, or whether there are routers or IP tables or TCP tunnels or whatever else in between, is for AMQP-CPP not responsibility or a concern.
