### ISSUE TITLE
confirmSelect occasionally will not publish messages when repeatedly called

### ISSUE THREAD

**Issue by rpbostock** [CopernicaMarketingSoftware/AMQP-CPP#449]
**Describe the bug**
publish calls within the callback for channel.confirmSelect().onSuccess() can be lost with no callback notification or error on the publish call.

**Expected behavior and actual behavior**

Expected: publish calls within the callback for channel.confirmSelect().onSuccess() should publish each message that is passed to it (one or many), and return an ACK or NACK notification for the messages.

Actual: Over repeated calls to the confirmSelect the latest messages appear to not be sent, while previously unsent messages will then be sent. Whilst sending ~2800 messages approximately 100 messages were lost. 

My application sends approximately 30-100 messages a second as a replay facility. The receive side verifies the order of the messages, and that messages are received. Missing messages that should have been transmitted are not on the message queue using queue diagnostics. The following sample code is an excerpt from the transmission. If more code is required I can provide it. By removing the do..while loop and sending as single messages no faults are seen.

**Sample code**
Provide a small piece of C++ code to demonstrate the issue. Watch out: do not use threads! AMQP-CPP objects are not thread-safe _by design_. If you construct channels or call methods from one thread, while the event loop is running in a different thread, unexpected things can and will happen.

The aim of the code is to send whatever data is available within the onSuccess call. This is normally 2-10 messages. Then when the onAck is received any new available messages are sent.

```c++

void RabbitmqTransmitter::sendMoreData_()
{
	channel.confirmSelect().onSuccess([&]() {
		do
		{
			auto message = messageQueue_.pop();
			numTransmitted_++;

			std::cout << "info: " << numTransmitted_ << ": Message " << message.header() << std::endl;

			// Send over RABBITMQ
			auto network_message = RabbitMessageConverter::convertMessage(message);
			if(!channel.publish("", queue_name_, network_message.data(), network_message.size()))
			{
				std::cout << "error: Failed to publish message " << message.header() << std::endl;
			}
		}
		while(!messageQueue_.isEmpty());

	}).onAck([&](uint64_t deliveryTag, bool multiple) {
		std::cout << "info: All messages up to sequence number " << deliveryTag << " have been processed (" << (int)multiple << ")" << std::endl;
		numReceived_ = deliveryTag;
		sendMoreData_();
	}).onNack([&](uint64_t deliveryTag, bool multiple, bool requeue) {
		// @TODO Need to handle data not being sent correctly - e.g. buffer sent data until an ACK is received.
		std::cout << "error: All messages up to sequence number " << deliveryTag << " have failed to be processed (" << (int)multiple << ")" << std::endl;
	});

}```

**Comment by EmielBruijntjes** [comment]
This might indeed be a bug in AMQP-CPP, but your code could be a bit simpler. You only have to put the channel in confirm-select mode once. After moving to confirm-select mode, you can just call channel.publish(), and you do not have to call confirmSelect _again_. You also do not have to re-install the onSuccess, onAck and onNack methods. In your code however, you call the sendMoreData_() method every time that message are acked, which repeats the call to put the channel in confirm-select mode - and this is not necessary.

Could you help me a bit and say if you still encounter the issue when you call confirmSelect() only once?

**Comment by rpbostock** [comment]
I have done further testing and generally this is working well. One thing that I have found is that if I do not limit the number of messages sent in a batch to ~200 that messages are lost. On 18000-19000 messages this varied from 16000 messages to 100 messages lost.

My code is below in case I still have something incorrect here that will be influencing the result:

''' C++ code

/**
 * This is called on start as a separate thread, and where the channel, etc. is all setup.
 */
void RabbitmqTransmitter::process()
{
	// Keep in a loop as this is where we come back to on a connection error
	while(isProcessing())
	{
		evbase = event_base_new();
		hndl = std::make_unique<LibEventHandlerMyError>(evbase);
		connection = std::make_unique<AMQP::TcpConnection>(hndl.get(), AMQP::Address(address_));
		channel = std::make_unique<AMQP::TcpChannel>(connection.get());

		channel->declareQueue(queue_name_, AMQP::durable)
			.onSuccess([&](const std::string &name, uint32_t messagecount, uint32_t consumercount)
				   {
					   // report the name of the temporary queue
					   std::cout << "declared queue " << name << std::endl;

					   channel->confirmSelect().onSuccess([&]() {
						   // Assume this occurs on the first time confirmSelect is setup
						   sendMoreData_();
					   }).onAck([&](uint64_t deliveryTag, bool multiple) {
						   std::cout << "info: All messages up to sequence number " << deliveryTag << " have been processed (" << (int) multiple << ")" << std::endl;
						   numReceived_ = deliveryTag;
						   sendMoreData_();
					   }).onNack([&](uint64_t deliveryTag, bool multiple, bool requeue) {
						   // @TODO Need to handle data not being sent correctly - e.g. buffer sent data until an ACK is received.
						   std::cout << "Error: All messages up to sequence number " << deliveryTag << " have failed to be processed (" << (int) multiple << ")" << std::endl;
					   });
				   })
			.onError([](const char *message) {
				std::cout << "Channel Error: " << message << std::endl;
			});

		event_base_dispatch(evbase);
		std::cout << "Exiting RabbitmqTransmitter::process()" << std::endl;
	}
}

void RabbitmqTransmitter::sendMoreData_()
{
	static int batchTransmit = 0;
	do
	{
		auto message = messageQueue_.pop();
		numTransmitted_++;
		batchTransmit++;

		std::cout << "info: " << numTransmitted_ << ": Message " << message.header() << std::endl;

		// It might have been poison - time to finish
		if(!isProcessing()) {
			// Close the connection
			connection->close();

			// Cancel the current action
			event_base_loopbreak(evbase);

			// Exit the event system
			event_base_free(evbase);
			std::cout << "Stopped processing data" << std::endl;
			return;
		}

		// Send over RABBITMQ
		auto network_message = RabbitMessageConverter::convertMessage(message);
		if(!channel->publish("", queue_name_, network_message.data(), network_message.size()))
		{
			std::cout << "Error: Failed to publish message " << message.header() << std::endl;
		}
	}
	while(!messageQueue_.isEmpty() && batchTransmit < 200);
	batchTransmit = 0;
}

**Comment by EmielBruijntjes** [comment]
I don't understand what you mean. I simplified your example code to this, but as far as I see it, everything is published:
```
// dependencies
#include <amqpcpp.h>
#include <amqpcpp/libev.h>

// main procedure
int main()
{
    // standard handler
    AMQP::LibEvHandler handler(EV_DEFAULT);
    
    // set up connection and channel
    AMQP::TcpConnection connection(&handler, "amqp://guest:guest@localhost/");
    AMQP::TcpChannel channel(&connection);
    
    // number of messages sent
    size_t counter = 0;
    
    // function to send a batch of messages
    auto sendmore = [&channel, &counter]() {
        size_t batchsize = 20000;
        std::cout << "send batch " << batchsize << std::endl;
        for (size_t i = 0; i < batchsize; ++i) channel.publish("","my-queue","my-message");
        counter += batchsize;
    };
    
    // up to what delivery-tag has everything been acked?
    uint64_t lastacked = 0;
    
    // declare a queue
    channel.declareQueue("my-queue", AMQP::exclusive).onSuccess([&]() {
        
        // switch to confirm-select mode
        channel.confirmSelect().onSuccess([&]() {

            // send the first batch
            sendmore();

        }).onAck([&](uint64_t deliveryTag, bool multiple) {

            // if multiple are tagged in one go
            if (multiple) lastacked = deliveryTag;
            
            // if only one was tagged, but this was the one that we expected?
            else if (deliveryTag == lastacked + 1) lastacked = deliveryTag;
            
            // otherwise we already get an ack for a message before we received the acks for messages 
            // that we published earlier (i think that there is nothing that forbids this, but we should
            // handle that here instead of showing an error)
            else std::cout << "RABBITMQ ALSO SENDS OUT-OF-BOUND ACKS" << std::endl;
            
            // send more if everything so far has been acked
            if (lastacked >= counter) sendmore();
            
        }).onNack([&](uint64_t deliveryTag, bool multiple, bool requeue) {
            std::cout << "Error: All messages up to sequence number " << deliveryTag << " have failed to be processed (" << (int) multiple << ")" << std::endl;
        });
    });
    
    // run the event loop
    ev_run(EV_DEFAULT);
    
    // done
    return 0;
}
```
