### ISSUE TITLE
What version of AMQP this library is implementing - AMQP 1.0 or/and AMQP v0.9.1.

### ISSUE THREAD

**Issue by lesio999** [CopernicaMarketingSoftware/AMQP-CPP#454]
this is just question
I'm looking for library which handles for version and work with Azure Service Bus as well as with RabbitMQ

Regards 

Les

**Comment by EmielBruijntjes** [comment]
It is intended for use with RabbitMQ, it implements 0.9.1. I don't know if it works with other message brokers as well.
