### ISSUE TITLE
Channel operations inside message handlers time out

### ISSUE THREAD

**Issue by mbulut** [CopernicaMarketingSoftware/AMQP-CPP#457]
## Description

In the problem scenario, pub/sub traffic is combined with req/res traffic in a 3 process distributed architecture. The subscriber and the client channels live in the first process, the publisher in the second and the server in the third process. A request is executed from within a subscription handler and synchronized with a future. This synchronization fails as the request never gets delivered to the server.

## Expected behavior

1. The publisher eventually generates some event, identified by the message 'go'.
2. The subscriber receives that event, delegates it to the client channel which in turn, makes a request to the server.
3. The server receives the request, processes it and sends back the response.
4. The client receives the response and completes the operation.

The sample program's expected output on the console is:
```
queue request-queue declared
subscriber recvd: go
server recvd: go
client recvd: GO
```

## Observed behavior
1. The publisher eventually generates some event, identified by the message 'go'.
2. The subscriber receives that event, delegates it to the client channel which in turn, makes a request to the server.
3. The server never receives the request.
4. The client operation times out.

The sample program's observed output on the console is:
```
queue request-queue declared
subscriber recvd: go
request timed out
```

When the req/res part, encapsulated in the function `make_request` below, is executed on its own thread the messages get delivered and everything seems to work. However, this does not feel like the right solution to the problem, especially after reading the note about threading.

## Sample program
The following code demonstrates the issue. The threaded `make_request` call is commented out, so this program will show the observed behavior.
```c++
#include <algorithm>
#include <exception>
#include <iostream>
#include <future>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>

#include <amqpcpp.h>
#include <amqpcpp/address.h>
#include <amqpcpp/libevent.h>
#include <event2/event.h>
#include <event2/thread.h>

using namespace std::chrono_literals;

namespace
{

void loop_exit(struct event_base *event_base)
{
  event_base_loopexit(event_base, nullptr);
  event_base_loopbreak(event_base);
}

}

int main(void)
{
  evthread_use_pthreads();
  auto event_base = event_base_new();

  AMQP::LibEventHandler event_handler{event_base};
  AMQP::TcpConnection connection{&event_handler, AMQP::Address{"amqp://guest:guest@localhost"}};

  AMQP::TcpChannel publisher{&connection};
  AMQP::TcpChannel subscriber{&connection};
  AMQP::TcpChannel client{&connection};
  AMQP::TcpChannel server{&connection};

  std::string pub_exchange{"publish-exchange"};
  std::string sub_queue{"subscription-queue"};
  std::string req_queue{"request-queue"};
  std::string res_queue{"response-queue"};

  auto req_handler = [&server](auto const& msg, auto tag, auto)
    {
      /* convert incoming message to uppercase and echo back to replyTo queue */
      server.ack(tag);
      std::string req{msg.body(), msg.body() + msg.bodySize()};
      std::cout << "server recvd: " << req << std::endl;

      auto res = req;
      std::transform(res.begin(), res.end(), res.begin(), ::toupper);
      AMQP::Envelope env{res.c_str(), res.size()};
      env.setCorrelationID(msg.correlationID());

      server.publish({}, msg.replyTo(), env);
    };

  auto make_request = [&event_base, &client, &req_queue, &res_queue](std::string req)
    {
      std::string req_tag{"42"};
      AMQP::Envelope env{req.c_str(), req.size()};
      env.setCorrelationID(req_tag);
      env.setReplyTo(res_queue);

      std::promise<std::string> p;
      auto f = p.get_future();

      client.consume(res_queue, req_tag)
            .onReceived([&p, &client](auto const& res, auto res_tag, auto)
              {
                p.set_value(std::string{res.body(), res.body() + res.bodySize()});
                client.ack(res_tag);
              })
            .onError([&p](auto const *err)
              {
                p.set_exception(std::make_exception_ptr(std::runtime_error{err}));
              });

      client.publish(std::string{}, req_queue, env);

      try
      {
        if (f.wait_for(3s) == std::future_status::timeout)
          std::cout << "request timed out" << std::endl;
        else
          std::cout << "client recvd: " << f.get() << std::endl;
      }
      catch (std::runtime_error const& e)
      {
        std::cout << "client: " << e.what() << std::endl;
      }

      loop_exit(event_base);
    };

  auto sub_handler = [&subscriber, &make_request](auto const& msg, auto tag, auto _)
    {
      subscriber.ack(tag);
      std::string text{msg.body(), msg.body() + msg.bodySize()};
      std::cout << "subscriber recvd: " << text << std::endl;

      /*
      * The synchronous call to make_request causes a deadlock in all calls into the client channel.
      * Deferring it on a detached thread seems to work but it doesn't feel like the right solution
      * to the problem, especially after reading the note about threads in the bug report template.
      */
      make_request(text);
      // std::thread{[&make_request, req = std::move(text)]{ make_request(req); }}.detach();
    };

  client.declareQueue(res_queue);

  server.declareQueue(req_queue)
        .onSuccess([&server, &req_handler](auto const& name, auto, auto)
          {
            std::cout << "queue " << name << " declared" << std::endl;
            server.consume(name).onReceived(req_handler);
          });

  subscriber.declareQueue(sub_queue)
            .onSuccess([&subscriber, &pub_exchange, &sub_queue, &sub_handler](auto const& name, auto, auto)
              {
                subscriber.bindQueue(pub_exchange, sub_queue, sub_queue)
                          .onSuccess([&subscriber, &sub_queue, &sub_handler]
                            {
                              subscriber.consume(sub_queue).onReceived(sub_handler);
                            });
              });

  publisher.declareExchange(pub_exchange, AMQP::fanout)
           .onSuccess([&publisher, &pub_exchange]
             {
               publisher.publish(pub_exchange, {}, "go");
             });

  event_base_dispatch(event_base);
  event_base_free(event_base);

  return 0;
}
```

## Additional note
In our normal setup, the `request-queue` is declared dynamically inside the subscription handler, right before the request is made. Similarly to publishing the request, the call to `Channel::declareQueue` also times out and we would abort the handler. Interestingly though, the `onSuccess` handler of the `Channel::declareQueue` call gets invoked right after the subscription handler determines the operation has timed out and returns.

The reason why I declare the `request-queue` beforehand in this sample is that I think both issues have the same root cause and I wanted to keep things simple.

**Comment by EmielBruijntjes** [comment]
I do not fully understand your code, but I see no place where you run the event loop, and I also don't understand why you call future.wait_for(). That is a blocking call, isn't it?

**Comment by mbulut** [comment]
The event loop is run at the end of the main function using `event_base_dispatch`, just like it is shown in the [libevent example](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/master/examples/libevent.cpp).

The `wait_for()` is to await the response message. Can you explain why this is problematic and how to properly wait for the response message in req/rep communication as shown above?

**Comment by EmielBruijntjes** [comment]
During the wait_for() nothing happens. The program is frozen, also the procedure that receives messages. Don't use it, just run the event loop. If you need a timer, use the libevent timer-mechanism and add that to the event loop.
