### ISSUE TITLE
Why I CAN NOT get bindQueue().onSuccess or onError callback

### ISSUE THREAD

**Issue by frank51234** [CopernicaMarketingSoftware/AMQP-CPP#465]
**Describe the bug**
As a consumer, I start to call channel.bindQueue. However I cannot get onSuccess or onError callback in a reasonable time. It seems stuck and until I quit my progress, the onError callback is invoked.

**Expected behavior and actual behavior**
I expect I get onSuccess or onError in a reasonable time. The I can start to consume.

**Sample code**
Provide a small piece of C++ code to demonstrate the issue. Watch out: do not use threads! AMQP-CPP objects are not thread-safe _by design_. If you construct channels or call methods from one thread, while the event loop is running in a different thread, unexpected things can and will happen.
```c++
//Anyway I create a new thread for libuv event loop in my codes. Is it the root cause?

void uvRun(void* arg)
{
    uv_run((uv_loop_t*)arg, UV_RUN_DEFAULT);
}

int main()
{
    auto *loop = uv_default_loop();
    MyHandler handler(loop);
    AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost/"));
    AMQP::TcpChannel channel(&connection);
    channel.declareQueue(AMQP::exclusive).onSuccess([&connection](const std::string &name, uint32_t messagecount, uint32_t consumercount) {
        
        // report the name of the temporary queue
        std::cout << "declared queue " << name << std::endl;
    });
    channel.bindQueue().onSuccess([]() {
         //...
    });
    channel.consume().onMessage([]() {
        //...
    }).
    onSuccess([](){}).
    onError([](){});

    // create a new thread to run the loop  ####Is it the problem root cause?
    uv_thread_create(&_uvThreadId, uvRun, loop);

    // done
    return 0;
}
```
My observation would be after channel.bindQueue() is invoked, I get nothing callback either onSuccess or onError. The looked stuck.

**Comment by EmielBruijntjes** [comment]
Can you supply an example without using threads?

**Comment by EmielBruijntjes** [comment]
How can I compile this?
