### ISSUE TITLE
/usr/bin/ld: cannot find -lamqcpp

### ISSUE THREAD

**Issue by ashsifat** [CopernicaMarketingSoftware/AMQP-CPP#470]
trying to build one of the examples: libevent.cpp
getting linker flags error
please let me know what I am doing wrong

![image](https://user-images.githubusercontent.com/30849030/181603768-e45bde46-9168-4b66-af84-8b719a75241d.png)

**Comment by EmielBruijntjes** [comment]
should be -l amqpcpp
