### ISSUE TITLE
undefined reference to amqp library funtions

### ISSUE THREAD

**Issue by ashsifat** [CopernicaMarketingSoftware/AMQP-CPP#471]
I have installed rabbitmq and amqp-cpp library successfully. also installed libevent-dev. But then when i try to compile the example code I get this errors. I have set build examples to ON in cmakelists.txt and tried both cmake and make
compile command:
g++ -g -Wall -lamqpcpp -lpthread -ldl examples/libevent.cpp -o libevent-cpp
error message:
![image](https://user-images.githubusercontent.com/30849030/181634367-95e270bd-744c-4745-bb38-f60a447f1c59.png)

**Comment by EmielBruijntjes** [comment]
Looks good to me, maybe you need to change the order of the -lamqpcpp flags that you pass to the compiler
