### ISSUE TITLE
TCPConnection using LibUvHandler - how to reconnect if connection is lost

### ISSUE THREAD

**Issue by akulkar1** [CopernicaMarketingSoftware/AMQP-CPP#472]
Hi all,

I am writing a piece of code that publishes messages to an exchange. It has this model -

Globals:
  - RMQConnector: contains TcpConnection, TcpChannel etc.

**Thread T1 (Connection creator) -**

while (true) {
     Connect()
}

function Connect {
      - allocate uv_loop_t.
      - Creates RMQConnector::TcpConnection / TcpChannel
      - Start uv_loop using uv_run
              - In channelReadyCallback: Creates exchange.
              - In exchangeReadyCallback: Sets **publish_ready** flag = TRUE.
      - We come out of uv_run only when uv_stop is called.
      - Free channel
      - Free connection
      - Close uv_loop and free uv_loop.
}

If error on connection, then error callback on channel will -
  - Close channel
  - Close connection
  - Stop uv_loop.

**Thread T2 (Publisher) -**

- Wait for **publish_ready** flag to become true.
- Makes use of RMQConnector::channel to publish messages.
    - RMQConnector.channel()->publish(...)

Based on this model, I have a few questions -

1. Is this the right way to go ahead with reconnecting to RabbitMQ?

2. There are a few races here between publisher and the reconnect mechanism. The races are given below. Is there a good way to solve these races -
    (a) In thread T1, the channel and connection resources can be freed leading to either null 
    (b) The publisher could be working on a stale handle of a channel and publish messages using that. What happens in this case?

I am new to RabbitMQ and AMQP-CPP, so just trying to figure out the basics. Pardon these basic questions.

Thanks

**Comment by EmielBruijntjes** [comment]
Don't use threads.

**Comment by akulkar1** [comment]
My application is inherently multi-threaded. There could be multiple actors (working as part of multiple threads) that can be publishing messages to the RabbitMQ server. I would like all of them to make use of the same connection and channel. How can this be accomplished if AMQP-CPP objects are not thread safe?

**Comment by EmielBruijntjes** [comment]
1. Depends on how much you publish. If you publish one message per day, creating a new connection makes sense. If you publish 1 million messages per minute you better keep the connection oipen.

2. You can have as many event loops as you like.

AMQP-CPP objects are not thread safe, just like almost every other C++ object. You're also not writing to the same file from multiple threads, or writing to the same memory buffer. That will lead to unexpected behavior (read: crashes).

**Comment by akulkar1** [comment]
Thanks again for responding to my questions.

We will be publishing lots (read ~16K) messages per second. We need to keep the connection open.

We have multiple publishers. From your reply, it seems that these multiple publishers can't use the same connection / channel because these objects are not thread safe. Essentially, what you are suggesting is one connection/channel per publisher thread. Is my understanding correct?

**Comment by EmielBruijntjes** [comment]
I am not suggesting anything. It is your application. You can write it the way you want. You can set up multiple connections one in each thread, you can refactor your application to avoid threads, you can synchronize threads and pass data from one thread to the other, etc, etc, etc.

**Comment by akulkar1** [comment]
Thanks. Can you confirm whether this understanding is correct -

From your reply, it seems that these multiple publishers can't use the same connection / channel because these objects are not thread safe.
