### ISSUE TITLE
[Question] Throwing from `ConnectionHandler::onData`

### ISSUE THREAD

**Issue by itrofimow** [CopernicaMarketingSoftware/AMQP-CPP#473]
Hi!
First of all, great library, a pleasure to works with.

I'm trying to incorporate the library into another peace of software, which uses it's own I/O mechamism and
tries its best to hide the asynchronous nature of it from a user, making async code look straightforward.

I use that seemingly synchronous I/O in `ConnectionHandler::onData` like this
```
MyConnectionHandler::onData(buf, size) {
    // all the async heavy-lifting is done by libev and some coroutine magic
    socket_.SendAll(buf, size, deadline_);
}
```
but the problem is it could very well throw (socket closed, timeout etc), and although
i'm fine with that and can handle it on the call site, it terminates the application,
because `ConnectionHandler::onData` is called from `PassthroughBuffer` destructor, which is not marked
`noexcept(false)`.

As of now i'm forced to handle that in a way that complicates my code significantly, but i'm wondering
whether this is an intended design limitation of the library or it could be a slight oversight?

**Comment by EmielBruijntjes** [comment]
I am not sure if I understand what you mean. You want to throw exceptions from within your callbacks? I don't think that this is a very good idea, and AMQP-CPP will probably not survive that. After every call to a "user space" callback, AMQP-CPP expects that the control is handed back, and that your code will not be performing odd jumps because of exceptions or so.

So better don't throw exceptions from within your callbacks.

**Comment by itrofimow** [comment]
I see your point, thanks.

Maybe it should be either documented or `noexcept`-ed where appropriate? - it was very surprising for me to see my application just crush when throwing from `ConnectionHandler::onData`, and it took me some time to realize why exactly that was the case.

**Comment by itrofimow** [comment]
@EmielBruijntjes kindly pinging you on this ^

**Comment by EmielBruijntjes** [comment]
From my perspective it is perfectly normal to not throw exceptions in callbacks that you pass to third party libraries. Just like you're not normally supposed to call free() on memory that you have not allocated, or close() on filedescriptors that you have not opened. I don't see a point in documenting something that is, for me, obvious. Plus I am a bit afraid that adding noexcept in tons of places will break existing programs.

**Comment by EmielBruijntjes** [comment]
Sure. You could send in a pull request to update the readme, and/or the relevant header files

**Comment by itrofimow** [comment]
Did just that. Could you please have a look?
