### ISSUE TITLE
TSAN: race condition between TcpResolver and IO threads

### ISSUE THREAD

**Issue by pgit** [CopernicaMarketingSoftware/AMQP-CPP#474]
This has already been described in #152, but I'm re-opening this because the TSAN failure _is not a false positive_.

The race occurs over the the client socket created within the TcpResolver thread, which is later used by the user-provided IO thread that does the FD polling. On first glance, there is some kind of  synchronization: `TcpResolver::run()` uses a PIPE to communicate with the IO thread, and wakes it up this way. Only after this the IO thread will start polling the socket.

The Problem is that using a PIPE this way is fine for waking up another thread, but does not guarantee that any other changes to memory performed in the TcpResolver thread have become visible in the IO thread. In other words, writing/reading to a PIPE is not a memory barrier.

Nothing in the documentation of pipe/pipe2 says something of memory synchronization, and this page about [memory synchronization primitives](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_12) explicitly lists the few POSIX functions that do.

**Comment by EmielBruijntjes** [comment]
Ok, thank you for your report and ponters to documentation. I did not know this and find it a bit difficult. Based on the article you mentioned it seems that _joining_ the thread is a good way to sync the memory between the threads, so I refactored the code a tiny bit. Do you think that this fixes the issue?

**Comment by pgit** [comment]
lgtm, thanks for the quick fix. I'll try the patch in a tsan-instrumented build tomorrow.

**Comment by pgit** [comment]
I can confirm this fixes the TSAN error. Joining the thread indeed acts as a memory barrier.

As a side note, the onAttached() handler is called before the thread is joined, just after the connection has been constructed. It's documentation says as much, but it may be worth adding that it is not safe to access any member (like fileno()) yet because that would be in a race again.

Thanks again.
