### ISSUE TITLE
During tuning, Connection handles frame-max=0 incorrectly.

### ISSUE THREAD

**Issue by boimart1** [CopernicaMarketingSoftware/AMQP-CPP#475]
**Describe the bug**

When an `AMQP::Connection` connects to a server, during the tune step, if the server proposes a `frame-max` value of 0, the client will be unable to finish connecting, failing silently and potentially blocking forever.

**Expected behavior and actual behavior**

According to the [AMQP Reference Guide](https://www.rabbitmq.com/amqp-0-9-1-reference.html#connection.tune) (emphasis mine):
> The largest frame size that the server proposes for the connection, including frame header and end-byte. The client can negotiate a lower value. **Zero means that the server does not impose any specific limit but may reject very large frames if it cannot allocate resources for them**.
> 
> Until the frame-max has been negotiated, both peers MUST accept frames of up to frame-min-size octets large, and the minimum negotiated value for frame-max is also frame-min-size.

Instead of the above behavior, the client takes the value of 0 as-is, and in the following step when it attempts to respond with tune-ok, it finds that its frame is larger than 0 and does not send the frame. The connection then essentially halts, as neither the client nor the server attempt to take further action.

**Sample code**

On the server side, the python package amqp-mock (as of version 0.4.0) sends a tune with a frame-max of 0. A simple demo program for the server is as follows:
```py
import asyncio
import logging

from amqp_mock import AmqpServer, HttpServer, Storage, create_amqp_mock

async def main() -> None:
    storage = Storage()
    await storage.bind_queue_to_exchange('demo-queue', 'demo-exchange')
    
    http_server = HttpServer(storage, port=8080)
    amqp_server = AmqpServer(storage, port=5672)
    async with create_amqp_mock(http_server, amqp_server) as mock:
        messages = storage.get_next_message('demo-queue')
        async for msg in messages:
            print(f"new message : {msg}")
            print('Properties: ', msg.properties)

if __name__ == "__main__":
    logging.basicConfig(level="DEBUG")
    asyncio.run(main())
```

For the client, any simple program should work. Here's the one I used, based on the libboostasio example, though the behavior should be event-loop-agnostic.
```c++
#include <boost/asio/io_service.hpp>
#include <boost/asio/strand.hpp>
#include <boost/asio/deadline_timer.hpp>

#include <amqpcpp.h>
#include <amqpcpp/libboostasio.h>

#include <iostream>

class MyHandler : public AMQP::LibBoostAsioHandler {
public:
    using AMQP::LibBoostAsioHandler::LibBoostAsioHandler;

    void onError(AMQP::TcpConnection *connection, const char *message) override
    {
        std::cerr << message << std::endl;
    }
};

int main(int argc, char** argv)
{
    boost::asio::io_service service(2);
    MyHandler handler(service);
    
    AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost/"));
    AMQP::TcpChannel channel(&connection);

    channel.onReady([&channel]{
        std::cout << "Connected, publishing message\n";
        channel.publish("demo-exchange", "", "Hello, world!");
    });

    return service.run();
}
```

Here is the logged output from the server, showing that it sent a tune but never received a tune-ok:
![image](https://user-images.githubusercontent.com/28604875/184710347-5b038df1-953e-4142-9a25-73163345f776.png)

Additionally, after debugging and investigating the AMQP-CPP source code, the fix could be done in one of two places, depending on the preferred approach.
1. This sets the connection's `_maxFrame` member to the value received from the tune, i.e. 0: https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/c273d936253ed08ff15642d6874406a564b8f9b5/src/connectiontuneframe.h#L135
2. This compares the frame's size to `_maxFrame`, and this check will always fail once `_maxFrame` has been set to 0: https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/c273d936253ed08ff15642d6874406a564b8f9b5/src/connectionimpl.cpp#L392

In either of these places, a special case could me made for the special value 0.

**Comment by EmielBruijntjes** [comment]
Thanks, you are right this was indeed wrong.
