### ISSUE TITLE
onError and other callbacks might not be called in certain conditions 

### ISSUE THREAD

**Issue by iragel-percipient** [CopernicaMarketingSoftware/AMQP-CPP#477]
**Describe the bug**
Error may happen after function return and before user sets onError callback. Then onError will not be called.

**Expected behavior**
Callbacks should be set before function call and passed as function parameters to function.

**Sample code**

```c++
int main()
{
    Channel myChannel(&connection);

    auto deferred = myChannel.declareExchange("my-exchange");

    // How do you guarantee that error did not occur before we set onError callback?

    deferred.onError([](const char *message) {
        // something went wrong creating the exchange
});}
```

**Comment by EmielBruijntjes** [comment]
Do you have a better example of this? The way I see it, the callbacks are only called in _later_ iterations of the event loop (when a response from the server is received), so if you immediately set the callbacks before you do anything else, there should not be any issue.

For the time being I close this issue, unless you can give me more input to prove in what situation the callbacks can be called before any other actions.

Please also keep in mind that the objects in AMQP-CPP are not thread safe. And that you're supposed to set the callbacks immediately after the "channel.dosomething()" call.
