### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by Kojoley** [CopernicaMarketingSoftware/AMQP-CPP#48]
There are some minor and major issues with building on Windows:
1. #46 fixed errors, but somewhere are still defined `max` macros which produces warnings.
2. Missing `htonll` and `ntohll` (mentioned in #41) in `Winsock2.h`, but [MSDN](https://msdn.microsoft.com/en-US/library/windows/desktop/jj710199%28v=vs.85%29.aspx) claims them should be there.
3. `TcpConnection` uses POSIX sockets (mentioned in #46 and #45).
4. Warnings in Visual Studio (because of more verbose warning level than GCC has by default)

**Comment by EmielBruijntjes** [comment]
I am not a Windows user. Can you send a pull request that fixes this?

**Comment by gk0090** [comment]
I am also getting that kinda error and i replace socket.h with winsock2.h and netdb.h,unistd.h with windows.h. now i am getting more then thousands error.Most of them are related to different callback class.

Please help me with this.
Thanks

**Comment by dharanikumar-s** [comment]
Hi, I too get the same error as @gk0090 commented. I too tried replacing linux header files with windows equivalents ones, but of no use. Is there any solution available for this issue? Do you require the detailed build log for debugging this issue?

**Comment by Vermillionaire** [comment]
I feel like this section in the README is a bit ambiguous

> For users on a non-Linux environment: this library is known to work on your environment too (after all, it does not do any operating specific system calls), but it might take some extra effort to get your compiler to compile it. Please send in your pull requests once you have it running, so that others can benefit from your experiences.

It actually does have some Linux/Unix specific system calls in the pipe.h header. This will probably work fine on a Mac, but Windows pipes are different enough that this could be quite a headache to fix. I'd probably rephrase this saying that it should support most Linux/Unix systems, but currently not Windows. Just a friendly suggestion :smile:

**Comment by zouqiang8233** [comment]
Remove the Linux platform for the pipe use simultaneous TCP connection will be some differences between the socket under the relevant functions to modify I passed the GIT to submit these But why I can't show

**Comment by dqueffeulouatw** [comment]
Finally, is someone can confirm this lib works on Windows ?
I would like to be sure before to start to compile it.

**Comment by iericzhou** [comment]
As far as I know, this lib doesn't compile on Windows~
If any fellow succeeds in compiling in on Windows, please comment here.

**Comment by xupanwilson** [comment]
I have build it on windows by visual studio 2013 successfully.
please have a look at my attachments.
Seems the attchments has a size limit, you can send me a message, I will reply you with a email.

**Comment by mpazhani** [comment]
Hi @xupanwilson,

Can you please provide me the steps to build the library in Windows or attchment to my mail id (m.pazhaniyappan@gmail.com) ?

Thanks in advance.

**Comment by vivekvrao** [comment]
@xupanwilson I am interested in the windows build as well. can help fork or merge changes.

**Comment by mpazhani** [comment]
@vivekvrao Ref.: https://github.com/jhugard/AMQP-CPP

**Comment by jeflib** [comment]
build for windows with a demo https://git.oschina.net/Ailsc/amqp-cpp.git

**Comment by MikePelton** [comment]
@vivekvrao Ref.: https://github.com/jhugard/AMQP-CPP

Can confirm this builds on VS2017 Community Edition to a static library in both 32- and 64-bit formats. Many thanks indeed!!

**Comment by MikePelton** [comment]
...but before you go down the path I did to get a Windows build of AMQP-CPP, there's a [Nuget implementation](https://www.nuget.org/packages/AMQP-CPP/) of 2.6.1.5 out there to save you the effort!

**Comment by vikaschamp** [comment]
Hello Friends,

May anybody send me any link or compiled amqp library (cpp) in visual studio .
I am trying to compile for make lib but i am stuck in errors.

This is my email id:  vikasjai134@gmail.com

Thanks in advance: :)

**Comment by fantastory** [comment]
You can try my build 
https://www.nuget.org/packages/AMQP-CPP/
or build from source from my branch.

**Comment by vikaschamp** [comment]
@fantastory  :)
I tried to install from  nuget package manager console but i am getting this error.


PM> Install-Package AMQP-CPP -Version 2.6.1.5
Install-Package : The current environment doesn't have a solution open.
At line:1 char:16
+ Install-Package <<<<  AMQP-CPP -Version 2.6.1.5
    + CategoryInfo          : InvalidOperation: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetNoActiveSolution,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM>

**Comment by fantastory** [comment]
"The current environment doesn't have a solution open."
Create a  "Solution"?
OR you can use manual download and unpack the archive, 7z should recognize it, (zip I guess)

**Comment by MikePelton** [comment]
Hi - as mentioned above I went round the houses here a little. At the time the Nuget version didn't ship with a built static library (.lib) file (it may now?) so you get link errors. [JHugard](https://github.com/jhugard/AMQP-CPP)'s Windows fork works perfectly, but the fork is from slightly old code, and the [examples ](https://github.com/hoxnox/examples.amqp-cpp) didn't quite compile. As a side note I was pleased to find that the examples ship using a worker thread based on boost::asio - pleased because it works and pleased because it's not easy to find good simple examples using boost::asio! 
The build I'm using now is built in the traditional CMake fashion from fantastory's latest code - I fixed some TCP stuff (Linux and Windows doing these things differently of course) and all is well, but by far the easiest way to get going is with JHugard's build.

**Comment by fantastory** [comment]
Boost examples are taken from Copernica, so all profit goes for them. While I use that nuget package - boost version - in production I feel the code went way away from Copernica main branch. 
They made some fixes, especialy heartbeat. 
think there would be a need to make a port again from their branch. But this time maybe little slower so there will be some possibility to merge it back to Copernica.
Last time I did it in a hurry to get it work on windows.

**Comment by vikaschamp** [comment]
Hello friends ,

I have successfully install AMQP-CPP library in VS-2017 but how can i test it .
I did some work for testing it but not able to test.
May you please suggest me some code or link how can i test .
One more thing there is no any lib file .
Thanks in advance.

**Comment by fantastory** [comment]
did you installed header package?
you need binary one
https://www.nuget.org/packages/AMQP-CPP-vc140/

**Comment by vikaschamp** [comment]
@fantastory  
I just install AMQP-CPP which is avialable in nuget package .
Ya this is header package .
https://www.nuget.org/packages/AMQP-CPP-vc140/
above link solution is not working for me : 
After firing this on console : Install-Package AMQP-CPP -Version 2.6.1.5
I am getting this exception--->
"
Install-Package <<<< AMQP-CPP -Version 2.6.1.5
CategoryInfo : InvalidOperation: (:) [Install-Package], InvalidOperationException
FullyQualifiedErrorId : NuGetNoActiveSolution,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
"

**Comment by vikaschamp** [comment]
Header Files are available but i am using it , named like< amqpcpp.h> .
But when i am creating object of connection " AMQP::Connection connection(&myHandler, AMQP::Login("guest", "guest"), "/");"

getting this error:

Error	LNK2019	unresolved external symbol "public: virtual __thiscall AMQP::ConnectionImpl::~ConnectionImpl(void)" (??1ConnectionImpl@AMQP@@UAE@XZ) referenced in function "public: virtual __thiscall AMQP::Connection::~Connection(void)" (??1Connection@AMQP@@UAE@XZ)	AMQP-Test	c:\Users\administrator\documents\visual studio 2017\Projects\AMQP-Test\AMQP-Test\AMQP-Test.obj	1

**Comment by fantastory** [comment]
review your install command it should be:
Install-Package AMQP-CPP-vc140 -Version 2.6.1.5

**Comment by vikaschamp** [comment]
@fantastory  
Sorry Friend i was firing wrong command.
Thank you so much  , i did install and i got lib file for 32 bit and 64bit.
May you suggest me how to test it . Tell me some links , i am confuse to see all google result to test amqp-cpp library .

**Comment by fantastory** [comment]
https://github.com/fantastory/AMQP-CPP.nuget-test

**Comment by vikaschamp** [comment]
@fantastory 
Thanks Friend i have seen above link solution but it little complex for me to understand .
I am new for AMQP-CPP library .
Ok i ll try .
If you have any other solution link may you please send me that also .
Otherwise i ll try for this only -> https://github.com/fantastory/AMQP-CPP.nuget-test
Thanks man

**Comment by vikaschamp** [comment]
@fantastory  
Hello Friend ,

I am getting **connectionimpl.cpp not found**

**Comment by vikaschamp** [comment]
I have installed AMQP-CPP (rabbit mq library ) from NuGet package in visual studio 2017. But i am not able to implement correctly. Please suggest me some example to implement successfully .

I have already tried also these links :-

https://github.com/CopernicaMarketingSoftware/AMQP-CPP
https://github.com/RPG-18/rabbitmq-cpp-tutorials
https://github.com/hoxnox/examples.amqp-cpp
...

**Comment by surgura** [comment]
This should be resolved as of 91c4f891590c630df4f2a18e3f5925ddf41b3d3f. I'd say this can be closed.
