### ISSUE TITLE
[Mini Issue] master is still version "4.3.15" instead of "4.3.16"

### ISSUE THREAD

**Issue by audaki** [CopernicaMarketingSoftware/AMQP-CPP#481]
~~If you want to deliberately move the version updates only into the tags I'd recommend replacing the version in master with some placeholder version. Currently I was just really confused that I had patches in the library which apparently was version 4.3.15 (I checked out master previously) which weren't included in the newer version 4.3.16 (where I checked out the tag)~~

I just found out that the version in tag 4.3.16 is also 4.3.15 so it just wasn't maintained at all

**Comment by EmielBruijntjes** [comment]
You are right, I forget about this when I brought out the last release. Sorry for the confusion.
