### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by dxj19831029** [CopernicaMarketingSoftware/AMQP-CPP#49]
I following information from your doc:
```
ability to set up secure connections (or is this fully done on the IO level)
```

Is that easy to add in openssl support?

**Comment by EmielBruijntjes** [comment]
What exactly do you mean?

If you want secure connections, you can implement the ConnectionHandler interface/class, and make sure that your data is sent over a secure connection. Is that easy? The completely depends on your skills as a programmer. I wouldn't call it as simple as writing "hello world!" - but it is way easier than writing the software of a self-driving-car.
