### ISSUE TITLE
Segmentation fault on transmitter's connection recreation

### ISSUE THREAD

**Issue by ClaudiaPawelek** [CopernicaMarketingSoftware/AMQP-CPP#495]
**Segmentation fault on transmitter's connection recreation**
The issue happens once in a while. The RabbitMQ transmitter and receiver work just fine (transmitting, consuming messages, heartbeats, ack, etc.). However, if there is an issue with a connection on the transmitter's side, the transmitter is not able to recreate the connection sometimes. Instead of that, there is a segmentation fault. The issue has not been observed on the receiver's side, only the transmitter has this problem (at least in my code).

**Sample code**
Here is the smallest possible test program that demonstrates the issue + cmake files + python script that can automatically close the connection.
Source code: [test_app.cpp](https://github.com/ClaudiaPawelek/RabbitMQ-test-app/blob/master/test_app.cpp)
Repo: [RabbitMQ-test-app](https://github.com/ClaudiaPawelek/RabbitMQ-test-app)
AMQP-CPP version: 4.3.17 
I am using AMQP::LibEventHandler with event2/event.h.

**How to reproduce the issue**
1. Close the transmitter connection using 'Force close' in the RabbitMQ Management (web)
2. The issue may not happen immediately, so it is possible that the connection will have to be closed-recreated a few times.

**Call stack**
Transmitter threads: [call stacks](https://github.com/ClaudiaPawelek/RabbitMQ-test-app/tree/master/stack_traces )

**Question**
Is it allowed to use threads - one for publishing, another for connection handler? If not, how exactly LibEventHandler should be used? Based on the call stacks, it looks like one thread was responsible for running `connectionHandler->Start()` while another one was for publishing messages (`channel->publish`).

**Comment by EmielBruijntjes** [comment]
No, it is not allowed to use the same connection from multiple threads. That will lead to crashes. This has been discussed many times in many issues.
