### ISSUE TITLE
Missing type definitions (BUG)  missing header file importing lines.

### ISSUE THREAD

**Issue by Corgile** [CopernicaMarketingSoftware/AMQP-CPP#499]
OS: ubuntu 2004
AMQP installing:

- downloading AMQP-CPP-4.3.23 release and unzip with tar
- in AMQP-CPP-4.3.23/build,  i did `cmake .. -DAMQP-CPP_LINUX_TCP=ON` and make, sudo make install
- also, I installed boost through apt.
- similarly, I installed RabbitMQ-c with cmake.., make and make install

### CMake project, reporting errors after hit "run" button in CLion

<img width="941" alt="image" src="https://user-images.githubusercontent.com/48396880/236622786-d0f914da-e87b-40bd-9af6-8add44598bf7.png">

this is my cmakelists.txt 

<img width="838" alt="image" src="https://user-images.githubusercontent.com/48396880/236622850-42e032d3-cb8a-4d77-8068-6ee83667aee0.png">

It is probably an internal error, because these header files provided by AMQP library do not refer to other header files. In fact, I tried to modify these files manually, and the compilation still failed after adding the necessary header files.

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/48396880/236623154-2ef0c107-4cdb-482e-a48f-f2a47b612ec1.png">

after manually fix

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/48396880/236623050-26f8975a-aee9-40a4-9aed-9b4ee3d9e26f.png">

this is my code

<img width="904" alt="image" src="https://user-images.githubusercontent.com/48396880/236623231-f8b2dcd2-52c2-4dcc-8333-962f04e23fd7.png">

Please fix this, thank you very much

**Comment by EmielBruijntjes** [comment]
Please send in the **smallest possible** program to reproduce this issue. Not as image, but as source code that can be copy/pasted (or so) so that I can run it myself.
