### ISSUE TITLE
Doc doesn't explicitely say if Channel::publish() methods are async or not

### ISSUE THREAD

**Issue by PierreBarnabe** [CopernicaMarketingSoftware/AMQP-CPP#503]
Hello,

Thanks a lot for this very nice library.

I have one single remark/question, to understand the exact behavior of the set of Channel::publish() methods:
Are those also "non blocking" methods, such as all the others Channel methods?
The reason I'm still unsure is that all the other methods return a Deferred object, while those return bool values.

Maybe it would be useful to explicitly say it in the doc (in case it confuses other people) ?

Thanks!

Pierre

**Comment by EmielBruijntjes** [comment]
Yes, they are also non-blocking. But normally, RabbitMQ does not send a confirmation back, so there is _by default_ no deferred object with handlers to check for success or failure. And there is also no guarantee that the publish() call succeeded.

If you do need more reliability, you can however use publish-confirms. This is a feature that has to be explicitly enabled, to instruct RabbitMQ to send an "ack" for every message published. You can enable this by calling the Channel::confirmSelect(), or you wrap your channel in an AMQP::Reliable object, which implicitly enables publisher-confirms, and offers a convenient alternative publish() method:
```
// wrap the channel in an AMQP::Reliable for confirmed publishing
AMQP::Reliable<> reliable(mychannel);

// publish the message
reliable.publish(exchange, routingkey, envelope).onAck([]() {
    // @todo add your own handling (the message has been processed by rabbitmq)
}).onLost([]() {
    // @todo add your own handling (rabbitmq was unable to process the message)
});
```
Above is pseudo-code, I am not 100% sure that all classnames, methods, functions and parameters are exactly named like that, but you'll manage to find out.

**Comment by PierreBarnabe** [comment]
Thanks a lot for the very clear answer!
