### ISSUE TITLE
Compile error in stringfield.h and message.h

### ISSUE THREAD

**Issue by paramveer73** [CopernicaMarketingSoftware/AMQP-CPP#511]
Visual Studio code tried compiling the sample given in the documentation.

`
#include <iostream>
#include <amqpcpp.h>

class MyConnectionHandler : public AMQP::ConnectionHandler
{
};

int main()
{
    MyConnectionHandler myHandler;

    // create a AMQP connection object
    AMQP::Connection connection(&myHandler, AMQP::Login("guest", "guest"), "/");

    // and create a channel
    AMQP::Channel channel(&connection);

    // use the channel object to call the AMQP method you like
    channel.declareExchange("my-exchange", AMQP::fanout);
    channel.declareQueue("my-queue");
    channel.bindQueue("my-exchange", "my-queue", "my-routing-key");
    std::cout << "Hello World!\n";
}`

Property sheet settings

c++ std 17 being used

Include directory --> C:\Program Files (x86)\amqpcpp\include
Preprocessor --> _DEBUG
                     --> _CONSOLE
                     
Additional Library Directories  --> C:\Program Files (x86)\amqpcpp\lib 
Additional Dependencies  --> amqpcpp.lib;pthread.lib;dl.lib;

1>------ Build started: Project: amqcppsample, Configuration: Debug x64 ------
1>amqcppsample.cpp
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): warning C4003: not enough arguments for function-like macro invocation 'max'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(298,2): message : see reference to class template instantiation 'AMQP::StringField<T,F>' being compiled
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): error C3878: syntax error: unexpected token '(' following 'expression'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): message : error recovery skipped: '( ('
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): error C2760: syntax error: ')' was unexpected here; expected ';'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): error C3878: syntax error: unexpected token ')' following 'jump_statement'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): message : error recovery skipped: ') >'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): error C2760: syntax error: ')' was unexpected here; expected 'expression'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): error C3878: syntax error: unexpected token ')' following 'expression_statement'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): message : error recovery skipped: ') ) ?'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): message : error recovery skipped: ') :'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\stringfield.h(250,19): message : error recovery skipped: ') )'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(83,42): warning C4003: not enough arguments for function-like macro invocation 'max'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(83,42): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(83,42): error C2059: syntax error: ')'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(83,1): error C2059: syntax error: ')'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(101,25): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(101,1): error C2062: type 'unknown-type' unexpected
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(101,1): error C2059: syntax error: ')'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(124,28): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(124,1): error C2062: type 'unknown-type' unexpected
1>C:\Program Files (x86)\amqpcpp\include\amqpcpp\message.h(124,1): error C2059: syntax error: ')'
1>Done building project "amqcppsample.vcxproj" -- FAILED.

![image](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/assets/44273391/9840741a-e1c5-441d-a8fb-174b28ee6fd4)

**Comment by EmielBruijntjes** [comment]
And can you fix it? I don't have Visual Studio.

**Comment by paramveer73** [comment]
Hello,

I don’t know how to fix this. I am happy to jump on a call with you.

To be honest I don’t see any error in the code. Maybe some macro I am not
passing or something like that.


Regards,
Paramveer Singh

**Comment by helloTom98** [comment]
Just add parentheses to std:: max and call it. for example: (std::max)(1, 2);
