### ISSUE TITLE
thread safe?

### ISSUE THREAD

**Issue by Yordroid** [CopernicaMarketingSoftware/AMQP-CPP#517]
**Describe the bug**
channel.publish is thread safe?

**Expected behavior and actual behavior**
send msg over 10k , will crash

**Sample code**
![image](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/assets/23250077/3b2e18ad-4be2-4c2b-b445-ccb82e4aa0e2)

```c++

```

**Comment by EmielBruijntjes** [comment]
Objects are not thread safe. If you construct a connection in one thread, you should not call any methods on it (or construct any channels on top of it) inside other threads.
