### ISSUE TITLE
Connection failed on armv7l target

### ISSUE THREAD

**Issue by half45** [CopernicaMarketingSoftware/AMQP-CPP#52]
I'm trying to use amqp-cpp on armv7l (gcc 4.9.3 / uclibc-1.0.6). On host machine x86_64 program works as excepted, but on arm I get this error:

```AMQP error invalid end of frame marker```

Is there any experience with amqp-cpp on non-x86 platforms?

upd: I found that all the negative values in the buffer are wrong. For example, 206 instead of -50.
The problem is that the char may be signed or unsigned depending on the compiler

**Comment by EmielBruijntjes** [comment]
I have not heard of anyone running it on anything other than x87. If you see errors that happen on other platforms, could you be so nice to send in a pull request with fixes?

**Comment by half45** [comment]
Now I solve problem with check to -50 and 206 both. Clearest solution is replace char to int8_t. It's more complex task, I will do it within a month.

**Comment by loruro** [comment]
Is there any progress in resolving issue?

**Comment by jbaumgarten** [comment]
Hi there,
Do you have any update about that issue's patch?

I'm also experiencing this bug, I would spend some time on that patch if nothing is coming

**Comment by EmielBruijntjes** [comment]
There does not seem to be any progress.

**Comment by aviadmini** [comment]
Solved by using clang compiler with "-fsigned-char" cflags/cppflags.
