### ISSUE TITLE
OpenSSL problem

### ISSUE THREAD

**Issue by fvisztra** [CopernicaMarketingSoftware/AMQP-CPP#524]
when I try to connect to my server with OpenSSL I get this error

LogPlayLevel: UAT: libc++abi: terminating due to uncaught exception of type std::__1::bad_function_call
LogPlayLevel: Error: UAT: [2024.04.05-12.29.11:595][  0]LogMac: === Critical error: ===
LogPlayLevel: UAT: SIGABRT: abort() called
LogPlayLevel: UAT: [2024.04.05-12.29.11:595][  0]LogMac: 0x80e360dc libsystem_kernel.dylib!__pthread_kill()   [UnknownFile])
LogPlayLevel: UAT: 0x80d79a40 libsystem_c.dylib!abort()   [UnknownFile])
LogPlayLevel: UAT: 0x80e25070 libc++abi.dylib!__cxxabiv1::__aligned_malloc_with_fallback(unsigned long)   [UnknownFile])
LogPlayLevel: UAT: 0x80e1512c libc++abi.dylib!demangling_terminate_handler()   [UnknownFile])
LogPlayLevel: UAT: 0x80abb99c libobjc.A.dylib!_objc_terminate()   [UnknownFile])
LogPlayLevel: UAT: 0x80e24434 libc++abi.dylib!std::__terminate(void (*)())   [UnknownFile])
LogPlayLevel: UAT: 0x80e27520 libc++abi.dylib!__cxa_get_exception_ptr()   [UnknownFile])
LogPlayLevel: UAT: 0x80e27464 libc++abi.dylib!__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)   [UnknownFile])
LogPlayLevel: UAT: 0x030ecb14 CPPLibTest1!AMQP::Function<ssl_method_st const* ()>::operator()() const   [UnknownFile])
LogPlayLevel: UAT: 0x030eca24 CPPLibTest1!AMQP::OpenSSL::TLS_client_method()   [UnknownFile])
LogPlayLevel: UAT: 0x030f8f94 CPPLibTest1!AMQP::SslHandshake::SslHandshake(AMQP::TcpExtState*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::TcpOutBuffer&&)   [UnknownFile])

**Comment by EmielBruijntjes** [comment]
And how do you expect someone to help you? Please provide the simplest possible test code to demonstrate the issue. Do not use threads.

**Comment by fvisztra** [comment]
so, ina nutshell:

I copied the sample code (libuv.cpp) into Unreal Engine.
It is true that I used thread but without thread it produces the same error.

if I run the code in Editor, everything works fine but as I make an unreal package (Mac or iOS).
The client can connect but it seems by the handshake it just crashes.
Do you think it would be rather an Unreal issue than lib issue?

**Comment by EmielBruijntjes** [comment]
I have no idea, I haven't seen any code yet.
