### ISSUE TITLE
Static tcp library without flags (lssl... )

### ISSUE THREAD

**Issue by fvisztra** [CopernicaMarketingSoftware/AMQP-CPP#525]
the library works well when I build my executable with flags (-lssl) but I would like to build a library with I don't have to add these flags to build an executable...

Thank you for your advice

**Comment by EmielBruijntjes** [comment]
This is possible indeed. In your own program, you must then load openssl dynamically by calling dlopen():
```
// open the openssl library (so that we do not hane to link with "-lssl"
auto handle = dlopen("/path/to/libssl.so.X.Y.Z", RTLD_NOW | RTLD_DEEPBIND);

// tell amqpcpp to use this handle
AMQP::openssl(handle);
```
Note that you can also rely on the library-path (which is nornally set to something like /lib and /usr/lib). In that case you can just specify `dlopen("libssl.so.X.Y.Z", ...);`
