### ISSUE TITLE
Does amqp-cpp support the amqp 1.0 protocol?

### ISSUE THREAD

**Issue by iec-1** [CopernicaMarketingSoftware/AMQP-CPP#528]
Sorry for posting this as an 'issue'. I could not find another place to post questions. Does amqp-cpp support the amqp 1.0 protocol? We want to use amqp-cpp to interface with a the apache activemq broker. This broker uses the amqp 1.0 protocol.

**Comment by EmielBruijntjes** [comment]
No, it was written for RabbitMQ and that uses 0.9.8 (or so please check). I have never used it to connect with anything else than RabbitMQ.
