### ISSUE TITLE
Heartbeat

### ISSUE THREAD

**Issue by naderafshari** [CopernicaMarketingSoftware/AMQP-CPP#532]
How can a connection to rabbitMQ be kept from disconnecting without sending heartbeats?

This in the read me 

The proposed heartbeat interval of the server during connection setup (the server normally suggests an interval of 60 seconds) is vetoed by the AMQP-CPP library so no heartbeats are ever needed to be sent over the connection. This means that you can safely keep your AMQP connection idle for as long as you like

Not clear what the above exactly mean or how to go about it. But ur connection disconnects after a couple of minutes and we want to prevent that and we don’t want to send heartbeats. Is that possible?

**Comment by naderafshari** [comment]
According to this
https://www.rabbitmq.com/docs/heartbeats#disabling
heartbeats can be disabled by setting the timeout to 0 at connection time
Can it be done with this library? 
In connection impl don't see anything directly related to connection timeout.
Does the onNegotiate() with an interval of 0 disable the heartbeats?

**Comment by naderafshari** [comment]
I just saw this
https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/32faf9526afa60f477a7bdb234ad5827a4351d28/src/linux_tcp/tcpconnection.cpp#L27

Would something like this work?
```
    AMQP::Address address(addressString);
    address.option("connectTimeout", 0);
    pCtrlBusConnection_.reset(new AMQP::TcpConnection(&cbeh, address));

```

**Comment by naderafshari** [comment]
This

```
    AMQP::Address address(addressString);
    address.option("connectTimeout", 0);
    pCtrlBusConnection_.reset(new AMQP::TcpConnection(&cbeh, address));

```
did not disable heartbeats. Connection still get disconnected. Any ideas please?

**Comment by EmielBruijntjes** [comment]
You can override the onNegotiate() method of the TcpConnectionHandler and return a value of 0, that will disable the heartbeats.
