### ISSUE TITLE
Bazel support

### ISSUE THREAD

**Issue by joyanta55** [CopernicaMarketingSoftware/AMQP-CPP#537]
Hi,
Is there any plan to add `BUILD` files to support `Bazel` in the future?
Best.

**Comment by EmielBruijntjes** [comment]
No, I have no plans for that, you will have to do this yourself.

**Comment by joyanta55** [comment]
> No, I have no plans for that, you will have to do this yourself.

yeah, I did this for myself in my forked repo, and found really useful to export AMQP-CPP, but asking if this can be added in the main repo through a PR.
