### ISSUE TITLE
How to use epoll with this library 

### ISSUE THREAD

**Issue by achandak123** [CopernicaMarketingSoftware/AMQP-CPP#61]
Thanks Emiel for your prompt response. I am trying to understand the usage. I am using the TcpHandler. In the monitor function, i get the fd, which i am adding on my select. However, what i didn't get is, how to receive on this fd. So, lets say this fd becomes readable, should i call size_t parse(char *buffer, size_t size)? Then, whats the use of channel.consume(name, AMQP::noack).onReceived(receiveMessageCallback)?

After spending some more time, correct me, if this is the flow
On fd becoming readable, call connection->process, which in turn will call the callback registered with the channel via channel.consume??

Second basic issue:

Here is my test file. I was expecting onConnected callback to be called, however i don't see any of my debugs showing up.  The only output i see is this:

Fd 3 Flags 1
3

However the fd for tcp socket is 5

test    26268 achandak    2u   CHR 136,62      0t0          65 /dev/pts/62
test    26268 achandak    3r  FIFO    0,8      0t0   197998650 pipe
test    26268 achandak    4w  FIFO    0,8      0t0   197998650 pipe
test    26268 achandak    5u  sock    0,6      0t0   197997790 protocol: TCP

I was expecting the monitor to give the fd as 5 and i can do a select on it?

#include <amqpcpp.h>
#include <sys/select.h>
using namespace std;

fd_set      rfds;
class MyTcpHandler : public AMQP::TcpHandler
{
private:
    /**
     *  Method that is called when the connection succeeded
     *  @param  socket      Pointer to the socket
     */
    virtual void onConnected(AMQP::TcpConnection *connection)
    {
        std::cout << "connected" << std::endl;
    }

    /**
     *  When the connection ends up in an error state this method is called.
     *  This happens when data comes in that does not match the AMQP protocol
     *
     *  After this method is called, the connection no longer is in a valid
     *  state and can be used. In normal circumstances this method is not called.
     *
     *  @param  connection      The connection that entered the error state
     *  @param  message         Error message
     */
    virtual void onError(AMQP::TcpConnection *connection, const char *message)
    {
        // report error
        std::cout << "AMQP TCPConnection error: " << message << std::endl;
    }

    /**
     *  Method that is called when the connection was closed.
     *  @param  connection      The connection that was closed and that is now unusable
     */
    virtual void onClosed(AMQP::TcpConnection *connection)
    {
        std::cout << "closed" << std::endl;
    }

    /**
     *  Method that is called by AMQP-CPP to register a filedescriptor for readability or writability
     *  @param  connection  The TCP connection object that is reporting
     *  @param  fd          The filedescriptor to be monitored
     *  @param  flags       Should the object be monitored for readability or writability?
     */
    virtual void monitor(AMQP::TcpConnection *connection, int fd, int flags)
    {
        // we did not yet have this watcher - but that is ok if no filedescriptor was registered
        if (flags == 0) return;
        cout << "Fd "<< fd << " Flags " << flags << endl;
        if (flags & AMQP::readable) {
            FD_SET(fd, &rfds);
            gfd = fd;
        }
    }
public:
    int  gfd = -1;
};

int main(int argc, const char* argv[])
{
    MyTcpHandler myHandler;
    int maxfd = 1;
    int result = 0;

    // address of the server
    AMQP::Address address("amqp://guest:guest@localhost/");

    // create a AMQP connection object
    AMQP::TcpConnection connection(&myHandler, address);

    // and create a channel
    AMQP::TcpChannel channel(&connection);

    channel.onError([](const char *message) {
        cout << "channel error: " << message << endl;
    });
    channel.onReady([]() {
        cout << "channel ready " << endl;
    });
    //channel.declareExchange
    do {
        FD_ZERO(&rfds);
        FD_SET(0, &rfds);
        cout << myHandler.gfd << endl;
        if (myHandler.gfd != -1) {
            maxfd = myHandler.gfd + 1;
        }
        result = select(maxfd, &rfds, NULL, NULL, NULL);
        if ((result == -1) && errno == EINTR) {
            cout << "Error in socket" << endl;
        } else if (result > 0) {
            cout << "Got something" << endl;
            if (FD_ISSET(myHandler.gfd, &rfds)) {
            }
        }
    }while(1);
}

**Comment by EmielBruijntjes** [comment]
I am only going to answer your first question, because I think to take one step a time is the right approach.

The question was: what should you do when the file descriptor becomes readable?

There are two possible answers, depending on how you use the AMQP-CPP lib:

1. You use the "AMQP::Connection" class
2. You use the "AMQP::TcpConnection" class

Let's assume you are in scenario 1. In that case it is _your_ responsibility to read the file descriptor and  _you_ should do the "read()" or "recv()" system call to collect the bytes, and then call the connection.parse() method to hand over the received bytes to the AMQP-CPP library.

However, in your case you're not in scenario 1 because you use the AMQP::TcpConnection class instead. This means that you do not have to do the the "read()" or "recv()" system call yourself, and that the "Connection::parse()" method does not have to be called either. You can simply call the "connection.process()" method to tell the AMQP-CPP tibrary that the fd is readable. The library will do the rest.

In your main select loop, you are now not doing anything meaningful. You should change this, and simply call "connection.process()" when the AMQP connection is readable. The library will do the rest.

Good luck!

**Comment by achandak123** [comment]
Thanks for your quick reply. Simple question, how do i get the socket fd? because thats what i need to put in my select loop.
I see my monitor getting called with the fd of the pipe opened in TcpResolver. I am currently doing the select on that, which doesn't look right.

**Comment by achandak123** [comment]
Thanks Emiel, i was able to get the socket fd. That brings me to the second part of my question. When this fd becomes readable, should i just do connection->process on that fd? How do i get the received buffer. I looked at virtual TcpState *process and its not returning the recvd buffer. I am pretty sure, i am missing something here???

**Comment by EmielBruijntjes** [comment]
It is an event driven design. when you call the process() method, the AMQP-CPP library is going to handle the events on the filedescriptor. If the fd becomes readable, it will read data from it, when it becomes writable, it sends possibly buffered bytes to it, and so on.

When the AMQP-CPP library reads data, it will process and interpret that data and possible pass it to the callback functions passed from user space. If you started a consume operation, this could for example be the callback function registered for consuming.

**Comment by achandak123** [comment]
Thanks Emiel. I have implemented a simple rpc client in C, using this library. The RPC server is in python. The request sent by the client is received by the server and responded back as well. However, on the client, the onReceived callback is not getting called. I do see the socket fd becoming readable and i am calling the connection->process and as you explained, expecting the onReceived callback to be called. If you don't mind, could you please give some details about the process chaining? as to how is onReceived supposed to be called, so that i can add some more debugs. I am trying to figure out myself as well, but it will be faster if you could guide me. Really appreciate your help.
