### ISSUE TITLE
Erroneous instructions in readme

### ISSUE THREAD

**Issue by biot023** [CopernicaMarketingSoftware/AMQP-CPP#65]
Hi -- I'm using the latest GCC, and have found this section at the end of the readme to be wrong:

    // start consuming from the queue, and install the callbacks
    channel.consume("my-queue")
        .onSuccess(startCb)
        .onError(errorCb)
        .onReceived(messageCb);

It generates this error:

    error: 'class AMQP::Deferred' has no member named 'onReceived'

I guess because the `onError` method returns a `Deferred` object that doesn't know about `onReceived`.

Changing the code to this fixed it:

    // start consuming from the queue, and install the callbacks
    channel.consume("my-queue")
        .onReceived(messageCb)
        .onSuccess(startCb)
        .onError(errorCb)
        ;

**Comment by EmielBruijntjes** [comment]
You are right, I have changed it.
