### ISSUE TITLE
The problem to send a big message (10K) in RPC

### ISSUE THREAD

**Issue by xupanwilson** [CopernicaMarketingSoftware/AMQP-CPP#66]
I use the asiohandler in the examples folder to write a rpc service， I my code, I send the following message FibS to the server side and then receive the FibS message from server side.
	struct FibS {
		int a;
		char b[1024 * 10];
	};
If the size of b is a small one, like 1024*5, the send and receive goes well, If the size of b is a big one like 1024*10, then the send and receive are all failed. The server side can't get the request and the client side can't get the response too.

I want to know if there is any restraint in the size of the Message?

Thanks a lot

**Comment by xupanwilson** [comment]
The following is my rpc_server.cpp and rpc_client.cpp.
rpc_server.cpp:
`#include <iostream>
#include <algorithm>
#include <thread>
#include <chrono>

#include "asiohandler.h"
using namespace std;
int fib(int n)
{
    switch (n)
    {
    case 0:
        return 0;
    case 1:
        return 1;
    default:
        return fib(n - 1) + fib(n - 2);
    }
}
struct FibS
{
	int a;
	char b[1024*10];
};
int main(void)
{
    boost::asio::io_service ioService;
    AsioHandler handler(ioService);
    handler.connect("168.1.1.50", 5672);
    AMQP::Connection connection(&handler, AMQP::Login("epri", "123456"), "/");
    AMQP::Channel channel(&connection);
    channel.setQos(1);

    channel.declareQueue("rpc_queue",AMQP::autodelete);
    channel.consume("").onReceived([&channel](const AMQP::Message &message,
            uint64_t deliveryTag,
            bool redelivered)
    {

    	std::cout << " [x] Got a message." << std::endl;



		if (message.bodySize() == sizeof(FibS))
		{
			FibS *f = (FibS*)message.body();
			std::cout<<" [.] Got "<<f->a<<":"<<f->b<<std::endl;

			int sum = fib(f->a);

			FibS s;
			s.a = sum;
			std::string name = "Hello, I am a big object from server.";
			strcpy(s.b, name.c_str());

			char* buf;
			unsigned int buf_size;
			buf = (char*)malloc(sizeof(FibS));
			memcpy(buf, (char*)&s, sizeof(s));
			buf_size = sizeof(s);


			AMQP::Envelope env((const char*)buf,buf_size);
			env.setCorrelationID(message.correlationID());

			channel.publish("", message.replyTo(), env);
			channel.ack(deliveryTag);
		}
		else
		{
			std::cout << " [x] Got a error message." << std::endl;
		}
    });

    std::cout << " [x] Awaiting RPC requests" << std::endl;

    ioService.run();
    return 0;
}
`

rpc_client.cpp:
`#include <iostream>

#include "tools.h"
#include "asiohandler.h"
struct FibS
{
	int a;
	char b[1024*10];
};
int main(int argc, const char* argv[])
{
    const std::string correlation(uuid());

    boost::asio::io_service ioService;
    AsioHandler handler(ioService);
    handler.connect("168.1.1.50", 5672);

    AMQP::Connection connection(&handler, AMQP::Login("epri", "123456"), "/");

    AMQP::Channel channel(&connection);
    AMQP::QueueCallback callback = [&](const std::string &name,
            int msgcount,
            int consumercount)
    {
    	FibS s;
		s.a = 8;
		std::string m = "Hello, I am a big object from client.";
		strcpy(s.b, m.c_str());

		char* buf;
		unsigned int buf_size;
		buf = (char*)malloc(sizeof(FibS));
		memcpy(buf, (char*)&s, sizeof(s));
		buf_size = sizeof(s);

		AMQP::Envelope env((const char*)buf,buf_size);
        env.setCorrelationID(correlation);
        env.setReplyTo(name);
        channel.publish("","rpc_queue",env);
        std::cout<<" [x] Requesting fib(8)"<<std::endl;

    };
    channel.declareQueue(AMQP::exclusive).onSuccess(callback);

    boost::asio::deadline_timer t(ioService, boost::posix_time::millisec(10000));

    auto receiveCallback = [&](const AMQP::Message &message,
            uint64_t deliveryTag,
            bool redelivered)
    {
    	std::cout << " [x] Got a reply." << std::endl;
        if(message.correlationID() != correlation)
            return;

        FibS s;
        memcpy(&s,message.body(),message.bodySize());
        std::cout<<" [.] Got "<<s.a<<":"<<s.b<<std::endl;
        t.async_wait([&](const boost::system::error_code&){ioService.stop();});
    };

    channel.consume("", AMQP::noack).onReceived(receiveCallback);

    ioService.run();
    return 0;
}
`

**Comment by EmielBruijntjes** [comment]
Do you have the same problem if you use a different type of handler? Like the libev handler?

**Comment by xupanwilson** [comment]
OK, I will hava a try. Thanks for you answer. And I will give your a reply soon.

**Comment by xupanwilson** [comment]
In libev.h, it say  *  Compile with: "g++ -std=c++11 libev.cpp -lamqpcpp -lev -lpthread", where can I find the libev.cpp?

**Comment by xupanwilson** [comment]
Actually, No need to use libevhandler, Just modify the bufsize in the asiohandler.h to a bigger one, everything will be ok.

**Comment by shbharath** [comment]
Changing the bufsize in asiohandler.h works. Sender is able to send message of any length. Receiver should also be able to receive the message of any length. Both of them should not have message size in the contract
