### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by daedric** [CopernicaMarketingSoftware/AMQP-CPP#69]
Hi,
I wrote an AsioHandler (inspired from the one in examples), that is safe to share amongst thread however, there is no mention whether or not it is safe to share an AMQP::Connection.
Also is it safe to have several AMQP::Connection on the same handler ?

Thanks,

**Comment by EmielBruijntjes** [comment]
It is **not** safe to call methods on one connection object from multiple threads at the same time.

The AMQP::ConnectionHandler class is just an interface. If your own derived class is thread safe completely depends on your own implementation.
