### ISSUE TITLE
channel.cancel usage

### ISSUE THREAD

**Issue by mowaiskhan** [CopernicaMarketingSoftware/AMQP-CPP#70]
Hello,

I have been trying to work on a solution where I can receive from queue whenever application wants. Hence, I modified the example, receive.cpp as below but I can't make it work.

	#include <iostream>
	#include <boost/date_time/posix_time/posix_time.hpp>
	#include "asiohandler.h"

	boost::asio::io_service ioService;
	AsioHandler handler(ioService);
	AMQP::Connection connection(&handler, AMQP::Login("guest", "guest"), "/");
	AMQP::Channel channel(&connection);

	int receive(void)
	{
			handler.connect("localhost", 5672);
			channel.declareQueue("hello");
			channel.consume("hello", AMQP::noack).onReceived(
				[](const AMQP::Message &message,
						   uint64_t deliveryTag,
						   bool redelivered)
				{
			std::string ss  = message.message();
			std::cout <<" [x] Received["<< std::endl;
			std::cout << ss << std::endl ;
			std::cout <<"]"<< std::endl;

			channel.cancel("hello").onSuccess([](const std::string& tag) 
						{
							   std::cout << "onSuccess::Stopped consuming under tag " << tag << std::endl;
					   });
			channel.cancel("hello").onFinalize([]() 
						{
							   std::cout << "onFinalize::Stopped consuming" << std::endl;
							   ioService.stop();
					   });
				});
		ioService.run();
	}

	int main(void)
	{
		std::cout << " [*] Waiting for messages. To exit press CTRL-C\n";
			receive();
				cout << endl << "Here-1" << endl;
			receive();
				cout << endl << "Here-2" << endl;
			receive();
				cout << endl << "Here-3" << endl;
		return 0;
	}

The output,I got is 

[*] Waiting for messages. To exit press CTRL-C
[x] Received[hello]
onSuccess::Stopped consuming under tag hello
onFinalize::Stopped consuming

Here-1

Here-2

Here-3

I was expecting
[*] Waiting for messages. To exit press CTRL-C
[x] Received[hello]
onSuccess::Stopped consuming under tag hello
onFinalize::Stopped consuming
Here-1
[x] Received[hello]
onSuccess::Stopped consuming under tag hello
onFinalize::Stopped consuming
Here-2
[x] Received[hello]
onSuccess::Stopped consuming under tag hello
onFinalize::Stopped consuming
Here-3

I will appreciate help on this.

Thanks & Regards,
Owais.

**Comment by EmielBruijntjes** [comment]
If you want to receive one message at a time, better call channel.get(). It is probably better to either keep the connection connected all the time, or make the handler, connection and channel variables local.

**Comment by mowaiskhan** [comment]
Thanks for quick reply. I modified above code to use channel.get

Now, if you run this program first, it won't receive any messages at all.

If you run sender first(sample send.cpp) and few messages are being sent and you start receiver, it will get the message. 

Strange thing is that It keeps receiving same message if you run this program again and again.

	#include <boost/date_time/posix_time/posix_time.hpp>

	#include "asiohandler.h"
	#include "msgpackdemo.h"


	int receive(void)
	{
			boost::asio::io_service ioService;
			AsioHandler handler(ioService);
			AMQP::Connection connection(&handler, AMQP::Login("guest", "guest"), "/");
			AMQP::Channel channel(&connection);
			handler.connect("localhost", 5672);
			channel.declareQueue("hello");
			
			channel.get("hello").onSuccess([](const AMQP::Message &message, uint64_t deliveryTag, bool redelivered) {

			std::cout << "Message fetched" << std::endl;
			std::string ss  = message.message();
			std::cout <<" [x] Received["<< std::endl;
			cout << ss << endl;
			std::cout <<"]"<< std::endl;
			
		   }).onEmpty([]() {

			   std::cout << "Queue is empty" << std::endl;

		   });

		ioService.run();
	}

	int main(void)
	{
		std::cout << " [*] Waiting for messages. To exit press CTRL-C\n";
			receive();
				cout << endl << "Here-1" << endl;
			receive();
				cout << endl << "Here-2" << endl;
			receive();
				cout << endl << "Here-3" << endl;
		return 0;
	}
