### ISSUE TITLE
channel.get usage

### ISSUE THREAD

**Issue by mowaiskhan** [CopernicaMarketingSoftware/AMQP-CPP#71]
Hello,

In issue #70 , I was advised to use channel.get to receive messages from queue if consumer is intermittent receiver.

I modified above receive.cpp code's from example directory to use channel.get feature.

Now, if you run this program first, it won't receive any messages at all.

But, If you run sender first(example directory send.cpp) and few messages are being sent to RabbitMQ and then you start receiver, it will get the message the first message which was sent.

Strange thing is that It keeps receiving same first message if you run this program again and again.

I tried finding channel.get working sample but couldn't find it anywhere.

I will appreciate any help.

Thanks & Regards,
Owais.

	#include <boost/date_time/posix_time/posix_time.hpp>
	#include "asiohandler.h"
	#include "msgpackdemo.h"

	int receive(void)
	{
			boost::asio::io_service ioService;
			AsioHandler handler(ioService);
			AMQP::Connection connection(&handler, AMQP::Login("guest", "guest"), "/");
			AMQP::Channel channel(&connection);
			handler.connect("localhost", 5672);
			channel.declareQueue("hello");

			channel.get("hello").onSuccess([](const AMQP::Message &message, uint64_t deliveryTag, bool redelivered) {

			std::cout << "Message fetched" << std::endl;
			std::string ss  = message.message();
			std::cout <<" [x] Received["<< std::endl;
			cout << ss << endl;
			std::cout <<"]"<< std::endl;

		   }).onEmpty([]() {

			   std::cout << "Queue is empty" << std::endl;

		   });

		ioService.run();
	}

	int main(void)
	{
		std::cout << " [*] Waiting for messages. To exit press CTRL-C\n";
			receive();
				cout << endl << "Here-1" << endl;
			receive();
				cout << endl << "Here-2" << endl;
			receive();
				cout << endl << "Here-3" << endl;
		return 0;
	}

**Comment by EmielBruijntjes** [comment]
Don't forget to acknowledge your messages using channel.ack(deilveryTag). If you do not ack a message, it is put back in the queue. This prevents that messages ever get lost when your client suddenly crashes.

**Comment by mowaiskhan** [comment]
Thanks for reply, 

channel.ack(deilveryTag)  usage got the message removed from queue.

I got few more questions.

1) If there is no message in the queue when receiver is run, It enters into channel.get.onEmpty function and never receives anything again until program is restarted.

2) If there is a message in the queue when receiver is run, It enters into channel.get.onSuccess function and received the message and never receives anything again until program is restarted.

3) If i break the ioService.run by caling ioService.stop in channel.get.onSuccess or channel.get.onEmpty and try to run it again by calling ioService.run it never works.

Thanks & Regards,
Owais.

**Comment by mowaiskhan** [comment]
I just observed a problem, you can't specify "tag" in get like you do in "consume" function :|

I think I should revert to consume method and try to use pause and resume? What do you advice.

Thanks & Regards,
Owais.

**Comment by mowaiskhan** [comment]
I tried calling channel.pause().onSuccess from  channel.consume("hello", AMQP::noack).onReceived and received below error.

AMQP error NOT_IMPLEMENTED - active=false
Error reading:system:104

I googled and found it means method is not implemented.

**Comment by martijnotto** [comment]
Well that's clear, RabbitMQ does not implement this feature. I'll check if this is on the roadmap to be added and if not we'll remove this method.

The only alternative is to not pause but to simply cancel the consumer. This is basicaly what the .get() method does internally.
