### ISSUE TITLE
Build error for send.cpp

### ISSUE THREAD

**Issue by anmol81** [CopernicaMarketingSoftware/AMQP-CPP#75]
Hello , 

I am trying to build send.cpp present in tutorials . However i am getting two different errors : 

1)  ### __/usr/include/bits/waitstatus.h:79:27: error: redeclaration of ‘unsigned int wait::<anonymous struct>::__w_retcode’
   unsigned int __w_retcode:8;

2)  /usr/local/include/amqpcpp/outbuffer.h: In member function ‘void AMQP::OutBuffer::add(uint32_t)’:
 /usr/local/include/amqpcpp/outbuffer.h:173:35: error: ‘htobe32’ was not declared in this scope
          uint32_t v = htobe32(value);__

I have attached the console logs . 

[console_logs.txt](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/files/336816/console_logs.txt)

**Comment by martijnotto** [comment]
I have no idea why you get the waitstatus.h error, that's a system-provided include-file - which normally would have proper include guards. Please let me know if this is still an issue.

**Comment by anmol81** [comment]
Thanks for your reply . 

Can you please comment on the second problem : 

2) /usr/local/include/amqpcpp/outbuffer.h: In member function ‘void AMQP::OutBuffer::add(uint32_t)’:
/usr/local/include/amqpcpp/outbuffer.h:173:35: error: ‘htobe32’ was not declared in this scope
uint32_t v = htobe32(value);__

**Comment by martijnotto** [comment]
That issue should have been solved as well. Did you try compiling after pulling? If it does not work then we need to tweak include/endian.h so it works for you platform. What compiler and platform do you use?

**Comment by anmol81** [comment]
Following are the details : 
CentOS Linux release 7.2.1511 (Core)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

The endian.h file does not have code for Linux and is not within AMQP namespace.

**Comment by martijnotto** [comment]
CentOS is linux so you should come into the #else branch for this include, which simply includes <endian.h>. Apparantly CentOS does not define the htobe32 function/macro from this file.

Can you see which file we need to include or maybe which functions to macro over?

**Comment by RobWillis** [comment]
I'm hitting this issue as well.  Building with Docker image for gcc:7.3.0

**Comment by EmielBruijntjes** [comment]
There no longer is a "send.cpp" in this repository.

**Comment by RobWillis** [comment]
Sorry I was not clear, I was building my project which includes AMQP-CPP and was getting the exact same error as was seen on this older send.cp test file.  My errors below compiling with the Docker image for gcc:7.3.0:

In file included from /usr/local/include/amqpcpp/amqpcpp.h:45:0,
                 from /usr/src/ws/src/msgq_client/MsgqConnHandler.h:14,
                 from /usr/src/ws/src/msgq_client/MsgqSubscriber.cpp:8:
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h: In member function 'void AMQP::OutBuffer::add(uint16_t)':
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h:80:22: error: 'htobe16' was not declared in this scope
         uint16_t v = htobe16(value);
                      ^~~~~~~
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h: In member function 'void AMQP::OutBuffer::add(uint32_t)':
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h:93:22: error: 'htobe32' was not declared in this scope
         uint32_t v = htobe32(value);
                      ^~~~~~~
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h: In member function 'void AMQP::OutBuffer::add(uint64_t)':
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h:106:22: error: 'htobe64' was not declared in this scope
         uint64_t v = htobe64(value);
                      ^~~~~~~
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h: In member function 'void AMQP::OutBuffer::add(int16_t)':
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h:129:21: error: 'htobe16' was not declared in this scope
         int16_t v = htobe16(value);
                     ^~~~~~~
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h: In member function 'void AMQP::OutBuffer::add(int32_t)':
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h:142:21: error: 'htobe32' was not declared in this scope
         int32_t v = htobe32(value);
                     ^~~~~~~
/usr/local/include/amqpcpp/amqpcpp/outbuffer.h: In member function 'void AMQP::OutBuffer::add

**Comment by surgura** [comment]
Take a look at include/amqpcpp/endian.h. It seems like your platform is either not supported or does not define the correct preprocessor macro. If you figure out how to add your platform a pull request would be appreciated.

**Comment by RobWillis** [comment]
I figured out the issue.
I had added the /usr/local/include/amqpcpp to my include path which caused the compiler to pick up your "endian.h" instead of the system <endian.h>.
Seems to be compiling fine now that I removed that include path.

**Comment by Enigma228322** [comment]
If you using for example **ubuntu/debian** in the end of AMQP-CPP/include/amqpcpp/endian.h file you can see https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/master/include/amqpcpp/endian.h#L142.
Which means that you are using endian.h from **/usr/include**
