### ISSUE TITLE
It takes too long to retriev queue size by declaring queue with passive flag 

### ISSUE THREAD

**Issue by TianBo-Timothy** [CopernicaMarketingSoftware/AMQP-CPP#82]
I was trying to implement flow-control based on the size of the queue (message count in the queue). To get the size of the queue, I created a new channel (using existing connection) and declared the queue with passive flag.

The problem is the installed onSuccess() callback does not always be called (if rabbitmq server is busy), or take two long to get a response (2~5 seconds after the declaration, if the server is not busy). So that the flow-control can not function properly as there is no reliable way to get the queue size.

The code to retrieve queue size is as follows:

~~~cpp

class MyClass
{
    // ...
private:
    void getQueueSize(const std::string & queueName);
    int m_lastQueueSize;
};

void MyClass::getQueueSize(const std::string & queueName)
{
    static std::unique_ptr<AMQP::TcpChannel> channel;

    channel.reset(new AMQP::TcpChannel(m_amqpConnection.get()));

    channel->onError([&](const char * errMsg) {
       // log the error
        myLog << errMsg;
    });

   // log a message to show this function is called
    myLog << "test: try to get size of queue " << queueName;

    channel->declareQueue(queueName, AMQP::passive).onSuccess(
            [&](const std::string &name, uint32_t messageCount, uint32_t consumerCount) {
        m_lastQueueSize = messageCount;
        // log the queue size
        myLog << "test: the queue size is: " << m_lastQueueSize;
    });
}

~~~

MyClass::getQueueSize() is called periodically (every 5 seconds). The following is from the created log file (in this case, all queues are empty and the server is then non-busy).

Jul 11 15:14:06 MyConnector[11039]: test: try to get size of queue queue.MyConnector
Jul 11 15:14:08 MyConnector[11039]: test: the queue size is: 0 
Jul 11 15:14:10 MyConnector[11039]: test: try to get size of queue queue.MyConnector
Jul 11 15:14:14 MyConnector[11039]: test: the queue size is: 0 
Jul 11 15:14:16 MyConnector[11039]: test: try to get size of queue queue.MyConnector
Jul 11 15:14:20 MyConnector[11039]: test: try to get size of queue queue.MyConnector
Jul 11 15:14:20 MyConnector[11039]: test: the queue size is: 0 
Jul 11 15:14:24 MyConnector[11039]: test: the queue size is: 0 
Jul 11 15:14:26 MyConnector[11039]: test: try to get size of queue queue.MyConnector
Jul 11 15:14:30 MyConnector[11039]: test: try to get size of queue queue.MyConnector
Jul 11 15:14:30 MyConnector[11039]: test: the queue size is: 0

As you can see, the response came after a few seconds. When the server is busy, the log message rarely shows the queue size message and occasionally a queue size is printed out but the size is much  different with the number in the RabbitMQ management page.

In the log file, I did not see any error message from AMQPCPP, so I assume onError() callback is not called.

Additional information:
OS: Ubuntu 15.10
RabbitMQ: 3.6.3
AMQPCPP: 2.5.0

**Comment by EmielBruijntjes** [comment]
Why do you think that this is a AMQP-CPP error?

**Comment by TianBo-Timothy** [comment]
I am not sure about is it a AMQP-CPP error or RabbitMQ error. Can you give me a clue to find it out?

**Comment by TianBo-Timothy** [comment]
The following is one of many Declare/Declare-ok messages captured by wireshark. It looks that the Declare-Ok message comes back almost immediately.

![image](https://cloud.githubusercontent.com/assets/16188280/16733884/ab5389ce-4783-11e6-9678-c9420ba797af.png)

**Comment by EmielBruijntjes** [comment]
My guess is that your event loop is not constantly running. Or is it?

**Comment by TianBo-Timothy** [comment]
I think the event loop is running well as the publishing is quite fast (if there are messages) and all periodical tasks are executed.

**Comment by EmielBruijntjes** [comment]
````c++
static std::unique_ptr<AMQP::TcpChannel> channel;
channel.reset(new AMQP::TcpChannel(m_amqpConnection.get()));
````

You don't need a static unique-ptr. Just a temporary channel on the stack will do too:

````
AMQP::TcpChannel channel(m_amqpConnection.get())'
````

**Comment by TianBo-Timothy** [comment]
I agree. The original code is like what you wrote here. As there is the problem, I re-wrote it to avoid possible object scope problem.

However, the result is the same.

I also tried to declare the queue using AMQP::durable (the same flag used at the first time), it improves  a little bit when RabbitMQ server is busy - I can get responses more often but still not reliable. When the server is not busy, the behavior is almost identical as to use AMQP::passive.

**Comment by EmielBruijntjes** [comment]
I cant help you with only half of your code. Can you please send in the _smallest possible_ example program in which the error occurs?

**Comment by TianBo-Timothy** [comment]
OK. I will make a small program to see if I can reproduce it.

**Comment by TianBo-Timothy** [comment]
I made a small program. but there is no problem with this simple program when retrieving queue size. I will update this when I find something new.

**Comment by TianBo-Timothy** [comment]
Here I attached a small program that might reproduce the problem.

The interesting part is from line 58 - the lambda function to be installed by onSuccess(). I was trying to print out a time measurement, but the value is incorrect. So I added a simple test variable (called test_value) and print its value inside the lambda function, but the value changes to 0.

This behavior is strange. It seems the value capturing does not work properly here. As the time measurement cannot be done, I cannot give an exact time but it takes quite long.

[amqp-queue-size-test.cpp.zip](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/files/359149/amqp-queue-size-test.cpp.zip)

**Comment by EmielBruijntjes** [comment]
dont call microsleep()

**Comment by EmielBruijntjes** [comment]
And you can't capture local variables like that. The lambda is going to be called when the start() function is already out-of-scope.

**Comment by TianBo-Timothy** [comment]
I fixed the problems in the test program. Those problems are not related to the original problem I described.

I can now reproduce the problem in this small program - just by publishing a message in idle task. Please  have a look at cb_idle() in the source code.

@EmielBruijntjes , can we re-open this issue when you confirmed it?

[amqp-queue-size-test.cpp.zip](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/files/361155/amqp-queue-size-test.cpp.zip)
