### ISSUE TITLE
Header conflict with Qt 5.5

### ISSUE THREAD

**Issue by half45** [CopernicaMarketingSoftware/AMQP-CPP#83]
When I try include any Qt header first:

```C
#include <QApplication>
#include <amqpcpp.h>
```

build failed with:

```
/usr/include/amqpcpp/deferredconsumerbase.h:89:31: ошибка: expected «)» before «&&» token
     virtual void emit(Message &&message, uint64_t deliveryTag, bool redelivered) const = 0;
                               ^

/usr/include/amqpcpp/deferredconsumer.h:50:23: ошибка: expected «)» before «&&» token
     void emit(Message &&message, uint64_t deliveryTag, bool redelivered) const override;
                       ^
/usr/include/amqpcpp/deferredget.h:67:23: ошибка: expected «)» before «&&» token
     void emit(Message &&message, uint64_t deliveryTag, bool redelivered) const override;
```

Unfortunately, I can't locate the source of the problem

**Comment by schoentoon** [comment]
Are you compiling with `-std=c++11`? This is a hard requirement for this library.

**Comment by half45** [comment]
I use gcc 5.2 and `set(CMAKE_CXX_STANDARD 11)` in my CMakeLists.
If I place `#include <amqpcpp.h>` to top of file or remove `#include <QApplication>` then build done without errors

**Comment by Kojoley** [comment]
`CMAKE_CXX_STANDARD 11` have no effect if your `cmake` version is not `>= 3.1` or if you do not set `CMAKE_CXX_STANDARD_REQUIRED ON`

**Comment by half45** [comment]
`cmake version 3.3.2` used

**Comment by schoentoon** [comment]
I think I know what's going on here, from previous experiences with Qt I know that emit is used quite often. Therefore I suspect this is some kind of macro and our headers are getting changed due to that. Currently I can't think of a proper solution for this sadly.

**Comment by schoentoon** [comment]
It seems that this emit method is only a private function that is used inside our own .cpp files. As you already mentioned yourself if you include amqpcpp.h before you include anything from Qt it does compile. Therefore I think that this is the best solution I can give you.

**Comment by wulinwulin76** [comment]
As schoentoon commented, change the order of include to:
#include <amqpcpp.h>
#include <QApplication>

**Comment by mridulwebengineer** [comment]
I want to use this inside my QT application. Please help me .

**Comment by martijnotto** [comment]
What exactly do you need help with? Does making sure amqpcpp.h is included first not work for you? Can you please post a code sample that illustrates the problem?

**Comment by mridulwebengineer** [comment]
I want to use boost as Network layer with AMQP CPP and QT for GUI part. If you have such example please send me. Both have different event loop etc. I don't have too much advance knowledge for integrating both event loop etc.  I'll share code soon.
