### ISSUE TITLE
Declaring queue from other thread may cause onSuccess CB not to be called

### ISSUE THREAD

**Issue by cweigel** [CopernicaMarketingSoftware/AMQP-CPP#90]
Since several days I am tracking down an issue that causes a callback registered with DefferedQueue::onSuccess() not to be called. I could track it down now and want to ask if this is to be expected or to be seen as a bug. Basically the issue is: When creating a channel, declaring a queue and registering a success callback on a queue in a thread that is different from the thread that is handling incoming messages it might happen that the CB is registered TOO late (aka later than the time the channelimpl calls the CB in reportSuccess() ) Here' an exemplary time line:
```
MAIN THREAD                           | 
                                      |        
asion connection thread ----->        | RECEIVE THREAD (doRead loop)                              |
                                      | 
new Channel                           | 
                                      | 
onReady(channelReadyCB)               | 
                                      | 
channelReadyCB                        t 
                                      i 
declareQueue                          m 
    send Frame                        e 
    push                              | 
                                      | receive ACK Frame
    do some more                      | 
    do some more                      | reportSuccess
    do some more                      | /////  NO CALLBACK YET REGISTERED ///// 
                                      | /////  calling only Deferred CB   /////
                                      | 
    return Deferred                   | 
                                      | 
/////Register success CB -> TOO LATE  | 
onSuccess(queueSuccessCB)             | 
                                      | 
```

Using AMQP-CPP 2.6.1 with RabbitMQ server 3.6.5 on Debian 8.0

**Comment by EmielBruijntjes** [comment]
connections are not thread safe. You cannot access one connection (or one of the channels on top of a connection) from multiple threads at the same time.

**Comment by cweigel** [comment]
But shouldn't that be possible? I basically follow the recommendation of the doc " If, for example, you notice in your event loop that the socket that is connected with the RabbitMQ server becomes readable, you should read out that socket (for example by using the recv() system call), and pass the received bytes to the AMQP-CPP library." which is done in a separate thread (what I call RECEIVE THREAD in the example above). It basically means that once you started to listen to events you are not allowed to use the connection for declaring queues etc. unless you do it in event callbacks. Would I need to create another connection to do so? Or am I getting something completely wrong?

**Comment by EmielBruijntjes** [comment]
Just don't use threads. Use an event loop.
