### ISSUE TITLE
AMQP error UNEXPECTED_FRAME - expected content header for class 60, got non content header frame instead Error reading:system:104

### ISSUE THREAD

**Issue by vinodkumar1985** [CopernicaMarketingSoftware/AMQP-CPP#91]
Hi Please help me, I am facing issue for that,

#include <iostream>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <thread>
#include "asiohandler.h"

int main(void)
{
        try
        {

                boost::asio::io_service ioService;
                AsioHandler handler(ioService);
                handler.connect("localhost", 5672);
                AMQP::Connection connection(&handler, AMQP::Login("guest", "guest"), "/");
                AMQP::Channel channel(&connection);
                std::thread t([&ioService](){ioService.run(); });
                //ioService.run();
                boost::asio::deadline_timer tm(ioService, boost::posix_time::millisec(100));
                int i=0;
                while(1)
                {
                        channel.onReady([&]()
                                        {
                                        if(handler.connected())
                                        {

                                        {
                                        const std::string msg="A missed call on Nirmal's father Prasanna's cellphone on August 14 got the police going. Vasaigaon inspector Sampatrao Patil activated his contacts and traced the call to Surat. He contacted his counterparts in Amroli and traced Nirmal to a shanty belonging to a pani puri vendor Karan Singh.While it is unclear whether the call was made by Singh to extort money from Prasanna, he admitted to having failed in intimating the cops about Nirmal. The teen is believed to have approached Singh for a job when he learnt that had lost his direction. Nirmal during his stay with Singh had shared his family details.Nirmal who lost his mother a few months ago used to speak about wanting to fight terrorists in Kashmir. His friends had ridiculed him. According to Prasanna who works in the BMC, Nirmal loves history and has spoken about wanting to go to Kashmir. But I never thought he would think of venturing out alone. The current crisis in Kashmir had disturbed the boy.\n";
                                        //Envelope Emsg(msg.c_str(),msg.length());
                                        channel.publish("", "hello", msg);
                                        std::cout <<":Time:"<<time(0)<<",[x] Sent 'Hello World!'\n" << std::endl;
                                        }
                                        }
                                        });

                        //tm.async_wait([&](const boost::system::error_code&){ioService.stop();});
                        usleep(5);
                }
                t.join();
        }
        catch (std::exception& e)
        {
                std::cerr << "Exception: " << e.what() << "\n";
        }
        return 0;
}

**Comment by vinodkumar1985** [comment]
Please help me I am facing issue

**Comment by EmielBruijntjes** [comment]
A connection or channel object is not thread safe.

**Comment by vinodkumar1985** [comment]
how can push message continues

**Comment by vinodkumar1985** [comment]
Sir my requirement,push message continues
