### ISSUE TITLE
Do I need assure that messages were sent before breaking underlying event loop?

### ISSUE THREAD

**Issue by hoxnox** [CopernicaMarketingSoftware/AMQP-CPP#95]
I'm using my own libevent loop with AMQP-CPP. Suppose I published a lot of messages, but connection is very slow. Now I want to call event_base_loopbreak and close application. Do I need to check somehow, that all messages were sent? If so, how can I do it?

**Comment by Kojoley** [comment]
From [README.md](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/2a0b0de409bf6e6dff2419621fe7cacaad0b03ad/README.md)

```markdown
WORK IN PROGRESS
================

Almost all AMQP features have been implemented. But the following things might
need additional attention:

    -   ability to set up secure connections (or is this fully done on the IO level)
    -   login with other protocols than login/password
    -   _publish confirms_
    -   returned messages
```

**Comment by EmielBruijntjes** [comment]
It is better not to stop the event loop in the middle of operations. The most elegant way to stop the application is by closing or destructing the amqp connection. It will unregister itself from the event loop, and the application comes automatically to an end.

Alternatively, you can call connection.close(), and wait for the ConnectionHandler::onClosed() method to be called.

**Comment by hoxnox** [comment]
Does called onClosed() guaranties that all published messages were sent?

**Comment by EmielBruijntjes** [comment]
yes
