### ISSUE TITLE
How to return as quickly as possible when send a message, but not wait for the timeout.

### ISSUE THREAD

**Issue by xupanwilson** [CopernicaMarketingSoftware/AMQP-CPP#96]
int Request::publish(const char * buf, const int len)
{
	int ret = -1;
	boost::asio::io_service ioService;
	AsioHandler handler(ioService);
	handler.connect(host, port);
	AMQP::Connection connection(&handler, AMQP::Login(username, password), vhost);
	AMQP::Channel channel(&connection);

	boost::asio::deadline_timer t(ioService, boost::posix_time::millisec(timeout));

	AMQP::SuccessCallback cb = [&]()
	{
		channel.publish(rpc_queue, "", buf, len);
		ret = 1;
		ioService.stop();**//The comment line.**
	};

	channel.declareExchange(rpc_queue, AMQP::fanout).onSuccess(cb);

	t.async_wait([&](const boost::system::error_code&) { ret = -1; ioService.stop(); });
	ioService.run();
	return ret;
}
In the code before, 
if I comment out the 'ioService.stop(); ' line, the method will wait for the timeout, it is a waste of time.  
if I don't comment out the line, the publish is failed, there is no message received in the receive application.
How can I fix it? I want it return as soon as possible but not wait for the timeout happens.

**Comment by EmielBruijntjes** [comment]
This is not an AMQP-CPP issue, but a call for support with boost asio.

**Comment by martijnotto** [comment]
Why are you stopping the io_service? If you call AMQP::Connection::close, it will close the connection. Then either the io_service will stop on its own (because no more active sockets are registered on it) or you can stop it from the callback of the close() method.

**Comment by EmielBruijntjes** [comment]
The whole point here is that the question is wrong. The question should not be "what is the fastest way to **return** the result of an operation".

AMQP-CPP is an async library, and requires you to program in an async fashion. There is no way to publish a message and return the result of that operation. The publish operation takes much longer than the function call, and the result of it is not returned, but passed to the callback function.

In all of your questions you are constantly setting timers, starting threads, stopping the event loop or do other things to "wait" for the result of the operation. But you don't have to wait, the callback will be called when the operation is finished. Forget about timers and threads.

**Comment by xupanwilson** [comment]
The code upstairs is the method of publish, In my program, I am using it as following:

Request request;
if(request.publish(message) == 1) print("Ok");
else print("failed");

In the publish method, if I call connection.close() or ioService.stop(), the whole program will be closed, and I can't see any print info. If a don't call the connection.close() or ioService.stop(), then I can see the print info "OK", but I have to wait for the timeout point of the timer, and it is a waste of time. 

And there is no callback for channel.publish(rpc_queue, "", buf, len).onSuccess(), as the publish method  returns a bool result.

**Comment by xupanwilson** [comment]
The following is a test method changed from send.cpp in the examples of your project, If I use the connection.close, the message is send but the cout info in the main is never print, means the program is terminated, the output of the program is:

[d5000@qrtp1 rabbitmq_tutorials]$ ./send 
 [x] Sent 'Hello World!'0
AMQP closed connection
Error reading:system:9

 If I don't use the connection.close, then I have to wait for the timeout of the timer, and the output of the program is:

[d5000@qrtp1 rabbitmq_tutorials]$ ./send 
 [x] Sent 'Hello World!'0
error happend

The following is the test program:

int sendMessage()
{
    int ret = -1;
    boost::asio::io_service ioService;
    AsioHandler handler(ioService);
    handler.connect("192.1.101.83", 5672);

    AMQP::Connection connection(&handler, AMQP::Login("epri", "123456"), "/");
    AMQP::Channel channel(&connection);

    boost::asio::deadline_timer t(ioService, boost::posix_time::millisec(10000));
    channel.onReady([&]()
    {
        if(handler.connected())
        {
                for(int i=0;i<1;i++)
                        {
                                int a =100;
                                //channel.publish("test_publish", "", "Hello World!");
                                channel.publish("test_publish","",(char*)&a,sizeof(a));
                                std::cout << " [x] Sent 'Hello World!'" << i<< std::endl;
                        }
                connection.close();
                ret = 1;
                //ioService.stop();
            t.async_wait([&](const boost::system::error_code&){ret = -1 ;ioService.stop();});

        }
    });
    //std::cout << " [*] send messages. To exit press CTRL-C\n";
    ioService.run();
    return ret;
}
int main(void)
{
int ret = sendMessage();
if(ret == 1)
        cout<<"The message is sent, then I am going on the following code...."<<endl;
else cout<<"error happend"<<endl;
return 0;
}

**Comment by EmielBruijntjes** [comment]
Don't use timers.

**Comment by xupanwilson** [comment]
int MessageBus::publish(const char * buf, const int len)
{
	int ret = -1;
	boost::asio::io_service ioService;
	AsioHandler handler(ioService);
	handler.connect(host, port);
	AMQP::Connection connection(&handler, AMQP::Login(username, password), vhost);
	AMQP::Channel channel(&connection);

	channel.onError([&](const char* msg)
	{
		ret = -1;
		connection.close();
	});

	AMQP::SuccessCallback cb = [&]()
	{
		bool b = channel.publish(rpc_queue, "", buf, len);
		if(b) ret = 1;
		connection.close();
	};
	channel.declareExchange(rpc_queue, AMQP::fanout).onSuccess(cb);
	
	ioService.run();
	return ret;
}


In the code before, I don't use the timer, the result of the method is never returned, and the whole program which call the publish method is terminated too.
