### ISSUE TITLE
The subscrible fails after running some minutes.

### ISSUE THREAD

**Issue by xupanwilson** [CopernicaMarketingSoftware/AMQP-CPP#99]
In your commit, I find you have write something as fix the read error. And I updated my AMQPCPP and build a new library, but the example "receive_logs" failed soon in some minutes. 
The test file is "AMQP-CPP/examples/rabbitmq_tutorials/receive_logs.cpp"

The error message is:
Error reading:system:104

Can someone have a try, and give some help?

**Comment by xupanwilson** [comment]
The jave library for rabbitmq works fine, so it is not my rabbitmq server's problem.
The receive_logs program just runs about 5 minutes, then the program will exit. Both the windows and linux runs for the same result.

The code of the program is:

#include <iostream>
#include <boost/date_time/posix_time/posix_time.hpp>

#include "asiohandler.h"

int main(void)
{
    boost::asio::io_service ioService;
    AsioHandler handler(ioService);
    handler.connect("localhost", 5672);

    AMQP::Connection connection(&handler, AMQP::Login("guest", "guest"), "/");

    AMQP::Channel channel(&connection);
    auto receiveMessageCallback = [](const AMQP::Message &message,
            uint64_t deliveryTag,
            bool redelivered)
    {

        std::cout <<" [x] "<<message.message() << std::endl;
    };

    AMQP::QueueCallback callback =
            [&](const std::string &name, int msgcount, int consumercount)
            {
                channel.bindQueue("logs", name,"");
                channel.consume(name, AMQP::noack).onReceived(receiveMessageCallback);
            };

    AMQP::SuccessCallback success = [&]()
            {
                channel.declareQueue(AMQP::exclusive).onSuccess(callback);
            };

    channel.declareExchange("logs", AMQP::fanout).onSuccess(success);

    std::cout << " [*] Waiting for messages. To exit press CTRL-C\n";

    ioService.run();
    return 0;
}





If I have to change something in the code?

**Comment by xupanwilson** [comment]
I changed the event lib as libevent, but still the same problem, the subscrible program runs about 4 minutes and then exit.

Can you give me some suggestions?

**Comment by EmielBruijntjes** [comment]
Implement the ConnectionHandler interface, especially the onError() method, and pass that object to the Connection constructor. It allows you to check whether an error occurs on the connection.

Also make sure that the SIGPIPE event is blocked. You can do this by calling `signal(SIGPIPE, SIG_IGN)` right after the program starts.

**Comment by xupanwilson** [comment]
I am using the LibEventHandler, and I used the SIGPIPE, but the issue still exist, I paste my code as bellow you can have a look.

	int subScrible()
	{
		host = "192.1.101.83";
		port = 5672;
		user = "epri";
		password = "123456";
		timeout = 3;
		channelName = "testChannel";

                event_base *base = event_base_new();
		AMQP::LibEventHandler handler(base);
		AMQP::TcpConnection connection(&handler, AMQP::Address(host,port,AMQP::Login(user, password), "/"));
		AMQP::TcpChannel channel(&connection);
		//channel.
	    auto receiveMessageCallback = [](const AMQP::Message &message,
	            uint64_t deliveryTag,
	            bool redelivered)
	    {

	        std::cout <<"Receive: [x] "<<message.message() << std::endl;
	    };

		AMQP::ErrorCallback error = [&](const char * msg)
		{
			cout << msg << endl;
		};

	    AMQP::QueueCallback callback =
	            [&](const std::string &name, int msgcount, int consumercount)
	            {
	                channel.bindQueue(channelName, name,"");
	                channel.consume(name, AMQP::noack).onReceived(receiveMessageCallback).onError(error);
	            };

	    AMQP::SuccessCallback success = [&]()
	            {
	                channel.declareQueue(AMQP::exclusive).onSuccess(callback);
	            };

	    channel.declareExchange(channelName, AMQP::fanout).onSuccess(success);

	    std::cout << " [*] Waiting for messages. To exit press CTRL-C\n";

	    event_base_dispatch(base);
	    return 0;
	}
int main(int argc, const char* argv[])
{
	signal(SIGPIPE,SIG_IGN);
	int ret = cls.subScrible();
}

**Comment by xupanwilson** [comment]
Hey, man
do you have any ideas? What I am using is the TcpHandler, do you have any other suggestions?
Or can you have a try on the example code I paste upside?

**Comment by EmielBruijntjes** [comment]
No, I can't. Write a decent program first instead of this ugly code that you just copy-and-paste around.

**Comment by xupanwilson** [comment]
I got to know that the TcpConnection is write by yourself, can you give me some examples which can be run based on it?

I really can't find out why the subscriber program terminates, I have tried a lot, really don't know why, thanks a lot if you can provided me some examples.
